
export const translations = {
    fr: {
        metaTitle: "Blog Roue de la Chance | Astuces pour votre Roulette Aléatoire",
        metaDescription: "Découvrez des astuces de tirage au sort, des idées de jeux et les nouveautés de notre roulette en ligne. Le blog pour tout savoir sur la roue de la chance personnalisable.",
        title: "Blog de la Roue de la Chance",
        description: "Astuces, idées originales et actualités sur l'univers du tirage au sort et de la décision ludique.",
        readMore: "Lire la suite",
        by: "Par",
        previous: "Précédent",
        next: "Suivant",
        allPosts: "Tous les articles",
        searchPlaceholder: "Rechercher un article...",
        similarPosts: "Articles Similaires",
        noArticlesTitle: "Aucun article pour le moment...",
        noArticlesDescription: "De nouveaux articles arrivent bientôt. En attendant, pourquoi ne pas prendre une décision rapide ?",
        noArticlesButton: "Essayer la roue Oui/Non"
    },
    en: {
        metaTitle: "Spin Wheel Blog | Tips & Ideas for your Custom Wheel & Random Picker",
        metaDescription: "Discover prize draw tips, game ideas, and the latest news for our online spin wheel. The ultimate blog for everything about the custom random picker.",
        title: "Wheel of Chance Blog",
        description: "Tips, original ideas, and news from the world of random draws and fun decision-making.",
        readMore: "Read more",
        by: "By",
        previous: "Previous",
        next: "Next",
        allPosts: "All posts",
        searchPlaceholder: "Search for an article...",
        similarPosts: "Similar Articles",
        noArticlesTitle: "No articles yet...",
        noArticlesDescription: "New articles are coming soon. In the meantime, why not make a quick decision?",
        noArticlesButton: "Try the Yes/No Wheel"
    },
    es: {
        metaTitle: "Blog Ruleta de la Suerte | Consejos para tu Ruleta Giratoria",
        metaDescription: "Descubre consejos para sorteos, ideas de juegos y las últimas novedades de nuestra ruleta giratoria online. El blog para saberlo todo sobre la rueda de la fortuna.",
        title: "Blog de la Ruleta de la Suerte",
        description: "Consejos, ideas originales y noticias del mundo de los sorteos y la toma de decisiones divertida.",
        readMore: "Leer más",
        by: "Por",
        previous: "Anterior",
        next: "Siguiente",
        allPosts: "Todos los artículos",
        searchPlaceholder: "Buscar un artículo...",
        similarPosts: "Artículos Similares",
        noArticlesTitle: "No hay artículos por el momento...",
        noArticlesDescription: "Pronto habrá nuevos artículos. Mientras tanto, ¿por qué no tomas una decisión rápida?",
        noArticlesButton: "Probar la ruleta Sí/No"
    },
    de: {
        metaTitle: "Glücksrad Blog | Tipps & Ideen für Ihr Zufallsrad & Drehrad",
        metaDescription: "Entdecken Sie Tipps für Gewinnspiele, Spielideen und Neuigkeiten zu unserem Online-Drehrad. Der ultimative Blog über das anpassbare Glücksrad.",
        title: "Zufallsrad Blog",
        description: "Tipps, originelle Ideen und Neuigkeiten aus der Welt der zufälligen Ziehungen und spielerischen Entscheidungen.",
        readMore: "Weiterlesen",
        by: "Von",
        previous: "Zurück",
        next: "Weiter",
        allPosts: "Alle Beiträge",
        searchPlaceholder: "Nach einem Artikel suchen...",
        similarPosts: "Ähnliche Artikel",
        noArticlesTitle: "Noch keine Artikel...",
        noArticlesDescription: "Neue Artikel kommen bald. Warum treffen Sie in der Zwischenzeit nicht eine schnelle Entscheidung?",
        noArticlesButton: "Das Ja/Nein-Rad ausprobieren"
    },
    pt: {
        metaTitle: "Blog Roda da Sorte | Dicas para sua Roleta Giratória",
        metaDescription: "Descubra dicas de sorteio, ideias de jogos e as últimas novidades da nossa roleta giratória online. O blog para tudo sobre a roda da sorte personalizável.",
        title: "Blog da Roda da Sorte",
        description: "Dicas, ideias originais e notícias do mundo dos sorteios e da tomada de decisão divertida.",
        readMore: "Leia mais",
        by: "Por",
        previous: "Anterior",
        next: "Próximo",
        allPosts: "Todos os artigos",
        searchPlaceholder: "Procurar um artigo...",
        similarPosts: "Artigos Semelhantes",
        noArticlesTitle: "Ainda não há artigos...",
        noArticlesDescription: "Novos artigos chegarão em breve. Entretanto, por que não tomar uma decisão rápida?",
        noArticlesButton: "Experimente a roda Sim/Não"
    }
}
