
export const translations = {
    fr: {
        metaTitle: "Roue de la Chance des Couleurs | Roue aléatoire pour Artistes & Designers",
        metaDescription: "Besoin d'inspiration ? Tirez une couleur au hasard avec notre roue des couleurs. Une roulette en ligne parfaite pour les artistes, les designers et les jeux créatifs.",
        ogImage: 'https://avisclients.digitalextension.fr/wp-content/uploads/2025/07/roue-des-couleurs.webp',
        pageTitle: "Roue de la Chance des Couleurs",
        description: "Lancez cette roue aléatoire pour un tirage de couleur. Un outil parfait pour l'inspiration créative.",
        storageWarning: "Sauvegarde automatique : Vos options et votre historique sont enregistrés dans votre navigateur.",
        spinButton: "LANCER",
        customizeTooltip: "Personnaliser les couleurs",
        shuffleTooltip: "Mélanger les couleurs",
        resultsTooltip: "Historique des couleurs",
        hideTooltip: "Masquer le panneau",
        showTooltip: "Afficher le panneau",
        sectionTitle: "La <strong>Roue en Ligne des Couleurs</strong> : Libérez votre Créativité",
        sectionDescription: "Un outil vibrant pour choisir des couleurs de manière ludique. Que vous soyez artiste, designer, ou à la recherche d'inspiration, cette roulette aléatoire est pour vous.",
        whatIsTitle: "Qu'est-ce que la Roue des Couleurs en Ligne ?",
        whatIsText: "C'est une <strong>roulette en ligne</strong> où chaque segment est une couleur que vous définissez. Lancez la roue du hasard et elle s'arrêtera sur une couleur au hasard. C'est un moyen simple et amusant de générer une palette, de lancer un défi artistique ou de choisir une couleur pour un projet.",
        whyUseTitle: "Pourquoi utiliser cette roue en ligne ?",
        whyUseText: "Pour briser le blocage de la page blanche ! Notre <strong>roue de la chance en ligne</strong> est perfecte pour trouver l'inspiration, créer des palettes de couleurs aléatoires ou organiser des jeux basés sur les couleurs. C'est un outil visuellement attrayant et très polyvalent.",
        howToUseTitle: "Comment utiliser cette roulette en ligne ?",
        howToUseSteps: [
            "<strong>Admirez la palette :</strong> La roue est prête avec une sélection de 12 couleurs de base.",
            "<strong>Personnalisez :</strong> Ajoutez vos propres couleurs (avec leur nom et leur code hexadécimal) ou supprimez celles qui ne vous plaisent pas via le panneau 'Personnaliser'.",
            "<strong>Lancez la roue en ligne :</strong> Cliquez sur \"LANCER\" et laissez le hasard peindre votre prochaine idée !"
        ],
        ideasTitle: "Idées d'utilisation de la roue des couleurs",
        ideasItems: [
            "<strong>Défis de dessin :</strong> Utilisez uniquement la couleur tirée pour créer une illustration.",
            "<strong>Design d'intérieur :</strong> Choisissez une couleur d'accent pour une pièce avec notre <strong>roulette en ligne</strong>.",
            "<strong>Mode :</strong> Trouvez la couleur de votre prochaine tenue ou accessoire.",
            "<strong>Jeux de société :</strong> Remplacez un dé de couleur par un lancer de cette <strong>roue en ligne</strong>."
        ],
        faqTitle: "Questions Fréquemment Posées",
        faqItems: [
            { "q": "La roue est-elle vraiment aléatoire ?", "a": "<strong>Absolument.</strong> Notre roue du hasard utilise un algorithme de Génération de Nombres Aléatoires de pointe pour garantir que chaque résultat est <strong>totalement imprévisible et indépendant</strong> des tours précédents. Chaque segment a une probabilité égale d'être sélectionné, assurant un tirage 100% juste et équitable. Pour en savoir plus sur le fonctionnement, vous pouvez consulter notre <a href='/fr/guide-roue-de-la-chance' class='text-primary hover:underline'>guide d'utilisation</a>." },
            { "q": "Puis-je utiliser la roue sur mon téléphone mobile ?", "a": "<strong>Oui, bien sûr !</strong> Notre site est entièrement \"responsive\", ce qui signifie que notre roue en ligne est conçue pour fonctionner parfaitement sur tous les appareils : ordinateurs de bureau, tablettes et smartphones. L'expérience est optimisée pour que vous puissiez faire tourner la roue où que vous soyez, quand vous le voulez." },
            { "q": "Comment sont sauvegardées mes options ?", "a": "La configuration de votre roue de la chance, y compris les options, est <strong>automatiquement sauvegardée dans le stockage local de votre navigateur</strong> (`localStorage`). Cela signifie que lorsque vous revenez sur notre site, vous retrouvez votre roue telle que vous l'avez laissée. C'est 100% privé et sécurisé sur votre appareil." },
            { "q": "Comment partager ma roue personnalisée ?", "a": "C'est très facile ! Utilisez le bouton <strong>'Partager'</strong> situé dans l'en-tête de la page. Cela générera un lien URL unique contenant la configuration de votre roue. Vous pourrez copier ce lien et l'envoyer à vos amis. Ils utiliseront alors exactement la même roue aléatoire que vous, ce qui est parfait pour les jeux à distance !" },
            { "q": "Mes données sont-elles vraiment privées ?", "a": "<strong>La confidentialité est notre priorité absolue.</strong> Toutes les données de votre roue (options et historique) sont stockées <strong>uniquement sur votre appareil</strong>. Nous ne collectons, ne voyons, ni ne stockons aucune de ces informations sur nos serveurs. C'est une des raisons pour lesquelles notre outil est si rapide et sécurisé. Pour plus de détails, n'hésitez pas à consulter notre <a href='/fr/politique-de-confidentialite' class='text-primary hover:underline'>Politique de Confidentialité</a>." }
        ],
        ctaTitle: "Envie d'une autre roue en ligne ?",
        ctaText: "Créez votre propre roue avec n'importe quelles options, pas seulement des couleurs !",
        ctaLink: "➤ Créer une Roue en Ligne Personnalisée",
        defaultOptions: [
            { id: 'red', name: 'Rouge', color: '#e74c3c' },
            { id: 'orange', name: 'Orange', color: '#e67e22' },
            { id: 'yellow', name: 'Jaune', color: '#f1c40f' },
            { id: 'green', name: 'Vert', color: '#2ecc71' },
            { id: 'cyan', name: 'Cyan', color: '#1abc9c' },
            { id: 'blue', name: 'Bleu', color: '#3498db' },
            { id: 'purple', name: 'Violet', color: '#9b59b6' },
            { id: 'magenta', name: 'Magenta', color: '#be2edd' },
            { id: 'pink', name: 'Rose', color: '#ff79c6' },
            { id: 'brown', name: 'Marron', color: '#a0522d' },
            { id: 'white', name: 'Blanc', color: '#ecf0f1' },
            { id: 'black', name: 'Noir', color: '#2c3e50' },
        ]
    },
    en: {
        metaTitle: "Color Spin Wheel | Random Color Picker & Generator",
        metaDescription: "Need inspiration? Spin our color wheel to pick a random color. A perfect online spinner and random picker for artists, designers, and creative games.",
        ogImage: 'https://avisclients.digitalextension.fr/wp-content/uploads/2025/07/roue-des-couleurs.webp',
        pageTitle: "Color Spin Wheel",
        description: "Use our color spin wheel generator for inspiration. A perfect random picker to generate a random shade.",
        storageWarning: "Automatic saving: Your options and history are saved in your browser.",
        spinButton: "SPIN",
        customizeTooltip: "Customize colors",
        shuffleTooltip: "Shuffle colors",
        resultsTooltip: "Color history",
        hideTooltip: "Hide panel",
        showTooltip: "Show panel",
        sectionTitle: "The <strong>Color Spin Wheel</strong>: Unleash Your Creativity",
        sectionDescription: "A vibrant tool to playfully choose colors. Whether you're an artist, designer, or looking for inspiration, this random picker is for you.",
        whatIsTitle: "What is the Color Spin Wheel?",
        whatIsText: "This is an <strong>online spinner</strong> where each segment is a color you define. Spin the wheel, and it will land on a random color. It's a simple and fun way to generate a palette, start an art challenge, or pick a color for a project.",
        whyUseTitle: "Why use this spin wheel?",
        whyUseText: "To break through creative blocks! Our <strong>custom wheel online</strong> is perfect for finding inspiration, creating random color palettes, or organizing color-based games. It's a visually appealing and highly versatile tool.",
        howToUseTitle: "How to use this random picker?",
        howToUseSteps: [
            "<strong>Admire the palette:</strong> The wheel comes ready with a selection of 12 basic colors.",
            "<strong>Customize:</strong> Add your own colors (with their name and hex codes) or remove the ones you don't like via the 'Customize' panel.",
            "<strong>Spin the wheel:</strong> Click \"SPIN\" and let chance paint your next idea!"
        ],
        ideasTitle: "Usage Ideas for the Color Wheel",
        ideasItems: [
            "<strong>Drawing challenges:</strong> Use only the drawn color to create an illustration.",
            "<strong>Interior design:</strong> Choose an accent color for a room with our <strong>random picker</strong>.",
            "<strong>Fashion:</strong> Find the color for your next outfit or accessory with the spinner.",
            "<strong>Board games:</strong> Replace a color die with a spin of this <strong>online wheel</strong>."
        ],
        faqTitle: "Frequently Asked Questions",
        faqItems: [
            { "q": "Is the wheel truly random?", "a": "<strong>Absolutely.</strong> Our spin wheel uses a state-of-the-art Random Number Generator (RNG) algorithm to ensure that every result is <strong>completely unpredictable and independent</strong> of previous spins. Each segment has an equal probability of being selected, guaranteeing a 100% fair draw. You can learn more in our <a href='/en/guide-spin-wheel-of-chance' class='text-primary hover:underline'>user guide</a>." },
            { "q": "Can I use the spin wheel on my mobile phone?", "a": "<strong>Yes, of course!</strong> Our website is fully responsive, which means it is designed to work perfectly on all devices: desktops, tablets, and smartphones. The experience is optimized so you can spin the wheel wherever and whenever you want." },
            { "q": "How is my custom wheel configuration saved?", "a": "Your wheel configuration, including your custom options, is <strong>automatically saved in your browser's local storage</strong> (`localStorage`). This means when you return to our site, you'll find your wheel just as you left it. It's 100% private and secure on your device." },
            { "q": "How can I share my custom wheel?", "a": "It's very easy! Use the <strong>'Share' button</strong> in the page header. This will generate a unique URL containing your wheel's setup. You can copy this link and send it to your friends. They will then be able to use the exact same random wheel as you, which is perfect for remote games!" },
            { "q": "Is my data really private?", "a": "<strong>Privacy is our absolute priority.</strong> All your wheel data (options and history) is stored <strong>only on your device</strong>. We do not collect, see, or store any of this information on our servers. This is one of the reasons our tool is so fast and secure. For more details, feel free to consult our <a href='/en/privacy-policy' class='text-primary hover:underline'>Privacy Policy</a>." }
        ],
        ctaTitle: "Want another online wheel?",
        ctaText: "Create your own wheel with any options, not just colors!",
        ctaLink: "➤ Create a Custom Online Wheel",
        defaultOptions: [
            { id: 'red', name: 'Red', color: '#e74c3c' },
            { id: 'orange', name: 'Orange', color: '#e67e22' },
            { id: 'yellow', name: 'Yellow', color: '#f1c40f' },
            { id: 'green', name: 'Green', color: '#2ecc71' },
            { id: 'cyan', name: 'Cyan', color: '#1abc9c' },
            { id: 'blue', name: 'Blue', color: '#3498db' },
            { id: 'purple', name: 'Purple', color: '#9b59b6' },
            { id: 'magenta', name: 'Magenta', color: '#be2edd' },
            { id: 'pink', name: 'Pink', color: '#ff79c6' },
            { id: 'brown', name: 'Brown', color: '#a0522d' },
            { id: 'white', name: 'White', color: '#ecf0f1' },
            { id: 'black', name: 'Black', color: '#2c3e50' },
        ]
    },
    es: {
        metaTitle: "Ruleta de Colores en Línea | Generador de Colores Aleatorio",
        metaDescription: "¿Necesitas inspiración? Gira nuestra ruleta de colores para elegir un color al azar. Un generador de colores online perfecto para artistas y diseñadores.",
        ogImage: 'https://avisclients.digitalextension.fr/wp-content/uploads/2025/07/roue-des-couleurs.webp',
        pageTitle: "Ruleta de Colores en Línea",
        description: "Gira la ruleta de colores para inspirarte. Un generador de colores aleatorio y personalizable.",
        storageWarning: "Guardado automático: Tus opciones e historial se guardan en tu navegador.",
        spinButton: "GIRAR",
        customizeTooltip: "Personalizar colores",
        shuffleTooltip: "Mezclar colores",
        resultsTooltip: "Historial de colores",
        hideTooltip: "Ocultar panel",
        showTooltip: "Mostrar panel",
        sectionTitle: "La <strong>Ruleta de Colores en Línea</strong>: Libera tu Creatividad",
        sectionDescription: "Una herramienta vibrante para elegir colores de forma lúdica. Si eres artista, diseñador o buscas inspiración, esta ruleta en línea es para ti.",
        whatIsTitle: "¿Qué es la Ruleta de Colores en Línea?",
        whatIsText: "Es una <strong>ruleta en línea</strong> donde cada segmento es un color que tú defines. Gira la ruleta y se detendrá en un color al azar. Es una forma sencilla y divertida de generar una paleta, iniciar un reto artístico o elegir un color para un proyecto.",
        whyUseTitle: "Por qué usar esta ruleta en línea?",
        whyUseText: "¡Para superar el bloqueo creativo! Nuestra <strong>ruleta en línea</strong> es perfecta para encontrar inspiración, crear paletas de colores aleatorias u organizar juegos basados en colores. Es una herramienta visualmente atractiva y muy versátil.",
        howToUseTitle: "¿Cómo usar esta ruleta virtual?",
        howToUseSteps: [
            "<strong>Admira la paleta:</strong> La ruleta viene lista con una selección de 12 colores básicos.",
            "<strong>Personaliza:</strong> Añade tus propios colores (con su nombre y código hexadecimal) o elimina los que no te gusten a través del panel 'Personalizar'.",
            "<strong>Gira la ruleta en línea:</strong> ¡Haz clic en \"GIRAR\" y deja que el azar pinte tu próxima idea!"
        ],
        ideasTitle: "Ideas de uso para la ruleta de colores",
        ideasItems: [
            "<strong>Retos de dibujo:</strong> Usa solo el color sorteado para crear una ilustración.",
            "<strong>Diseño de interiores:</strong> Elige un color de acento para una habitación con nuestra <strong>ruleta virtual</strong>.",
            "<strong>Moda:</strong> Encuentra el color para tu próximo atuendo o accesorio.",
            "<strong>Juegos de mesa:</strong> Sustituye un dado de color por un giro de esta <strong>ruleta en línea</strong>."
        ],
        faqTitle: "Preguntas Frecuentes",
        faqItems: [
            { "q": "¿La ruleta es realmente aleatoria?", "a": "<strong>Absolutamente.</strong> Nuestra ruleta utiliza un algoritmo de Generador de Números Aleatorios (RNG) para garantizar que cada resultado sea <strong>impredecible e independiente</strong> de los giros anteriores. Cada segmento tiene la misma probabilidad de ser seleccionado, asegurando un sorteo 100% justo. Puedes aprender más en nuestra <a href='/es/guia-ruleta-de-la-suerte' class='text-primary hover:underline'>guía de uso</a>." },
            { "q": "¿Puedo usar la ruleta en mi teléfono móvil?", "a": "<strong>¡Sí, claro!</strong> Nuestro sitio está completamente diseñado para funcionar perfectamente en todos los dispositivos: ordenadores, tabletas y teléfonos inteligentes. La experiencia está optimizada para que puedas girar la ruleta estés donde estés." },
            { "q": "¿Cómo se guardan mis opciones?", "a": "La configuración de tu ruleta, incluyendo tus opciones personalizadas, se <strong>guarda automáticamente en el almacenamiento local de tu navegador</strong> (`localStorage`). Esto significa que cuando regreses, encontrarás tu ruleta tal como la dejaste. ¡Es 100% privado y seguro en tu dispositivo!" },
            { "q": "¿Cómo comparto mi ruleta personalizada?", "a": "¡Es muy fácil! Utiliza el botón <strong>'Compartir'</strong> situado en el encabezado de la página. Esto generará un enlace URL único que contiene la configuración de tu ruleta. Puedes copiar este enlace y enviarlo a tus amigos, lo que es perfecto para juegos a distancia." },
            { "q": "¿Mis datos son realmente privados?", "a": "<strong>La privacidad es nuestra máxima prioridad.</strong> Todos los datos de tu ruleta (opciones e historial) se almacenan <strong>únicamente en tu dispositivo</strong>. No recopilamos, vemos ni almacenamos ninguna de esta información en nuestros servidores. Para más detalles, no dudes en consultar nuestra <a href='/es/politica-de-privacidad' class='text-primary hover:underline'>Política de Privacidad</a>." }
        ],
        ctaTitle: "¿Quieres otra ruleta en línea?",
        ctaText: "¡Crea tu propia ruleta con cualquier opción, no solo colores!",
        ctaLink: "➤ Crear una Ruleta en Línea Personalizada",
        defaultOptions: [
            { id: 'red', name: 'Rojo', color: '#e74c3c' },
            { id: 'orange', name: 'Naranja', color: '#e67e22' },
            { id: 'yellow', name: 'Amarillo', color: '#f1c40f' },
            { id: 'green', name: 'Verde', color: '#2ecc71' },
            { id: 'cyan', name: 'Cian', color: '#1abc9c' },
            { id: 'blue', name: 'Azul', color: '#3498db' },
            { id: 'purple', name: 'Morado', color: '#9b59b6' },
            { id: 'magenta', name: 'Magenta', color: '#be2edd' },
            { id: 'pink', name: 'Rosa', color: '#ff79c6' },
            { id: 'brown', name: 'Marrón', color: '#a0522d' },
            { id: 'white', name: 'Blanco', color: '#ecf0f1' },
            { id: 'black', name: 'Negro', color: '#2c3e50' },
        ]
    },
    de: {
        metaTitle: "Farben-Glücksrad | Zufälliger Farbgenerator",
        metaDescription: "Brauchen Sie Inspiration? Drehen Sie unser Farben-Glücksrad, um eine zufällige Farbe auszuwählen. Ein perfektes Online-Drehrad für Künstler und Designer.",
        ogImage: 'https://avisclients.digitalextension.fr/wp-content/uploads/2025/07/roue-des-couleurs.webp',
        pageTitle: "Farben-Glücksrad",
        description: "Drehen Sie das Glücksrad zur Inspiration. Ein Zufallsgenerator für Farben.",
        storageWarning: "Automatische Speicherung: Ihre Optionen und Ihr Verlauf werden in Ihrem Browser gespeichert.",
        spinButton: "DREHEN",
        customizeTooltip: "Farben anpassen",
        shuffleTooltip: "Farben mischen",
        resultsTooltip: "Farbverlauf",
        hideTooltip: "Panel ausblenden",
        showTooltip: "Panel anzeigen",
        sectionTitle: "Das <strong>Farben-Glücksrad</strong>: Entfesseln Sie Ihre Kreativität",
        sectionDescription: "Ein lebendiges Werkzeug, um spielerisch Farben auszuwählen. Ob Sie Künstler, Designer sind oder Inspiration suchen, dieses Glücksrad ist für Sie.",
        whatIsTitle: "Was ist das Farben-Glücksrad?",
        whatIsText: "Dies ist ein <strong>Online-Glücksrad</strong>, bei dem jedes Segment eine von Ihnen definierte Farbe ist. Drehen Sie das Glücksrad, und es landet auf einer zufälligen Farbe. Es ist eine einfache und unterhaltsame Möglichkeit, eine Palette zu generieren, eine künstlerische Herausforderung zu starten oder eine Farbe für ein Projekt auszuwählen.",
        whyUseTitle: "Warum dieses Online-Glücksrad verwenden?",
        whyUseText: "Um kreative Blockaden zu durchbrechen! Unser <strong>Glücksrad</strong> ist perfekt, um Inspiration zu finden, zufällige Farbpaletten zu erstellen oder farbenbasierte Spiele zu organisieren. Es ist ein visuell ansprechendes und sehr vielseitiges Werkzeug.",
        howToUseTitle: "Wie benutzt man dieses Online-Glücksrad?",
        howToUseSteps: [
            "<strong>Bewundern Sie die Palette:</strong> Das Rad ist mit einer Auswahl von 12 Grundfarben einsatzbereit.",
            "<strong>Anpassen:</strong> Fügen Sie Ihre eigenen Farben (mit ihrem Namen und Hex-Codes) hinzu oder entfernen Sie diejenigen, die Ihnen nicht gefallen, über das 'Anpassen'-Panel.",
            "<strong>Drehen Sie das Online-Rad:</strong> Klicken Sie auf \"DREHEN\" und lassen Sie den Zufall Ihre nächste Idee malen!"
        ],
        ideasTitle: "Anwendungsideen für das Farbrad",
        ideasItems: [
            "<strong>Zeichenherausforderungen:</strong> Verwenden Sie nur die gezogene Farbe, um eine Illustration zu erstellen.",
            "<strong>Innenarchitektur:</strong> Wählen Sie eine Akzentfarbe für einen Raum mit unserem <strong>Online-Glücksrad</strong>.",
            "<strong>Mode:</strong> Finden Sie die Farbe für Ihr nächstes Outfit oder Accessoire.",
            "<strong>Brettspiele:</strong> Ersetzen Sie einen Farbwürfel durch eine Drehung dieses <strong>Glücksrads</strong>."
        ],
        faqTitle: "Häufig gestellte Fragen",
        faqItems: [
            { "q": "Ist das Glücksrad wirklich zufällig?", "a": "<strong>Absolut.</strong> Unser Glücksrad verwendet einen Zufallszahlengenerator (RNG), um sicherzustellen, dass jedes Ergebnis <strong>unvorhersehbar und unabhängig</strong> von früheren Drehungen ist. Jedes Segment hat die gleiche Wahrscheinlichkeit, was eine 100% faire Ziehung garantiert. Erfahren Sie mehr in unserer <a href='/de/anleitung-zufallsrad' class='text-primary hover:underline'>Anleitung</a>." },
            { "q": "Kann ich das Glücksrad auf meinem Handy benutzen?", "a": "<strong>Ja, natürlich!</strong> Unsere Seite ist vollständig so konzipiert, dass sie auf allen Geräten perfekt funktioniert: Desktops, Tablets und Smartphones. Das Erlebnis ist optimiert, damit Sie das Glücksrad drehen können, wo immer Sie sind." },
            { "q": "Wie werden meine Optionen gespeichert?", "a": "Ihre Glücksrad-Konfiguration wird <strong>automatisch in Ihrem Browser gespeichert</strong> (`localStorage`). Das bedeutet, wenn Sie zurückkehren, finden Sie Ihr Glücksrad so vor, wie Sie es verlassen haben. Es ist 100% privat und sicher auf Ihrem Gerät." },
            { "q": "Wie teile ich mein benutzerdefiniertes Glücksrad?", "a": "Ganz einfach! Verwenden Sie die Schaltfläche <strong>'Teilen'</strong> im Kopfbereich der Seite. Dadurch wird ein eindeutiger URL-Link generiert, der Ihre Glücksrad-Konfiguration enthält, perfekt für Fernspiele!" },
            { "q": "Sind meine Daten wirklich privat?", "a": "<strong>Datenschutz hat für uns oberste Priorität.</strong> Alle Ihre Glücksrad-Daten (Optionen und Verlauf) werden <strong>nur auf Ihrem Gerät</strong> gespeichert. Wir sammeln, sehen oder speichern keine dieser Informationen auf unseren Servern. Für weitere Details können Sie gerne unsere <a href='/de/datenschutzrichtlinie' class='text-primary hover:underline'>Datenschutzrichtlinie</a> konsultieren." }
        ],
        ctaTitle: "Möchten Sie ein anderes Glücksrad?",
        ctaText: "Erstellen Sie Ihr eigenes Glücksrad mit beliebigen Optionen, nicht nur Farben!",
        ctaLink: "➤ Erstellen Sie ein benutzerdefiniertes Glücksrad",
        defaultOptions: [
            { id: 'red', name: 'Rot', color: '#e74c3c' },
            { id: 'orange', name: 'Orange', color: '#e67e22' },
            { id: 'yellow', name: 'Gelb', color: '#f1c40f' },
            { id: 'green', name: 'Grün', color: '#2ecc71' },
            { id: 'cyan', name: 'Cyan', color: '#1abc9c' },
            { id: 'blue', name: 'Blau', color: '#3498db' },
            { id: 'purple', name: 'Lila', color: '#9b59b6' },
            { id: 'magenta', name: 'Magenta', color: '#be2edd' },
            { id: 'pink', name: 'Rosa', color: '#ff79c6' },
            { id: 'brown', name: 'Braun', color: '#a0522d' },
            { id: 'white', name: 'Weiß', color: '#ecf0f1' },
            { id: 'black', name: 'Schwarz', color: '#2c3e50' },
        ]
    },
    pt: {
        metaTitle: "Roda das Cores Online | Gerador de Cores Aleatório",
        metaDescription: "Precisa de inspiração? Gire a nossa roda das cores para escolher uma cor aleatória. Uma roleta giratória online perfeita para artistas, designers e jogos criativos.",
        ogImage: 'https://avisclients.digitalextension.fr/wp-content/uploads/2025/07/roue-des-couleurs.webp',
        pageTitle: "Roda das Cores Online",
        description: "Gire a roleta de cores para se inspirar. Um gerador de cores aleatório e personalizável.",
        storageWarning: "Gravação automática: As suas opções e histórico são guardados no seu navegador.",
        spinButton: "GIRAR",
        customizeTooltip: "Personalizar cores",
        shuffleTooltip: "Baralhar cores",
        resultsTooltip: "Histórico de cores",
        hideTooltip: "Ocultar painel",
        showTooltip: "Mostrar painel",
        sectionTitle: "A <strong>Roda das Cores Online</strong>: Liberte a Sua Criatividade",
        sectionDescription: "Uma ferramenta vibrante para escolher cores de forma lúdica. Quer seja artista, designer ou esteja à procura de inspiração, esta roleta online é para si.",
        whatIsTitle: "O que é a Roda das Cores Online?",
        whatIsText: "É uma <strong>roleta online</strong> donde cada segmento é uma cor que define. Gire a roda e ela irá parar numa cor ao acaso. É uma forma simples e divertida de gerar uma paleta, lançar um desafio artístico ou escolher uma cor para um projeto.",
        whyUseTitle: "Por que usar esta roleta online?",
        whyUseText: "Para quebrar o bloqueio criativo! A nossa <strong>roleta online</strong> é perfeita para encontrar inspiração, criar paletas de cores aleatórias ou organizar jogos baseados em cores. É uma ferramenta visualmente atraente e muito versátil.",
        howToUseTitle: "Como usar esta roleta online?",
        howToUseSteps: [
            "<strong>Admire a paleta:</strong> A roda vem pronta com uma seleção de 12 cores básicas.",
            "<strong>Personalize:</strong> Adicione as suas próprias cores (com o seu nome e códigos hexadecimais) ou remova as que não gosta através do painel 'Personalizar'.",
            "<strong>Gire a roleta online:</strong> Clique em \"GIRAR\" e deixe o acaso pintar a sua próxima ideia!"
        ],
        ideasTitle: "Ideias de utilização para a roda das cores",
        ideasItems: [
            "<strong>Desafios de desenho:</strong> Use apenas a cor sorteada para criar uma ilustração.",
            "<strong>Design de interiores:</strong> Escolha uma cor de destaque para um quarto com a nossa <strong>roleta online</strong>.",
            "<strong>Moda:</strong> Encontre a cor para o seu próximo look ou acessório.",
            "<strong>Jogos de tabuleiro:</strong> Substitua um dado de cor por um giro desta <strong>roleta online</strong>."
        ],
        faqTitle: "Perguntas Frequentes",
        faqItems: [
            { "q": "A roda é realmente aleatória?", "a": "<strong>Absolutamente.</strong> A nossa roda utiliza um gerador de números aleatórios (RNG) para garantir que cada resultado é <strong>imprevisível e independente</strong> das rotações anteriores. Cada segmento tem a mesma probabilidade de ser selecionado, garantindo um sorteio 100% justo. Pode saber mais no nosso <a href='/pt/guia-roda-da-sorte' class='text-primary hover:underline'>guia de utilização</a>." },
            { "q": "Posso usar a roda no meu telemóvel?", "a": "<strong>Sim, claro!</strong> O nosso site é totalmente responsivo, o que significa que foi concebido para funcionar perfeitamente em todos os dispositivos: computadores, tablets e smartphones. A experiência está otimizada para que possa girar a roda onde quer que esteja." },
            { "q": "Como são guardadas as minhas opções?", "a": "A configuração da sua roda, incluindo as suas opções personalizadas, é <strong>automaticamente guardada no armazenamento local do seu navegador</strong> (`localStorage`). Isto significa que quando regressar, encontrará a sua roda tal como a deixou. É 100% privado e seguro no seu dispositivo." },
            { "q": "Como posso partilhar a minha roda personalizada?", "a": "É muito fácil! Utilize o botão <strong>'Partilhar'</strong> localizado no cabeçalho da página. Isto irá gerar um link URL único contendo a configuração da sua roda, perfeito para jogos à distância!" },
            { "q": "Os meus dados são realmente privados?", "a": "<strong>A privacidade é a nossa prioridade absoluta.</strong> Todos os dados da sua roda (opções e histórico) são armazenados <strong>apenas no seu dispositivo</strong>. Não recolhemos, vemos ou armazenamos nenhuma destas informações nos nossos servidores. Para mais detalhes, não hesite em consultar a nossa <a href='/pt/politica-de-privacidade' class='text-primary hover:underline'>Política de Privacidade</a>." }
        ],
        ctaTitle: "Quer outra roleta online?",
        ctaText: "Crie a sua própria roda com quaisquer opções, não apenas cores!",
        ctaLink: "➤ Criar uma Roleta Online Personalizada",
        defaultOptions: [
            { id: 'red', name: 'Vermelho', color: '#e74c3c' },
            { id: 'orange', name: 'Laranja', color: '#e67e22' },
            { id: 'yellow', name: 'Amarelo', color: '#f1c40f' },
            { id: 'green', name: 'Verde', color: '#2ecc71' },
            { id: 'cyan', name: 'Ciano', color: '#1abc9c' },
            { id: 'blue', name: 'Azul', color: '#3498db' },
            { id: 'purple', name: 'Roxo', color: '#9b59b6' },
            { id: 'magenta', name: 'Magenta', color: '#be2edd' },
            { id: 'pink', name: 'Rosa', color: '#ff79c6' },
            { id: 'brown', name: 'Castanho', color: '#a0522d' },
            { id: 'white', name: 'Branco', color: '#ecf0f1' },
            { id: 'black', name: 'Preto', color: '#2c3e50' },
        ]
    }
}
