export const translations = {
    fr: {
        metaTitle: "Contact | Roue de la Chance, Partenariats & Support",
        metaDescription: "Contactez l'équipe de notre roue de la chance pour toute question, suggestion ou proposition de partenariat. Nous sommes à votre écoute.",
        title: "Contactez-nous",
        description: "Une question, une suggestion ou une proposition de partenariat ? Nous sommes là pour vous répondre.",
        formTitle: "Envoyer un message",
        formDescription: "Remplissez le formulaire ci-dessous et nous vous répondrons dans les plus brefs délais.",
        nameLabel: "Votre nom",
        namePlaceholder: "Jean Dupont",
        emailLabel: "Votre e-mail",
        emailPlaceholder: "jean.dupont@email.com",
        subjectLabel: "Sujet de votre message",
        subjectPlaceholder: "Choisissez un sujet",
        subjects: [
            "Question générale",
            "Suggestion d'amélioration",
            "Signaler un bug",
            "Proposition de partenariat",
            "Autre"
        ],
        messageLabel: "Votre message",
        messagePlaceholder: "Bonjour, je vous contacte concernant...",
        submitButton: "Envoyer",
        submittingButton: "Envoi en cours...",
        partnershipTitle: "Partenariats & Collaborations",
        partnershipDescription: "Vous souhaitez collaborer avec nous ?",
        partnershipText: "Nous sommes toujours ouverts aux idées créatives. Contactez-nous directement par e-mail pour en discuter.",
        partnershipEmail: "contact@larouedelachance.com",
        readyTitle: "Prêt à faire un tour ?",
        readyText: "Retournez sur la roue principale et laissez le hasard décider !",
        readyLink: "Lancer la roue",
        toastSuccessTitle: "Message envoyé !",
        toastSuccessDescription: "Nous avons bien reçu votre message et nous vous répondrons bientôt.",
        toastErrorTitle: "Erreur d'envoi",
        toastErrorDescription: "Une erreur est survenue. Veuillez réessayer plus tard.",
        toastBlockedEmail: "Cet e-mail est bloqué. Veuillez utiliser une autre adresse."
    },
    en: {
        metaTitle: "Contact | Wheel of Chance, Partnerships & Support",
        metaDescription: "Contact the Wheel of Chance team for any questions, suggestions, or partnership proposals. We are here to listen.",
        title: "Contact Us",
        description: "Have a question, a suggestion, or a partnership proposal? We are here to answer you.",
        formTitle: "Send a message",
        formDescription: "Fill out the form below and we will get back to you as soon as possible.",
        nameLabel: "Your name",
        namePlaceholder: "John Doe",
        emailLabel: "Your email",
        emailPlaceholder: "john.doe@email.com",
        subjectLabel: "Subject of your message",
        subjectPlaceholder: "Choose a subject",
        subjects: [
            "General question",
            "Improvement suggestion",
            "Report a bug",
            "Partnership proposal",
            "Other"
        ],
        messageLabel: "Your message",
        messagePlaceholder: "Hello, I am contacting you regarding...",
        submitButton: "Send",
        submittingButton: "Sending...",
        partnershipTitle: "Partnerships & Collaborations",
        partnershipDescription: "Interested in collaborating with us?",
        partnershipText: "We are always open to creative ideas. Contact us directly by email to discuss.",
        partnershipEmail: "contact@larouedelachance.com",
        readyTitle: "Ready for a spin?",
        readyText: "Go back to the main wheel and let chance decide!",
        readyLink: "Spin the wheel",
        toastSuccessTitle: "Message sent!",
        toastSuccessDescription: "We have received your message and will get back to you soon.",
        toastErrorTitle: "Sending Error",
        toastErrorDescription: "An error occurred. Please try again later.",
        toastBlockedEmail: "This email is blocked. Please use another address."
    },
    es: {
        metaTitle: "Contacto | Ruleta de la Suerte, Colaboraciones y Soporte",
        metaDescription: "Contacta con el equipo de la Ruleta de la Suerte para cualquier pregunta, sugerencia o propuesta de colaboración. Estamos aquí para escucharte.",
        title: "Contáctanos",
        description: "¿Tienes una pregunta, una sugerencia o una propuesta de colaboración? Estamos aquí para responderte.",
        formTitle: "Enviar un mensaje",
        formDescription: "Rellena el siguiente formulario y te responderemos lo antes posible.",
        nameLabel: "Tu nombre",
        namePlaceholder: "Juan Pérez",
        emailLabel: "Tu correo electrónico",
        emailPlaceholder: "juan.perez@email.com",
        subjectLabel: "Asunto de tu mensaje",
        subjectPlaceholder: "Elige un asunto",
        subjects: [
            "Pregunta general",
            "Sugerencia de mejora",
            "Informar de un error",
            "Propuesta de colaboración",
            "Otro"
        ],
        messageLabel: "Tu mensaje",
        messagePlaceholder: "Hola, te contacto en relación con...",
        submitButton: "Enviar",
        submittingButton: "Enviando...",
        partnershipTitle: "Colaboraciones y Asociaciones",
        partnershipDescription: "¿Interesado en colaborar con nosotros?",
        partnershipText: "Siempre estamos abiertos a ideas creativas. Contáctanos directamente por correo electrónico para discutirlo.",
        partnershipEmail: "contact@larouedelachance.com",
        readyTitle: "¿Listo para girar?",
        readyText: "¡Vuelve a la ruleta principal y deja que el azar decida!",
        readyLink: "Girar la ruleta",
        toastSuccessTitle: "¡Mensaje enviado!",
        toastSuccessDescription: "Hemos recibido tu mensaje y te responderemos pronto.",
        toastErrorTitle: "Error de envío",
        toastErrorDescription: "Ha ocurrido un error. Por favor, inténtalo de nuevo más tarde.",
        toastBlockedEmail: "Este correo electrónico está bloqueado. Por favor, utiliza otra dirección."
    },
    de: {
        metaTitle: "Kontakt | Zufallsrad, Partnerschaften & Support",
        metaDescription: "Kontaktieren Sie das Zufallsrad-Team bei Fragen, Anregungen oder Partnerschaftsvorschlägen. Wir sind hier, um zuzuhören.",
        title: "Kontaktieren Sie uns",
        description: "Haben Sie eine Frage, einen Vorschlag oder einen Partnerschaftsvorschlag? Wir sind hier, um Ihnen zu antworten.",
        formTitle: "Nachricht senden",
        formDescription: "Füllen Sie das untenstehende Formular aus und wir werden uns so schnell wie möglich bei Ihnen melden.",
        nameLabel: "Ihr Name",
        namePlaceholder: "Max Mustermann",
        emailLabel: "Ihre E-Mail",
        emailPlaceholder: "max.mustermann@email.com",
        subjectLabel: "Betreff Ihrer Nachricht",
        subjectPlaceholder: "Wählen Sie einen Betreff",
        subjects: [
            "Allgemeine Frage",
            "Verbesserungsvorschlag",
            "Fehler melden",
            "Partnerschaftsvorschlag",
            "Sonstiges"
        ],
        messageLabel: "Ihre Nachricht",
        messagePlaceholder: "Hallo, ich kontaktiere Sie bezüglich...",
        submitButton: "Senden",
        submittingButton: "Wird gesendet...",
        partnershipTitle: "Partnerschaften & Kooperationen",
        partnershipDescription: "Interessiert an einer Zusammenarbeit mit uns?",
        partnershipText: "Wir sind immer offen für kreative Ideen. Kontaktieren Sie uns direkt per E-Mail, um dies zu besprechen.",
        partnershipEmail: "contact@larouedelachance.com",
        readyTitle: "Bereit für eine Drehung?",
        readyText: "Gehen Sie zurück zum Hauptrad und lassen Sie den Zufall entscheiden!",
        readyLink: "Rad drehen",
        toastSuccessTitle: "Nachricht gesendet!",
        toastSuccessDescription: "Wir haben Ihre Nachricht erhalten und werden uns bald bei Ihnen melden.",
        toastErrorTitle: "Sende-Fehler",
        toastErrorDescription: "Ein Fehler ist aufgetreten. Bitte versuchen Sie es später erneut.",
        toastBlockedEmail: "Diese E-Mail ist blockiert. Bitte verwenden Sie eine andere Adresse."
    },
    pt: {
        metaTitle: "Contato | Roda da Sorte, Parcerias & Suporte",
        metaDescription: "Entre em contato com a equipe da Roda da Sorte para qualquer dúvida, sugestão ou proposta de parceria. Estamos aqui para ouvir.",
        title: "Contate-nos",
        description: "Tem uma pergunta, uma sugestão ou uma proposta de parceria? Estamos aqui para responder.",
        formTitle: "Enviar uma mensagem",
        formDescription: "Preencha o formulário abaixo e entraremos em contato o mais breve possível.",
        nameLabel: "Seu nome",
        namePlaceholder: "João da Silva",
        emailLabel: "Seu e-mail",
        emailPlaceholder: "joao.silva@email.com",
        subjectLabel: "Assunto da sua mensagem",
        subjectPlaceholder: "Escolha um assunto",
        subjects: [
            "Pergunta geral",
            "Sugestão de melhoria",
            "Relatar um erro",
            "Proposta de parceria",
            "Outro"
        ],
        messageLabel: "Sua mensagem",
        messagePlaceholder: "Olá, estou entrando em contato sobre...",
        submitButton: "Enviar",
        submittingButton: "Enviando...",
        partnershipTitle: "Parcerias & Colaborações",
        partnershipDescription: "Interessado em colaborar conosco?",
        partnershipText: "Estamos sempre abertos a ideias criativas. Entre em contato conosco directamente por e-mail para discutir.",
        partnershipEmail: "contact@larouedelachance.com",
        readyTitle: "Pronto para girar?",
        readyText: "Volte para a roda principal e deixe o acaso decidir!",
        readyLink: "Girar a roda",
        toastSuccessTitle: "Mensagem enviada!",
        toastSuccessDescription: "Recebemos sua mensagem e responderemos em breve.",
        toastErrorTitle: "Erro ao enviar",
        toastErrorDescription: "Ocorreu um erro. Por favor, tente novamente mais tarde.",
        toastBlockedEmail: "Este e-mail está bloqueado. Por favor, use outro endereço."
    }
}