
export const translations = {
    fr: {
        metaTitle: "Guide Roue de la Chance | Comment utiliser notre Roulette Aléatoire",
        metaDescription: "Apprenez à maîtriser notre roulette aléatoire. Le guide complet pour créer une roue de la chance personnalisable pour vos jeux, tirages au sort et décisions.",
        title: "Guide Complet de la Roulette Aléatoire",
        intro: "Bienvenue sur le guide d'utilisation de notre",
        introLink: "roue de la chance gratuite et personnalisable",
        intro2: ". Apprenez à maîtriser notre outil de roue aléatoire pour prendre des décisions, organiser des tirages au sort et bien plus encore.",
        whatIsTitle: "Qu'est-ce que la Roue de la Chance ?",
        whatIsText: "Notre",
        whatIsText2: "roulette en ligne",
        whatIsText3: "est un outil de tirage au sort aléatoire conçu pour être simple, amusant et entièrement adaptable. Que vous ayez besoin de choisir un nom au hasard, de pimenter un jeu avec des défis, de décider où manger ou de faire un simple \"Oui/Non\", notre roue du hasard est la solution idéale. Lancez",
        whatIsText4: "la roue de la chance",
        whatIsText5: "et laissez le destin choisir pour vous !",
        howToTitle: "Comment créer et utiliser votre roue de la chance personnalisable 🌀",
        howToText: "Créer votre propre",
        howToText2: "roue aléatoire personnalisable",
        howToText3: "est un jeu d'enfant. Suivez ces étapes simples :",
        howToSteps: [
            "<strong>Ajoutez vos entrées :</strong> Dans le panneau \"Personnaliser\", saisissez les options que vous souhaitez voir sur la roue en ligne. Il peut s'agir de noms, de chiffres, de tâches, d'emojis 🔥, ou même d'images !",
            "<strong>Personnalisez le design (Bientôt !) :</strong> Utilisez l'onglet \"Conception\" pour modifier l'apparence de votre roue de la chance en ligne. Vous pourrez choisir vos propres couleurs, ajouter une image de fond et bien plus.",
            "<strong>Sauvegardez vos créations :</strong> Une fois votre roue du hasard perfecte, enregistrez-la dans votre navigateur pour pouvoir la réutiliser plus tard en un seul clic.",
            "<strong>Lancez la roue ! :</strong> Cliquez sur le bouton central \"LANCER\" et regardez la magie opérer. Le résultat s'affichera dans une fenêtre festive."
        ],
        usesTitle: "Des usages illimités pour tous les besoins",
        usesText: "La flexibilité de notre",
        usesText2: "roue de la chance gratuite",
        usesText3: "la rend utile dans de nombreuses situations :",
        usesItems: [
            "<strong>Pour les enseignants :</strong> Idéal pour une sélection aléatoire d'élèves, créer une roue de questions pour réviser, ou attribuer des sujets d'exposé de manière équitable.",
            "<strong>Pour les jeux et événements :</strong> Désignez le gagnant d'un concours, attribuez des prix dans une tombola, ou créez un jeu de défis pour animer une soirée avec une roue en ligne.",
            "<strong>Dans la vie de tous les jours :</strong> Vous n'arrivez pas à choisir un film, un restaurant ou une destination de vacances ? Laissez",
            "<strong>Pour la créativité :</strong> Bloqué sur un projet ? Utilisez la roue en ligne hasard pour générer des idées, des noms de personnages, ou des concepts pour votre prochaine création."
        ],
        usesItem3Part2: "la roue du hasard",
        usesItem3Part3: "décider pour vous !",
        featuresTitle: "Fonctionnalités avancées : Multi-roues et personnalisation",
        featuresText: "Notre outil va au-delà des simples générateurs de roue. Découvrez des fonctionnalités exclusives pour une expérience unique :",
        featuresItems: [
            "<strong>Support multi-roues (Bientôt !) :</strong> Notre",
            "<strong>Personnalisation poussée :</strong> Ajoutez des images et des sons personnalisés à chaque segment pour rendre vos tirages avec la roulette aléatoire encore plus immersifs et amusants.",
            "<strong>100% Gratuite et sans inscription :</strong> Accédez à toutes les fonctionnalités sans dépenser un centime et sans avoir à créer de compte."
        ],
        featureItem1Part2: "roulette en ligne",
        featureItem1Part3: "vous permettra de faire tourner plusieurs roues simultanément. Imaginez les possibilités : une roue de la chance pour le plat principal, une autre pour le dessert !",
        ctaTitle: "Prêt à faire tourner la roue ?",
        ctaText: "Maintenant que vous connaissez tous les secrets de notre outil, il est temps de passer à l'action.",
        ctaLink: "➤ Créez votre première Roue Aléatoire !",
    },
    en: {
        metaTitle: "Spin Wheel Guide | How to Use Our Random Picker & Custom Wheel",
        metaDescription: "Learn to master our spin wheel generator! The complete guide to creating a custom spin wheel for your games, prize draws, decisions, and more. Spin the wheel now!",
        title: "Complete Guide to the Online Spin Wheel",
        intro: "Welcome to the user guide for our",
        introLink: "free and customizable spin wheel",
        intro2: ". Learn to master our tool for making decisions, organizing prize draws, and much more.",
        whatIsTitle: "What is a Spin Wheel?",
        whatIsText: "Our",
        whatIsText2: "online spin wheel",
        whatIsText3: "is a random drawing tool designed to be simple, fun, and fully adaptable. Whether you need to pick a name at random, spice up a game with challenges, or decide where to eat, our wheel is the ideal solution. Use our",
        whatIsText4: "spin wheel picker",
        whatIsText5: "and let fate choose for you!",
        howToTitle: "How to create and use your custom spin wheel 🌀",
        howToText: "Creating your own",
        howToText2: "custom spin wheel",
        howToText3: "is child's play. Follow these simple steps:",
        howToSteps: [
            "<strong>Add your entries:</strong> In the \"Customize\" panel, enter the options you want to see on the spin wheel of names. These can be names, numbers, tasks, or emojis 🔥!",
            "<strong>Customize the design (Coming Soon!):</strong> Use the \"Design\" tab to change the appearance of your wheel. You'll be able to choose your own colors, add a background image, and much more.",
            "<strong>Save your creations:</strong> Once your custom spin wheel is perfect, save it in your browser to reuse it later with a single click.",
            "<strong>Spin the wheel!:</strong> Click the central \"SPIN\" button and watch the magic happen. The result will be displayed in a festive window."
        ],
        usesTitle: "Unlimited uses for the Spin Wheel Picker",
        usesText: "The flexibility of our",
        usesText2: "free spin wheel generator",
        usesText3: "makes it useful in many situations:",
        usesItems: [
            "<strong>For teachers:</strong> Use a spin wheel of names to designate a student to answer a question.",
            "<strong>For games and events:</strong> Designate a contest winner, award prizes in a raffle, or create a game of challenges to liven up a party.",
            "<strong>In everyday life:</strong> Can't decide on a movie, a restaurant, or a vacation destination? Let the",
            "<strong>For creativity:</strong> Stuck on a project? Use the wheel to generate ideas, character names, or concepts for your next creation."
        ],
        usesItem3Part2: "random spin wheel",
        usesItem3Part3: "decide for you!",
        featuresTitle: "Advanced features: Multi-wheels and customization",
        featuresText: "Our tool goes beyond simple wheel generators. Discover exclusive features for a unique experience:",
        featuresItems: [
            "<strong>Multi-wheel support (Coming Soon!):</strong> The only",
            "<strong>Advanced customization:</strong> Add custom images and sounds to each segment to make your draws even more immersive and fun.",
            "<strong>100% Free and no registration:</strong> Access all features at no cost and with no registration required."
        ],
        featureItem1Part2: "spin wheel generator",
        featureItem1Part3: "that will allow you to spin multiple wheels simultaneously. Imagine the possibilities: one wheel for the main course, another for dessert!",
        ctaTitle: "Ready to spin the wheel?",
        ctaText: "Now that you know all the secrets of our tool, it's time to take action.",
        ctaLink: "➤ Create your first Spin Wheel!",
    },
    es: {
        metaTitle: "Guía de la Ruleta de la Suerte | Cómo usar nuestra Ruleta Giratoria",
        metaDescription: "Aprende a dominar nuestra ruleta giratoria online. La guía definitiva para crear una ruleta de la suerte personalizada para tus sorteos, juegos y decisiones.",
        title: "Guía Completa de la Ruleta Virtual",
        intro: "Bienvenido a la guía de usuario de nuestra",
        introLink: "ruleta personalizada y gratuita",
        intro2: ". Aprende a dominar nuestra ruleta para tomar decisiones, organizar sorteos y mucho más.",
        whatIsTitle: "¿Qué es la Ruleta Aleatoria?",
        whatIsText: "Nuestra",
        whatIsText2: "ruleta en línea",
        whatIsText3: "es una herramienta de sorteo aleatorio diseñada para ser simple, divertida y totalmente adaptable. Ya sea que necesites elegir un nombre al azar, animar un juego con desafíos, decidir dónde comer o hacer una simple elección de \"Sí/No\", nuestra ruleta virtual es la solución ideal. ¡Gira",
        whatIsText4: "la ruleta",
        whatIsText5: "y deja que el azar decida por ti!",
        howToTitle: "Cómo crear y usar tu ruleta personalizada 🌀",
        howToText: "Crear tu propia",
        howToText2: "ruleta virtual",
        howToText3: "es un juego de niños. Sigue estos sencillos pasos:",
        howToSteps: [
            "<strong>Añade tus entradas:</strong> En el panel \"Personalizar\", introduce las opciones que quieres ver en la ruleta. ¡Pueden ser nombres, números, tareas, emojis 🔥 o incluso imágenes!",
            "<strong>Personaliza el diseño (¡Próximamente!):</strong> Usa la pestaña \"Diseño\" para cambiar la apariencia de tu ruleta en línea. Podrás elegir tus propios colores, añadir una imagen de fondo y mucho más.",
            "<strong>Guarda tus creaciones:</strong> Una vez que tu ruleta personalizada esté perfecta, guárdala en tu navegador para poder reutilizarla más tarde con un solo clic.",
            "<strong>¡Gira la ruleta!:</strong> Haz clic en el gran botón central \"GIRAR\" y observa la magia. El resultado se mostrará en una ventana festiva."
        ],
        usesTitle: "Usos ilimitados para todas las necesidades",
        usesText: "La flexibilidad de nuestra",
        usesText2: "ruleta en línea gratuita",
        usesText3: "la hace útil en muchas situaciones:",
        usesItems: [
            "<strong>Para profesores:</strong> Ideal para seleccionar alumnos al azar, crear una ruleta de preguntas para repasar o asignar temas de exposición de manera justa.",
            "<strong>Para juegos y eventos:</strong> Designa al ganador de un concurso, otorga premios en una rifa o crea un juego de desafíos para animar una fiesta.",
            "<strong>En la vida cotidiana:</strong> ¿No puedes decidir qué película ver, a qué restaurante ir o a qué destino de vacaciones viajar? ¡Deja que",
            "<strong>Para la criatividade:</strong> ¿Atascado en un proyecto? Usa la ruleta para generar ideas, nombres de personajes o conceptos para tu próxima creación."
        ],
        usesItem3Part2: "la ruleta aleatoria",
        usesItem3Part3: "decida por ti!",
        featuresTitle: "Funciones avanzadas: Multi-ruletas y personalización",
        featuresText: "Nuestra herramienta va más allá de los simples generadores de ruletas. Descubre funciones exclusivas para una experiencia única:",
        featuresItems: [
            "<strong>Soporte multi-ruleta (¡Próximamente!):</strong> La única",
            "<strong>Personalización avanzada:</strong> Añade imágenes y sonidos personalizados a cada segmento para que tus sorteos sean aún más inmersivos y divertidos.",
            "<strong>100% Gratuita y sin registro:</strong> Accede a todas las funciones sin gastar un céntimo y sin necesidad de crear una cuenta."
        ],
        featureItem1Part2: "ruleta virtual",
        featureItem1Part3: "que te permitirá girar varias ruletas simultáneamente. ¡Imagina las posibilidades: una ruleta para el plato principal y otra para el postre!",
        ctaTitle: "¿Listo para girar la ruleta?",
        ctaText: "Ahora que conoces todos los secretos de nuestra herramienta, es hora de pasar a la acción.",
        ctaLink: "➤ ¡Crea tu primera Ruleta Aleatoria!",
    },
    de: {
        metaTitle: "Anleitung Glücksrad | So verwenden Sie unser Zufallsrad & Drehrad",
        metaDescription: "Meistern Sie unser Online-Drehrad! Die vollständige Anleitung, um ein anpassbares Glücksrad für Ihre Gewinnspiele, Spiele und Entscheidungen zu erstellen.",
        title: "Vollständige Anleitung zum Online-Zufallsrad",
        intro: "Willkommen zur Bedienungsanleitung für unser",
        introLink: "kostenloses und anpassbares Glücksrad",
        intro2: ". Lernen Sie, unser Zufallsrad-Tool zu meistern, um Entscheidungen zu treffen, Verlosungen zu organisieren und vieles mehr.",
        whatIsTitle: "Was ist das Glücksrad?",
        whatIsText: "Unser",
        whatIsText2: "Online-Zufallsrad",
        whatIsText3: "ist ein zufälliges Ziehungswerkzeug, das einfach, unterhaltsam und vollständig anpassbar ist. Ob Sie einen Namen zufällig auswählen, ein Spiel mit Herausforderungen aufpeppen, entscheiden müssen, wo Sie essen gehen, oder eine einfache \"Ja/Nein\"-Entscheidung treffen müssen, unser Zufallsrad ist die ideale Lösung. Drehen Sie",
        whatIsText4: "das Glücksrad",
        whatIsText5: "und lassen Sie das Schicksal für Sie entscheiden!",
        howToTitle: "So erstellen und verwenden Sie Ihr anpassbares Rad 🌀",
        howToText: "Ihr eigenes",
        howToText2: "anpassbares Zufallsrad",
        howToText3: "zu erstellen ist kinderleicht. Befolgen Sie diese einfachen Schritte:",
        howToSteps: [
            "<strong>Fügen Sie Ihre Einträge hinzu:</strong> Geben Sie im Bereich \"Anpassen\" die Optionen ein, die Sie auf dem Rad sehen möchten. Das können Namen, Zahlen, Aufgaben, Emojis 🔥 oder sogar Bilder sein!",
            "<strong>Passen Sie das Design an (bald verfügbar!):</strong> Verwenden Sie den Tab \"Design\", um das Aussehen Ihres Online-Rads zu ändern. Sie können Ihre eigenen Farben wählen, ein Hintergrundbild hinzufügen und vieles mehr.",
            "<strong>Speichern Sie Ihre Kreationen:</strong> Sobald Ihr Rad perfekt ist, speichern Sie es in Ihrem Browser, um es später mit einem einzigen Klick wiederverwenden zu können.",
            "<strong>Drehen Sie das Rad!:</strong> Klicken Sie auf den zentralen \"DREHEN\"-Button und sehen Sie die Magie. Das Ergebnis wird in einem festlichen Fenster angezeigt."
        ],
        usesTitle: "Unbegrenzte Einsatzmöglichkeiten für alle Bedürfnisse",
        usesText: "Die Flexibilität unseres",
        usesText2: "kostenlosen Glücksrads",
        usesText3: "macht es in vielen Situationen nützlich:",
        usesItems: [
            "<strong>Für Lehrer:</strong> Ideal zur zufälligen Auswahl von Schülern, zum Erstellen eines Fragenrads zur Wiederholung oder zur fairen Vergabe von Präsentationsthemen.",
            "<strong>Für Spiele und Veranstaltungen:</strong> Bestimmen Sie einen Gewinner eines Wettbewerbs, vergeben Sie Preise in einer Tombola oder erstellen Sie ein Herausforderungsspiel, um eine Party zu beleben.",
            "<strong>Im Alltag:</strong> Können Sie sich nicht für einen Film, ein Restaurant oder ein Urlaubsziel entscheiden? Lassen Sie",
            "<strong>Für die Kreativität:</strong> Stecken Sie bei einem Projekt fest? Verwenden Sie das Rad, um Ideen, Charakternamen oder Konzepte für Ihre nächste Kreation zu generieren."
        ],
        usesItem3Part2: "das Zufallsrad",
        usesItem3Part3: "für Sie entscheiden!",
        featuresTitle: "Erweiterte Funktionen: Mehrere Räder und Anpassung",
        featuresText: "Unser Tool geht über einfache Radgeneratoren hinaus. Entdecken Sie exklusive Funktionen für ein einzigartiges Erlebnis:",
        featuresItems: [
            "<strong>Unterstützung für mehrere Räder (bald verfügbar!):</strong> Das einzige",
            "<strong>Erweiterte Anpassung:</strong> Fügen Sie jedem Segment benutzerdefinierte Bilder und Sounds hinzu, um Ihre Ziehungen noch immersiver und unterhaltsamer zu gestalten.",
            "<strong>100% kostenlos und ohne Registrierung:</strong> Greifen Sie auf alle Funktionen zu, ohne einen Cent auszugeben und ohne ein Konto erstellen zu müssen."
        ],
        featureItem1Part2: "Online-Zufallsrad",
        featureItem1Part3: ", mit dem Sie mehrere Räder gleichzeitig drehen können. Stellen Sie sich die Möglichkeiten vor: ein Rad für den Hauptgang, ein anderes für das Dessert!",
        ctaTitle: "Bereit, das Rad zu drehen?",
        ctaText: "Jetzt, da Sie alle Geheimnisse unseres Tools kennen, ist es Zeit zu handeln.",
        ctaLink: "➤ Erstellen Sie Ihr erstes Zufallsrad!",
    },
    pt: {
        metaTitle: "Guia da Roda da Sorte | Como usar nossa Roleta Giratória Aleatória",
        metaDescription: "Aprenda a dominar a nossa roleta giratória online! O guia completo para criar uma roda da sorte personalizável para os seus jogos, sorteios e decisões.",
        title: "Guia Completo da Roda da Sorte",
        intro: "Bem-vindo ao guia de utilização da nossa",
        introLink: "roda da sorte gratuita e personalizável",
        intro2: ". Aprenda a dominar a nossa ferramenta de roleta giratória para tomar decisões, organizar sorteios e muito mais.",
        whatIsTitle: "O que é a Roda da Sorte?",
        whatIsText: "A nossa",
        whatIsText2: "roleta giratória online grátis",
        whatIsText3: "é uma ferramenta de sorteio aleatório concebida para ser simples, divertida e totalmente adaptável. Quer precise de escolher um nome ao acaso, apimentar um jogo com desafios, decidir onde comer ou fazer uma simples escolha de \"Sim/Não\", a nossa roda da sorte é a solução ideal. Gire",
        whatIsText4: "a roleta giratória",
        whatIsText5: "e deixe o destino escolher por si!",
        howToTitle: "Como criar uma roda giratória interativa 🌀",
        howToText: "Criar a sua própria",
        howToText2: "roda personalizada para promoções",
        howToText3: "é uma brincadeira de crianças. Siga estes passos simples:",
        howToSteps: [
            "<strong>Adicione as suas entradas:</strong> No painel \"Personalizar\", insira as opções que deseja ver na roda. Podem ser nomes, números, tarefas ou emojis 🔥!",
            "<strong>Personalize o design (Em breve!):</strong> Use o separador \"Design\" para alterar a aparência da sua roda da sorte online. Poderá escolher as suas próprias cores, adicionar uma imagem de fundo e muito mais.",
            "<strong>Guarde as suas criações:</strong> Assim que a sua roda giratória para sorteios estiver perfeita, guarde-a no seu navegador para poder reutilizá-la mais tarde com um único clique.",
            "<strong>Gire a roda!:</strong> Clique no botão central \"GIRAR\" e veja a magia acontecer. O resultado será exibido numa janela festiva."
        ],
        usesTitle: "Usos ilimitados para a sua Roda da Sorte",
        usesText: "A flexibilidade da nossa",
        usesText2: "ferramenta de roda giratória para eventos",
        usesText3: "torna-a útil em muitas situações:",
        usesItems: [
            "<strong>Para professores:</strong> Ideal para uma seleção aleatória de alunos ou para criar uma roda de perguntas para revisões.",
            "<strong>Para jogos e eventos:</strong> Designe o vencedor de um concurso ou atribua prémios num sorteio.",
            "<strong>No dia a dia:</strong> Não consegue decidir um filme, um restaurante ou um destino de férias? Deixe a",
            "<strong>Para a criatividade:</strong> Bloqueado num projeto? Use a roda para gerar ideias ou nomes de personagens."
        ],
        usesItem3Part2: "roda da sorte",
        usesItem3Part3: "decidir por si!",
        featuresTitle: "Funcionalidades avançadas: Multi-rodas e personalização",
        featuresText: "A nossa ferramenta vai além dos simples geradores de rodas. Descubra funcionalidades exclusivas:",
        featuresItems: [
            "<strong>Suporte multi-rodas (Em breve!):</strong> A única",
            "<strong>Personalização avançada:</strong> Adicione imagens e sons personalizados a cada segmento para tornar os seus sorteios com a roleta ainda mais imersivos.",
            "<strong>100% Gratuita e sem registo:</strong> Aceda a todas as funcionalidades sem gastar um cêntimo e sem precisar de criar uma conta. Não precisa comprar uma roda giratória para negócios!"
        ],
        featureItem1Part2: "roleta giratória online grátis",
        featureItem1Part3: "que lhe permitirá girar várias rodas em simultâneo. Imagine as possibilidades: uma roda para o prato principal, outra para a sobremesa!",
        ctaTitle: "Pronto para girar a roda da sorte?",
        ctaText: "Agora que conhece todos os segredos da nossa ferramenta, está na hora de passar à ação.",
        ctaLink: "➤ Crie a sua primeira Roda da Sorte!",
    }
}
