
export const translations = {
    fr: {
        metaTitle: "Roue de la Chance Films d'Action | Roue aléatoire pour Soirée Cinéma",
        metaDescription: "Lancez notre roue des films d'action pour choisir un film à regarder. Cette roulette en ligne est un outil de tirage au sort gratuit parmi une liste de classiques.",
        ogImage: 'https://avisclients.digitalextension.fr/wp-content/uploads/2025/07/Top-10-films.png',
        pageTitle: "Roue de la Chance : Top 10 Films d'Action",
        description: "Lancez cette roue aléatoire pour un tirage de film et pimentez votre soirée cinéma.",
        storageWarning: "Sauvegarde automatique : Vos options et votre historique sont enregistrés dans votre navigateur.",
        spinButton: "LANCER",
        customizeTooltip: "Personnaliser la liste",
        shuffleTooltip: "Mélanger les films",
        resultsTooltip: "Historique des tirages",
        hideTooltip: "Masquer le panneau",
        showTooltip: "Afficher le panneau",
        defaultOptions: [
            { id: 'die-hard', name: 'Die Hard' },
            { id: 'terminator-2', name: 'Terminator 2' },
            { id: 'mad-max', name: 'Mad Max: Fury Road' },
            { id: 'the-dark-knight', name: 'The Dark Knight' },
            { id: 'inception', name: 'Inception' },
            { id: 'the-matrix', name: 'The Matrix' },
            { id: 'john-wick', name: 'John Wick' },
            { id: 'predator', name: 'Predator' },
            { id: 'aliens', name: 'Aliens' },
            { id: 'mission-impossible', name: 'Mission: Impossible' },
        ],
        sectionTitle: "Organisez votre soirée cinéma avec la <strong>Roue en Ligne des Films d'Action</strong>",
        sectionDescription: "Indécis sur le film à regarder ce soir ? Laissez notre <strong>roue en ligne</strong> choisir pour vous un classique de l'action. Fini les débats, place au spectacle !",
        whatIsTitle: "Qu'est-ce que la Roue en ligne des Films d'Action ?",
        whatIsText: "C'est une <strong>roulette en ligne</strong> spécialement conçue pour les cinéphiles, pré-remplie avec une sélection des 10 films d'action les plus emblématiques. C'est l'outil de <strong>tirage au sort</strong> parfait pour pimenter vos soirées.",
        whyUseTitle: "Pourquoi utiliser cette roue en ligne ?",
        whyUseText: "Pour le fun et la simplicité ! Au lieu de perdre du temps à parcourir les catalogues, laissez cette <strong>roue en ligne</strong> prendre une décision rapide et aléatoire. C'est aussi une excellente façon de (re)découvrir des chefs-d'œuvre du cinéma d'action.",
        howToUseTitle: "Comment lancer un tirage au sort de film ?",
        howToUseSteps: [
            "<strong>Consultez la sélection :</strong> Le top 10 est déjà prêt pour le tirage.",
            "<strong>Personnalisez la liste :</strong> N'hésitez pas à ajouter vos propres films préférés ou à en retirer via le panneau 'Personnaliser'.",
            "<strong>Lancez la roue en ligne :</strong> Cliquez sur \"LANCER\" et préparez le pop-corn. La <strong>roue en ligne</strong> a choisi pour vous !",
        ],
        ideasTitle: "Idées d'utilisation pour cette roue en ligne de films",
        ideasItems: [
            "<strong>Soirée film entre amis :</strong> Mettez fin aux débats interminables sur le choix du film.",
            "<strong>Marathon de films :</strong> Lancez la <strong>roue en ligne</strong> plusieurs fois pour organiser un marathon d'action.",
            "<strong>Découverte cinéphile :</strong> Utilisez la <strong>roulette en ligne</strong> pour explorer des classiques que vous n'avez pas encore vus.",
            "<strong>Jeu à boire :</strong> Associez des règles à chaque film pour une soirée encore plus animée."
        ],
        faqTitle: "Questions Fréquemment Posées",
        faqItems: [
            { "q": "La roue est-elle vraiment aléatoire ?", "a": "<strong>Absolument.</strong> Notre roue du hasard utilise un algorithme de Génération de Nombres Aléatoires de pointe pour garantir que chaque résultat est <strong>totalement imprévisible et indépendant</strong> des tours précédents. Chaque segment a une probabilité égale d'être sélectionné, assurant un tirage 100% juste et équitable. Pour en savoir plus sur le fonctionnement, vous pouvez consulter notre <a href='/fr/guide-roue-de-la-chance' class='text-primary hover:underline'>guide d'utilisation</a>." },
            { "q": "Puis-je utiliser la roue sur mon téléphone mobile ?", "a": "<strong>Oui, bien sûr !</strong> Notre site est entièrement \"responsive\", ce qui signifie que notre roue en ligne est conçue pour fonctionner perfectly sur tous les appareils : ordinateurs de bureau, tablettes et smartphones. L'expérience est optimisée pour que vous puissiez faire tourner la roue où que vous soyez, quand vous le voulez." },
            { "q": "Comment sont sauvegardées mes options ?", "a": "La configuration de votre roue de la chance, y compris les options, est <strong>automatiquement sauvegardée dans le stockage local de votre navigateur</strong> (`localStorage`). Cela signifie que lorsque vous revenez sur notre site, vous retrouvez votre roue telle que vous l'avez laissée. C'est 100% privé et sécurisé sur votre appareil." },
            { "q": "Comment partager ma roue personnalisée ?", "a": "C'est très facile ! Utilisez le bouton <strong>'Partager'</strong> situé dans l'en-tête de la page. Cela générera un lien URL unique contenant la configuration de votre roue. Vous pourrez copier ce lien et l'envoyer à vos amis. Ils utiliseront alors exactement la même roue aléatoire que vous, ce qui est parfait pour les jeux à distance !" },
            { "q": "Mes données sont-elles vraiment privées ?", "a": "<strong>La confidentialité est notre priorité absolue.</strong> Toutes les données de votre roue (options et historique) sont stockées <strong>uniquement sur votre appareil</strong>. Nous ne collectons, ne voyons, ni ne stockons aucune de ces informations sur nos serveurs. C'est une des raisons pour lesquelles notre outil est si rapide et sécurisé. Pour plus de détails, n'hésitez pas à consulter notre <a href='/fr/politique-de-confidentialite' class='text-primary hover:underline'>Politique de Confidentialité</a>." }
        ],
        ctaTitle: "Créez votre propre roue en ligne thématique",
        ctaText: "Envie d'une roue avec des films de science-fiction, des comédies, ou les films d'un acteur en particulier ? Créez votre propre <strong>roue en ligne</strong> personnalisée.",
        ctaLink: "➤ Créer une Roue sur Mesure"
    },
    en: {
        metaTitle: "Action Movies Spin Wheel | Random Picker for Movie Night",
        metaDescription: "Spin our action movies wheel to pick a film for movie night. This online spinner is a free random picker from a list of classic movies. Spin the wheel now!",
        ogImage: 'https://avisclients.digitalextension.fr/wp-content/uploads/2025/07/Top-10-films.png',
        pageTitle: "Top 10 Action Movies Spin Wheel",
        description: "Use our movie spin wheel generator for a random pick and enjoy your movie night.",
        storageWarning: "Automatic saving: Your options and history are saved in your browser.",
        spinButton: "SPIN",
        customizeTooltip: "Customize the list",
        shuffleTooltip: "Shuffle the movies",
        resultsTooltip: "Draw history",
        hideTooltip: "Hide panel",
        showTooltip: "Show panel",
        defaultOptions: [
            { id: 'die-hard', name: 'Die Hard' },
            { id: 'terminator-2', name: 'Terminator 2' },
            { id: 'mad-max', name: 'Mad Max: Fury Road' },
            { id: 'the-dark-knight', name: 'The Dark Knight' },
            { id: 'inception', name: 'Inception' },
            { id: 'the-matrix', name: 'The Matrix' },
            { id: 'john-wick', name: 'John Wick' },
            { id: 'predator', name: 'Predator' },
            { id: 'aliens', name: 'Aliens' },
            { id: 'mission-impossible', name: 'Mission: Impossible' },
        ],
        sectionTitle: "Plan your movie night with the <strong>Action Movies Spin Wheel</strong>",
        sectionDescription: "Undecided on which movie to watch tonight? Let our <strong>online spinner</strong> choose an action classic for you. No more debates, it's showtime!",
        whatIsTitle: "What is the Action Movies Spin Wheel?",
        whatIsText: "This is an <strong>online wheel</strong> specially designed for movie lovers, pre-filled with a selection of the 10 most iconic action films. It's the perfect <strong>random draw</strong> tool to spice up your evenings.",
        whyUseTitle: "Why use this online spinner?",
        whyUseText: "For fun and simplicity! Instead of wasting time browsing catalogs, let this <strong>spin wheel</strong> make a quick, random decision. It's also a great way to (re)discover masterpieces of action cinema.",
        howToUseTitle: "How to draw a random movie?",
        howToUseSteps: [
            "<strong>Check the selection:</strong> The top 10 is ready for the draw.",
            "<strong>Customize the list:</strong> Feel free to add your own favorite movies or remove some via the 'Customize' panel.",
            "<strong>Spin the wheel:</strong> Click \"SPIN\" and get the popcorn ready. The <strong>online spinner</strong> has chosen for you!",
        ],
        ideasTitle: "Usage ideas for this online movie wheel",
        ideasItems: [
            "<strong>Movie night with friends:</strong> End the endless debates over which movie to pick.",
            "<strong>Movie marathon:</strong> Spin the <strong>online wheel</strong> several times to organize an action marathon.",
            "<strong>Cinephile discovery:</strong> Use the <strong>spinner</strong> to explore classics you haven't seen yet.",
            "<strong>Drinking game:</strong> Associate rules with each movie for an even livelier evening."
        ],
        faqTitle: "Frequently Asked Questions",
        faqItems: [
            { "q": "Is the wheel truly random?", "a": "<strong>Absolutely.</strong> Our spin wheel uses a state-of-the-art Random Number Generator (RNG) algorithm to ensure that every result is <strong>completely unpredictable and independent</strong> of previous spins. Each segment has an equal probability of being selected, guaranteeing a 100% fair draw. You can learn more in our <a href='/en/guide-spin-wheel-of-chance' class='text-primary hover:underline'>user guide</a>." },
            { "q": "Can I use the spin wheel on my mobile phone?", "a": "<strong>Yes, of course!</strong> Our website is fully responsive, which means it is designed to work perfectly on all devices: desktops, tablets, and smartphones. The experience is optimized so you can spin the wheel wherever and whenever you want." },
            { "q": "How is my custom wheel configuration saved?", "a": "Your wheel configuration, including your custom options, is <strong>automatically saved in your browser's local storage</strong> (`localStorage`). This means when you return to our site, you'll find your wheel just as you left it. It's 100% private and secure on your device." },
            { "q": "How can I share my custom wheel?", "a": "It's very easy! Use the <strong>'Share' button</strong> in the page header. This will generate a unique URL containing your wheel's setup. You can copy this link and send it to your friends. They will then be able to use the exact same random wheel as you, which is perfect for remote games!" },
            { "q": "Is my data really private?", "a": "<strong>Privacy is our absolute priority.</strong> All your wheel data (options and history) is stored <strong>only on your device</strong>. We do not collect, see, or store any of this information on our servers. This is one of the reasons our tool is so fast and secure. For more details, feel free to consult our <a href='/en/privacy-policy' class='text-primary hover:underline'>Privacy Policy</a>." }
        ],
        ctaTitle: "Create your own themed online wheel",
        ctaText: "Want a wheel with sci-fi movies, comedies, or films by a specific actor? Create your own custom <strong>online wheel</strong>.",
        ctaLink: "➤ Create a Custom Wheel"
    },
    es: {
        metaTitle: "Ruleta en Línea de las Mejores Películas de Acción | Ruleta de Cine",
        metaDescription: "Gira nuestra ruleta de películas de acción para elegir qué ver. Esta ruleta de la suerte online es una herramienta de sorteo gratuita de una lista de clásicos del cine.",
        ogImage: 'https://avisclients.digitalextension.fr/wp-content/uploads/2025/07/Top-10-films.png',
        pageTitle: "Ruleta: Top 10 Películas de Acción",
        description: "Gira la ruleta online para un sorteo de película y anima tu noche de cine.",
        storageWarning: "Guardado automático: Tus opciones e historial se guardan en tu navegador.",
        spinButton: "GIRAR",
        customizeTooltip: "Personalizar la lista",
        shuffleTooltip: "Mezclar las películas",
        resultsTooltip: "Historial de sorteios",
        hideTooltip: "Ocultar panel",
        showTooltip: "Mostrar panel",
        defaultOptions: [
            { id: 'die-hard', name: 'Die Hard (Jungla de Cristal)' },
            { id: 'terminator-2', name: 'Terminator 2' },
            { id: 'mad-max', name: 'Mad Max: Furia en la Carretera' },
            { id: 'the-dark-knight', name: 'El Caballero Oscuro' },
            { id: 'inception', name: 'Origen' },
            { id: 'the-matrix', name: 'The Matrix' },
            { id: 'john-wick', name: 'John Wick' },
            { id: 'predator', name: 'Depredador' },
            { id: 'aliens', name: 'Aliens: El Regreso' },
            { id: 'mission-impossible', name: 'Misión: Imposible' },
        ],
        sectionTitle: "Organiza tu noche de cine con la <strong>Ruleta en Línea de Películas de Acción</strong>",
        sectionDescription: "¿Indeciso sobre qué película ver esta noche? Deja que nuestra <strong>ruleta en línea</strong> elija por ti un clásico de acción. ¡Se acabaron los debates, que empiece el espectáculo!",
        whatIsTitle: "¿Qué es la Ruleta en Línea de Películas de Acción?",
        whatIsText: "Es una <strong>ruleta en línea</strong> especialmente diseñada para cinéfilos, precargada con una selección de las 10 películas de acción más icónicas. Es la herramienta de <strong>sorteo</strong> perfecta para animar tus noches.",
        whyUseTitle: "¿Por qué usar esta ruleta en línea?",
        whyUseText: "¡Por diversión y simplicidad! En lugar de perder tiempo navegando por catálogos, deja que esta <strong>ruleta en línea</strong> tome una decisión rápida y aleatoria. También es una excelente manera de (re)descubrir obras maestras del cine de acción.",
        howToUseTitle: "¿Cómo hacer un sorteo de película?",
        howToUseSteps: [
            "<strong>Consulta la selección:</strong> El top 10 ya está listo para el sorteo.",
            "<strong>Personaliza la lista:</strong> No dudes en añadir tus propias películas favoritas o quitar algunas a través del panel 'Personalizar'.",
            "<strong>Gira la ruleta en línea:</strong> ¡Haz clic en \"GIRAR\" y prepara las palomitas! ¡La <strong>ruleta en línea</strong> ha elegido por ti!",
        ],
        ideasTitle: "Ideas de uso para esta ruleta en línea de películas",
        ideasItems: [
            "<strong>Noche de cine con amigos:</strong> Pon fin a los interminables debates sobre qué película elegir.",
            "<strong>Maratón de películas:</strong> Gira la <strong>ruleta en línea</strong> varias veces para organizar un maratón de acción.",
            "<strong>Descubrimiento cinéfilo:</strong> Usa la <strong>ruleta en línea</strong> para explorar clásicos que aún no has visto.",
            "<strong>Juego de beber:</strong> Asocia reglas a cada película para una noche aún más animada."
        ],
        faqTitle: "Preguntas Frecuentes",
        faqItems: [
            { "q": "¿La ruleta es realmente aleatoria?", "a": "<strong>Absolutamente.</strong> Nuestra ruleta utiliza un algoritmo de Generador de Números Aleatorios (RNG) para garantizar que cada resultado sea <strong>impredecible e independiente</strong> de los giros anteriores. Cada segmento tiene la misma probabilidad de ser seleccionado, asegurando un sorteo 100% justo. Puedes aprender más en nuestra <a href='/es/guia-ruleta-de-la-suerte' class='text-primary hover:underline'>guía de uso</a>." },
            { "q": "¿Puedo usar la ruleta en mi teléfono móvil?", "a": "<strong>¡Sí, claro!</strong> Nuestro sitio está completamente diseñado para funcionar perfectamente en todos los dispositivos: ordenadores, tabletas y teléfonos inteligentes. La experiencia está optimizada para que puedas girar la ruleta estés donde estés." },
            { "q": "¿Cómo se guardan mis opciones?", "a": "La configuración de tu ruleta, incluyendo tus opciones personalizadas, se <strong>guarda automáticamente en el almacenamiento local de tu navegador</strong> (`localStorage`). Esto significa que cuando regreses, encontrarás tu ruleta tal como la dejaste. ¡Es 100% privado y seguro en tu dispositivo!" },
            { "q": "¿Cómo comparto mi ruleta personalizada?", "a": "¡Es muy fácil! Utiliza el botón <strong>'Compartir'</strong> situado en el encabezado de la página. Esto generará un enlace URL único que contiene la configuración de tu ruleta. Puedes copiar este enlace y enviarlo a tus amigos, lo que es perfecto para juegos a distancia." },
            { "q": "¿Mis datos son realmente privados?", "a": "<strong>La privacidad es nuestra máxima prioridad.</strong> Todos los datos de tu ruleta (opciones e historial) se almacenan <strong>únicamente en tu dispositivo</strong>. No recopilamos, vemos ni almacenamos ninguna de esta información en nuestros servidores. Para más detalles, no dudes en consultar nuestra <a href='/es/politica-de-privacidad' class='text-primary hover:underline'>Política de Privacidad</a>." }
        ],
        ctaTitle: "Crea tu propia ruleta en línea temática",
        ctaText: "¿Quieres una ruleta con películas de ciencia ficción, comedias o las películas de un actor en particular? Crea tu <strong>ruleta en línea</strong> personalizada.",
        ctaLink: "➤ Crear una Ruleta a Medida"
    },
    de: {
        metaTitle: "Actionfilme-Glücksrad | Kino-Roulette",
        metaDescription: "Drehen Sie unser Actionfilme-Glücksrad, um einen Film auszuwählen. Dieses Online-Drehrad ist ein kostenloses Zufallswerkzeug aus einer Liste von Filmklassikern.",
        ogImage: 'https://avisclients.digitalextension.fr/wp-content/uploads/2025/07/Top-10-films.png',
        pageTitle: "Actionfilme-Glücksrad: Top 10",
        description: "Drehen Sie das Glücksrad für eine zufällige Filmauswahl und genießen Sie Ihren Filmabend.",
        storageWarning: "Automatische Speicherung: Ihre Optionen und Ihr Verlauf werden in Ihrem Browser gespeichert.",
        spinButton: "DREHEN",
        customizeTooltip: "Liste anpassen",
        shuffleTooltip: "Filme mischen",
        resultsTooltip: "Ziehungsverlauf",
        hideTooltip: "Panel ausblenden",
        showTooltip: "Panel anzeigen",
        defaultOptions: [
            { id: 'die-hard', name: 'Stirb Langsam' },
            { id: 'terminator-2', name: 'Terminator 2' },
            { id: 'mad-max', name: 'Mad Max: Fury Road' },
            { id: 'the-dark-knight', name: 'The Dark Knight' },
            { id: 'inception', name: 'Inception' },
            { id: 'the-matrix', name: 'Matrix' },
            { id: 'john-wick', name: 'John Wick' },
            { id: 'predator', name: 'Predator' },
            { id: 'aliens', name: 'Aliens – Die Rückkehr' },
            { id: 'mission-impossible', name: 'Mission: Impossible' },
        ],
        sectionTitle: "Organisieren Sie Ihren Filmabend mit dem <strong>Actionfilme-Glücksrad</strong>",
        sectionDescription: "Unentschlossen, welchen Film Sie heute Abend sehen sollen? Lassen Sie unser <strong>Glücksrad</strong> einen Action-Klassiker für Sie auswählen. Keine Debatten mehr, die Show kann beginnen!",
        whatIsTitle: "Was ist das Actionfilme-Glücksrad?",
        whatIsText: "Dies ist ein <strong>Online-Glücksrad</strong>, das speziell für Filmfans entwickelt wurde und mit einer Auswahl der 10 kultigsten Actionfilme vorab gefüllt ist. Es ist das perfekte <strong>Zufallsziehungswerkzeug</strong>, um Ihre Abende aufzupeppen.",
        whyUseTitle: "Warum dieses Glücksrad verwenden?",
        whyUseText: "Aus Spaß und Einfachheit! Anstatt Zeit mit dem Durchsuchen von Katalogen zu verschwenden, lassen Sie dieses <strong>Glücksrad</strong> eine schnelle, zufällige Entscheidung treffen. Es ist auch eine großartige Möglichkeit, Meisterwerke des Actionkinos (wieder) zu entdecken.",
        howToUseTitle: "Wie zieht man einen zufälligen Film?",
        howToUseSteps: [
            "<strong>Überprüfen Sie die Auswahl:</strong> Die Top 10 sind bereits für die Ziehung bereit.",
            "<strong>Passen Sie die Liste an:</strong> Fühlen Sie sich frei, Ihre eigenen Lieblingsfilme hinzuzufügen oder einige über das 'Anpassen'-Panel zu entfernen.",
            "<strong>Drehen Sie das Glücksrad:</strong> Klicken Sie auf \"DREHEN\" und machen Sie das Popcorn bereit. Das <strong>Glücksrad</strong> hat für Sie gewählt!",
        ],
        ideasTitle: "Anwendungsideen für dieses Film-Glücksrad",
        ideasItems: [
            "<strong>Filmabend mit Freunden:</strong> Beenden Sie die endlosen Debatten über die Wahl des Films.",
            "<strong>Filmmarathon:</strong> Drehen Sie das <strong>Glücksrad</strong> mehrmals, um einen Action-Marathon zu organisieren.",
            "<strong>Cinephile Entdeckung:</strong> Nutzen Sie das <strong>Glücksrad</strong>, um Klassiker zu entdecken, die Sie noch nicht gesehen haben.",
            "<strong>Trinkspiel:</strong> Verknüpfen Sie Regeln mit jedem Film für einen noch lebhafteren Abend."
        ],
        faqTitle: "Häufig gestellte Fragen",
        faqItems: [
            { "q": "Ist das Glücksrad wirklich zufällig?", "a": "<strong>Absolut.</strong> Unser Glücksrad verwendet einen Zufallszahlengenerator (RNG), um sicherzustellen, dass jedes Ergebnis <strong>unvorhersehbar und unabhängig</strong> von früheren Drehungen ist. Jedes Segment hat die gleiche Wahrscheinlichkeit, was eine 100% faire Ziehung garantiert. Erfahren Sie mehr in unserer <a href='/de/anleitung-zufallsrad' class='text-primary hover:underline'>Anleitung</a>." },
            { "q": "Kann ich das Glücksrad auf meinem Handy benutzen?", "a": "<strong>Ja, natürlich!</strong> Unsere Seite ist vollständig so konzipiert, dass sie auf allen Geräten perfekt funktioniert: Desktops, Tablets und Smartphones. Das Erlebnis ist optimiert, damit Sie das Glücksrad drehen können, wo immer Sie sind." },
            { "q": "Wie werden meine Optionen gespeichert?", "a": "Ihre Glücksrad-Konfiguration wird <strong>automatisch in Ihrem Browser gespeichert</strong> (`localStorage`). Das bedeutet, wenn Sie zurückkehren, finden Sie Ihr Glücksrad so vor, wie Sie es verlassen haben. Es ist 100% privat und sicher auf Ihrem Gerät." },
            { "q": "Wie teile ich mein benutzerdefiniertes Glücksrad?", "a": "Ganz einfach! Verwenden Sie die Schaltfläche <strong>'Teilen'</strong> im Kopfbereich der Seite. Dadurch wird ein eindeutiger URL-Link generiert, der Ihre Glücksrad-Konfiguration enthält, perfekt für Fernspiele!" },
            { "q": "Sind meine Daten wirklich privat?", "a": "<strong>Datenschutz hat für uns oberste Priorität.</strong> Alle Ihre Glücksrad-Daten (Optionen und Verlauf) werden <strong>nur auf Ihrem Gerät</strong> gespeichert. Wir sammeln, sehen oder speichern keine dieser Informationen auf unseren Servern. Für weitere Details können Sie gerne unsere <a href='/de/datenschutzrichtlinie' class='text-primary hover:underline'>Datenschutzrichtlinie</a> konsultieren." }
        ],
        ctaTitle: "Erstellen Sie Ihr eigenes thematisches Glücksrad",
        ctaText: "Möchten Sie ein Rad mit Sci-Fi-Filmen, Komödien oder Filmen eines bestimmten Schauspielers? Erstellen Sie Ihr eigenes benutzerdefiniertes <strong>Glücksrad</strong>.",
        ctaLink: "➤ Erstellen Sie ein benutzerdefiniertes Glücksrad"
    },
    pt: {
        metaTitle: "Roleta Online dos Melhores Filmes de Ação | Roleta de Cinema",
        metaDescription: "Gire a nossa roleta de filmes de ação para escolher um filme. Esta roda da sorte online é uma ferramenta de sorteio gratuita de uma lista de clássicos.",
        ogImage: 'https://avisclients.digitalextension.fr/wp-content/uploads/2025/07/Top-10-films.png',
        pageTitle: "Roleta Online: Top 10 Filmes de Ação",
        description: "Gire a roleta para uma escolha aleatória de filme e aproveite a sua noite de cinema.",
        storageWarning: "Gravação automática: As suas opções e histórico são guardados no seu navegador.",
        spinButton: "GIRAR",
        customizeTooltip: "Personalizar a lista",
        shuffleTooltip: "Baralhar os filmes",
        resultsTooltip: "Histórico de sorteios",
        hideTooltip: "Ocultar painel",
        showTooltip: "Mostrar painel",
        defaultOptions: [
            { id: 'die-hard', name: 'Die Hard: Assalto ao Arranha-Céus' },
            { id: 'terminator-2', name: 'O Exterminador Implacável 2' },
            { id: 'mad-max', name: 'Mad Max: Estrada da Fúria' },
            { id: 'the-dark-knight', name: 'O Cavaleiro das Trevas' },
            { id: 'inception', name: 'A Origem' },
            { id: 'the-matrix', name: 'The Matrix' },
            { id: 'john-wick', name: 'John Wick' },
            { id: 'predator', name: 'O Predador' },
            { id: 'aliens', name: 'Aliens: O Recontro Final' },
            { id: 'mission-impossible', name: 'Missão: Impossível' },
        ],
        sectionTitle: "Organize a sua noite de cinema com a <strong>Roleta Online de Filmes de Ação</strong>",
        sectionDescription: "Indeciso sobre que filme ver esta noite? Deixe que a nossa <strong>roleta online</strong> escolha um clássico de ação por si. Acabaram-se os debates, que comece o espetáculo!",
        whatIsTitle: "O que é a Roleta Online de Filmes de Ação?",
        whatIsText: "É uma <strong>roleta online</strong> especialmente concebida para cinéfilos, pré-preenchida com uma seleção dos 10 filmes de ação mais icónicos. É a ferramenta de <strong>sorteio</strong> perfeita para animar as suas noites.",
        whyUseTitle: "Porquê usar esta roleta online?",
        whyUseText: "Pela diversão e simplicidade! Em vez de perder tempo a navegar por catálogos, deixe que esta <strong>roleta online</strong> tome uma decisão rápida e aleatória. É também uma ótima maneira de (re)descobrir obras-primas do cinema de ação.",
        howToUseTitle: "Como sortear um filme aleatório?",
        howToUseSteps: [
            "<strong>Consulte a seleção:</strong> O top 10 está pronto para o sorteio.",
            "<strong>Personalize a lista:</strong> Sinta-se à vontade para adicionar os seus próprios filmes favoritos ou remover alguns através do painel 'Personalizar'.",
            "<strong>Gire a roleta online:</strong> Clique em \"GIRAR\" e prepare as pipocas. A <strong>roleta online</strong> escolheu por si!",
        ],
        ideasTitle: "Ideias de utilização para esta roleta online de filmes",
        ideasItems: [
            "<strong>Noite de cinema com amigos:</strong> Ponha fim aos debates intermináveis sobre que filme escolher.",
            "<strong>Maratona de filmes:</strong> Gire a <strong>roleta online</strong> várias vezes para organizar uma maratona de ação.",
            "<strong>Descoberta cinéfila:</strong> Use a <strong>roleta online</strong> para explorar clássicos que ainda não viu.",
            "<strong>Jogo de bebida:</strong> Associe regras a cada filme para uma noite ainda mais animada."
        ],
        faqTitle: "Perguntas Frequentes",
        faqItems: [
            { "q": "A roda é realmente aleatória?", "a": "<strong>Absolutamente.</strong> A nossa roda utiliza um gerador de números aleatórios (RNG) para garantir que cada resultado é <strong>imprevisível e independente</strong> das rotações anteriores. Cada segmento tem a mesma probabilidade de ser selecionado, garantindo um sorteio 100% justo. Pode saber mais no nosso <a href='/pt/guia-roda-da-sorte' class='text-primary hover:underline'>guia de utilização</a>." },
            { "q": "Posso usar a roda no meu telemóvel?", "a": "<strong>Sim, claro!</strong> O nosso site é totalmente responsivo, o que significa que foi concebido para funcionar perfeitamente em todos os dispositivos: computadores, tablets e smartphones. A experiência está otimizada para que possa girar a roda onde quer que esteja." },
            { "q": "Como são guardadas as minhas opções?", "a": "A configuração da sua roda, incluindo as suas opções personalizadas, é <strong>automaticamente guardada no armazenamento local do seu navegador</strong> (`localStorage`). Isto significa que quando regressar, encontrará a sua roda tal como a deixou. É 100% privado e seguro no seu dispositivo." },
            { "q": "Como posso partilhar a minha roda personalizada?", "a": "É muito fácil! Utilize o botão <strong>'Partilhar'</strong> localizado no cabeçalho da página. Isto irá gerar um link URL único contendo a configuração da sua roda, perfeito para jogos à distância!" },
            { "q": "Os meus dados são realmente privados?", "a": "<strong>A privacidade é a nossa prioridade absoluta.</strong> Todos os dados da sua roda (opções e histórico) são armazenados <strong>apenas no seu dispositivo</strong>. Não recolhemos, vemos ou armazenamos nenhuma destas informações nos nossos servidores. Para mais detalhes, não hesite em consultar a nossa <a href='/pt/politica-de-privacidade' class='text-primary hover:underline'>Política de Privacidade</a>." }
        ],
        ctaTitle: "Crie a sua própria roleta online temática",
        ctaText: "Quer uma roda com filmes de ficção científica, comédias ou filmes de um ator específico? Crie a sua <strong>roleta online</strong> personalizada.",
        ctaLink: "➤ Criar uma Roda Personalizada"
    }
}
