
export const translations = {
    fr: {
        metaTitle: "Roue de la Chance 10 Pays les Plus Visités | Roue aléatoire de destinations",
        metaDescription: "Besoin d'inspiration de voyage ? Lancez notre roue des destinations et laissez le hasard choisir un pays pour vous parmi les 10 plus visités. Un tirage au sort ludique !",
        ogImage: 'https://avisclients.digitalextension.fr/wp-content/uploads/2025/07/roue-pays-les-plus-visites.webp',
        pageTitle: "Roue de la Chance des 10 Pays les Plus Visités",
        description: "Lancez cette roue aléatoire pour un tirage de destination et inspirez votre prochain voyage.",
        storageWarning: "Sauvegarde automatique : Vos options et votre historique sont enregistrés dans votre navigateur.",
        spinButton: "LANCER",
        customizeTooltip: "Personnaliser",
        shuffleTooltip: "Mélanger",
        resultsTooltip: "Historique",
        hideTooltip: "Masquer",
        showTooltip: "Afficher",
        defaultOptions: [
            { id: 'fr', name: 'France' },
            { id: 'es', name: 'Espagne' },
            { id: 'us', name: 'États-Unis' },
            { id: 'cn', name: 'Chine' },
            { id: 'it', name: 'Italie' },
            { id: 'tr', name: 'Turquie' },
            { id: 'mx', name: 'Mexique' },
            { id: 'de', name: 'Allemagne' },
            { id: 'th', name: 'Thaïlande' },
            { id: 'gb', name: 'Royaume-Uni' },
        ],
        sectionTitle: "Planifiez votre prochain voyage avec la <strong>Roue des Destinations</strong>",
        sectionDescription: "Vous ne savez pas où partir ? Laissez notre <strong>générateur de destination aléatoire</strong> choisir pour vous parmi les 10 pays les plus visités de la planète. L'aventure vous attend !",
        whatIsTitle: "Qu'est-ce que cette roue de la chance thématique ?",
        whatIsText: "C'est une <strong>roulette en ligne</strong> pré-remplie avec la liste des 10 pays qui accueillent le plus de touristes chaque année. C'est l'outil de <strong>tirage au sort</strong> parfait pour trouver l'inspiration pour vos prochaines vacances ou pour des jeux sur le thème du voyage.",
        whyUseTitle: "Pourquoi utiliser ce générateur aléatoire ?",
        whyUseText: "Pour le plaisir de la surprise ! Au lieu de passer des heures à chercher une destination, laissez la <strong>roue de la chance</strong> vous proposer une idée excitante. C'est aussi une excellente façon de découvrir des pays auxquels vous n'auriez peut-être pas pensé.",
        howToUseTitle: "Comment faire un tirage au sort de destination ?",
        howToUseSteps: [
            "<strong>La liste est prête :</strong> Les 10 pays les plus visités sont déjà dans la roue.",
            "<strong>Ajoutez vos propres idées :</strong> Vous pouvez bien sûr modifier la liste pour inclure vos propres destinations de rêve via le panneau 'Personnaliser'.",
            "<strong>Lancez la roulette et rêvez :</strong> Cliquez sur \"LANCER\" et découvrez où notre <strong>générateur aléatoire</strong> pourrait vous envoyer pour votre prochaine aventure!",
        ],
        ideasTitle: "Idées d'utilisation pour cette roue de voyage",
        ideasItems: [
            "<strong>Inspiration de voyage :</strong> La façon la plus simple de choisir votre prochaine destination avec un <strong>générateur aléatoire</strong>.",
            "<strong>Défi culinaire :</strong> Cuisinez un plat typique du pays qui a été sélectionné par la <strong>roulette</strong>.",
            "<strong>Soirée film :</strong> Regardez un film qui se déroule dans le pays sélectionné par le <strong>tirage au sort</strong>.",
            "<strong>Jeu éducatif :</strong> Testez vos connaissances sur la capitale, la langue ou l'histoire du pays gagnant."
        ],
        faqTitle: "Questions Fréquemment Posées",
        faqItems: [
            { "q": "La roue est-elle vraiment aléatoire ?", "a": "<strong>Absolument.</strong> Notre roue du hasard utilise un algorithme de Génération de Nombres Aléatoires de pointe pour garantir que chaque résultat est <strong>totalement imprévisible et indépendant</strong> des tours précédents. Chaque segment a une probabilité égale d'être sélectionné, assurant un tirage 100% juste et équitable. Pour en savoir plus sur le fonctionnement, vous pouvez consulter notre <a href='/fr/guide-roue-de-la-chance' class='text-primary hover:underline'>guide d'utilisation</a>." },
            { "q": "Puis-je utiliser la roue sur mon téléphone mobile ?", "a": "<strong>Oui, bien sûr !</strong> Notre site est entièrement \"responsive\", ce qui signifie que notre roue en ligne est conçue pour fonctionner parfaitement sur tous les appareils : ordinateurs de bureau, tablettes et smartphones. L'expérience est optimisée pour que vous puissiez faire tourner la roue où que vous soyez, quand vous le voulez." },
            { "q": "Comment sont sauvegardées mes options ?", "a": "La configuration de votre roue de la chance, y compris les options, est <strong>automatiquement sauvegardée dans le stockage local de votre navigateur</strong> (`localStorage`). Cela signifie que lorsque vous revenez sur notre site, vous retrouvez votre roue telle que vous l'avez laissée. C'est 100% privé et sécurisé sur votre appareil." },
            { "q": "Comment partager ma roue personnalisée ?", "a": "C'est très facile ! Utilisez le bouton <strong>'Partager'</strong> situé dans l'en-tête de la page. Cela générera un lien URL unique contenant la configuration de votre roue. Vous pourrez copier ce lien et l'envoyer à vos amis. Ils utiliseront alors exactement la même roue aléatoire que vous, ce qui est parfait pour les jeux à distance !" },
            { "q": "Mes données sont-elles vraiment privées ?", "a": "<strong>La confidentialité est notre priorité absolue.</strong> Toutes les données de votre roue (options et historique) sont stockées <strong>uniquement sur votre appareil</strong>. Nous ne collectons, ne voyons, ni ne stockons aucune de ces informations sur nos serveurs. C'est une des raisons pour lesquelles notre outil est si rapide et sécurisé. Pour plus de détails, n'hésitez pas à consulter notre <a href='/fr/politique-de-confidentialite' class='text-primary hover:underline'>Politique de Confidentialité</a>." }
        ],
        ctaTitle: "Créez votre propre roue de voyage",
        ctaText: "Vous voulez faire une roue avec les capitales d'Europe ou les plages de Thaïlande ? Créez votre propre <strong>roue de la chance</strong> personnalisée dès maintenant.",
        ctaLink: "➤ Créer une Roue Personalizada"
    },
    en: {
        metaTitle: "Spin Wheel of Top 10 Visited Countries | Random Destination Picker",
        metaDescription: "Need travel inspiration? Spin our destination wheel and let the random picker choose a country for you from the 10 most visited. A fun online spinner for your next trip!",
        ogImage: 'https://avisclients.digitalextension.fr/wp-content/uploads/2025/07/roue-pays-les-plus-visites-monde.webp',
        pageTitle: "Top 10 Visited Countries Spin Wheel",
        description: "Use our travel spin wheel generator for a random destination and get inspired for your next trip.",
        storageWarning: "Automatic saving: Your options and history are saved in your browser.",
        spinButton: "SPIN",
        customizeTooltip: "Customize",
        shuffleTooltip: "Shuffle",
        resultsTooltip: "History",
        hideTooltip: "Hide",
        showTooltip: "Show",
        defaultOptions: [
            { id: 'fr', name: 'France' },
            { id: 'es', name: 'Spain' },
            { id: 'us', name: 'United States' },
            { id: 'cn', name: 'China' },
            { id: 'it', name: 'Italy' },
            { id: 'tr', name: 'Turkey' },
            { id: 'mx', name: 'Mexico' },
            { id: 'de', name: 'Germany' },
            { id: 'th', name: 'Thailand' },
            { id: 'gb', name: 'United Kingdom' },
        ],
        sectionTitle: "Plan your next trip with the <strong>Destination Spin Wheel</strong>",
        sectionDescription: "Don't know where to go? Let our <strong>random destination generator</strong> choose for you from the 10 most visited countries on the planet. Adventure awaits!",
        whatIsTitle: "What is this themed spin wheel?",
        whatIsText: "This is a pre-filled <strong>online spinner</strong> with the list of the 10 countries that welcome the most tourists each year. It's the perfect <strong>random draw</strong> tool to find inspiration for your next vacation or for travel-themed games.",
        whyUseTitle: "Why use this random generator?",
        whyUseText: "For the fun of the surprise! Instead of spending hours searching for a destination, let the <strong>spin wheel</strong> give you an exciting idea. It's also a great way to discover countries you might not have thought of.",
        howToUseTitle: "How to draw a random destination?",
        howToUseSteps: [
            "<strong>The list is ready:</strong> The 10 most visited countries are already on the wheel.",
            "<strong>Add your own ideas:</strong> You can, of course, modify the list to include your own dream destinations via the 'Customize' panel.",
            "<strong>Spin the wheel and dream:</strong> Click \"SPIN\" and find out where our <strong>random generator</strong> might send you for your next adventure!",
        ],
        ideasTitle: "Usage Ideas for this travel wheel",
        ideasItems: [
            "<strong>Travel inspiration:</strong> The easiest way to choose your next destination with a <strong>random generator</strong>.",
            "<strong>Culinary challenge:</strong> Cook a typical dish from the country selected by the <strong>spinner</strong>.",
            "<strong>Movie night:</strong> Watch a movie that takes place in the country selected by the <strong>random draw</strong>.",
            "<strong>Educational game:</strong> Test your knowledge of the capital, language, or history of the winning country."
        ],
        faqTitle: "Frequently Asked Questions",
        faqItems: [
            { "q": "Is the wheel truly random?", "a": "<strong>Absolutely.</strong> Our spin wheel uses a state-of-the-art Random Number Generator (RNG) algorithm to ensure that every result is <strong>completely unpredictable and independent</strong> of previous spins. Each segment has an equal probability of being selected, guaranteeing a 100% fair draw. You can learn more in our <a href='/en/guide-spin-wheel-of-chance' class='text-primary hover:underline'>user guide</a>." },
            { "q": "Can I use the spin wheel on my mobile phone?", "a": "<strong>Yes, of course!</strong> Our website is fully responsive, which means it is designed to work perfectly on all devices: desktops, tablets, and smartphones. The experience is optimized so you can spin the wheel wherever and whenever you want." },
            { "q": "How is my custom wheel configuration saved?", "a": "Your wheel configuration, including your custom options, is <strong>automatically saved in your browser's local storage</strong> (`localStorage`). This means when you return to our site, you'll find your wheel just as you left it. It's 100% private and secure on your device." },
            { "q": "How can I share my custom wheel?", "a": "It's very easy! Use the <strong>'Share' button</strong> in the page header. This will generate a unique URL containing your wheel's setup. You can copy this link and send it to your friends. They will then be able to use the exact same random wheel as you, which is perfect for remote games!" },
            { "q": "Is my data really private?", "a": "<strong>Privacy is our absolute priority.</strong> All your wheel data (options and history) is stored <strong>only on your device</strong>. We do not collect, see, or store any of this information on our servers. This is one of the reasons our tool is so fast and secure. For more details, feel free to consult our <a href='/en/privacy-policy' class='text-primary hover:underline'>Privacy Policy</a>." }
        ],
        ctaTitle: "Create your own travel wheel",
        ctaText: "Want to make a wheel with the capitals of Europe or the beaches of Thailand? Create your own custom <strong>spin wheel</strong> now.",
        ctaLink: "➤ Create a Custom Wheel"
    },
    es: {
        metaTitle: "Ruleta en Línea de los 10 Países Más Visitados",
        metaDescription: "¿Necesitas inspiración para viajar? Gira nuestra ruleta de destinos y deja que el azar elija un país para ti entre los 10 más visitados. ¡Un sorteo divertido para tu próximo viaje!",
        ogImage: 'https://avisclients.digitalextension.fr/wp-content/uploads/2025/07/roue-pays-les-plus-visites-monde.webp',
        pageTitle: "Ruleta de los 10 Países Más Visitados",
        description: "Gira la ruleta para un sorteo de destino. Un generador de viajes aleatorio para inspirarte.",
        storageWarning: "Guardado automático: Tus opciones e historial se guardan en tu navegador.",
        spinButton: "GIRAR",
        customizeTooltip: "Personalizar",
        shuffleTooltip: "Mezclar",
        resultsTooltip: "Historial",
        hideTooltip: "Ocultar",
        showTooltip: "Mostrar",
        defaultOptions: [
            { id: 'fr', name: 'Francia' },
            { id: 'es', name: 'España' },
            { id: 'us', name: 'Estados Unidos' },
            { id: 'cn', name: 'China' },
            { id: 'it', name: 'Italia' },
            { id: 'tr', name: 'Turquía' },
            { id: 'mx', name: 'México' },
            { id: 'de', name: 'Alemania' },
            { id: 'th', name: 'Tailandia' },
            { id: 'gb', name: 'Reino Unido' },
        ],
        sectionTitle: "Planifica tu próximo viaje con la <strong>Ruleta de Destinos</strong>",
        sectionDescription: "¿No sabes a dónde ir? Deja que nuestro <strong>generador de destinos aleatorio</strong> elija por ti entre los 10 países más visitados del planeta. ¡La aventura te espera!",
        whatIsTitle: "¿Qué es esta ruleta de la suerte temática?",
        whatIsText: "Es una <strong>ruleta en línea</strong> precargada con la lista de los 10 países que reciben más turistas cada año. Es la herramienta de <strong>sorteo</strong> perfecta para encontrar inspiración para tus próximas vacaciones o para juegos con temática de viajes.",
        whyUseTitle: "¿Por qué usar este generador aleatorio?",
        whyUseText: "¡Por la diversión de la sorpresa! En lugar de pasar horas buscando un destino, deja que la <strong>ruleta de la suerte</strong> te dé una idea emocionante. También es una excelente manera de descubrir países en los que quizás no habías pensado.",
        howToUseTitle: "¿Cómo hacer un sorteo de destino?",
        howToUseSteps: [
            "<strong>La lista está lista:</strong> Los 10 países más visitados ya están en la ruleta.",
            "<strong>Añade tus propias ideas:</strong> Por supuesto, puedes modificar la lista para incluir tus propios destinos de ensueño a través del panel 'Personalizar'.",
            "<strong>Gira la ruleta y sueña:</strong> ¡Haz clic en \"GIRAR\" y descubre a dónde podría llevarte nuestro <strong>generador aleatorio</strong> en tu próxima aventura!",
        ],
        ideasTitle: "Ideas de uso para esta ruleta de viajes",
        ideasItems: [
            "<strong>Inspiración para viajar:</strong> La forma más fácil de elegir tu próximo destino con un <strong>generador aleatorio</strong>.",
            "<strong>Desafío culinario:</strong> Cocina un plato típico del país que salió en la <strong>ruleta</strong>.",
            "<strong>Noche de cine:</strong> Mira una película que se desarrolle en el país seleccionado por el <strong>sorteo</strong>.",
            "<strong>Juego educativo:</strong> Pon a prueba tus conocimientos sobre la capital, el idioma o la historia del país ganador."
        ],
        faqTitle: "Preguntas Frecuentes",
        faqItems: [
            { "q": "¿La ruleta es realmente aleatoria?", "a": "<strong>Absolutamente.</strong> Nuestra ruleta utiliza un algoritmo de Generador de Números Aleatorios (RNG) para garantizar que cada resultado sea <strong>impredecible e independiente</strong> de los giros anteriores. Cada segmento tiene la misma probabilidad de ser seleccionado, asegurando un sorteo 100% justo. Puedes aprender más en nuestra <a href='/es/guia-ruleta-de-la-suerte' class='text-primary hover:underline'>guía de uso</a>." },
            { "q": "¿Puedo usar la ruleta en mi teléfono móvil?", "a": "<strong>¡Sí, claro!</strong> Nuestro sitio está completamente diseñado para funcionar perfectamente en todos los dispositivos: ordenadores, tabletas y teléfonos inteligentes. La experiencia está optimizada para que puedas girar la ruleta estés donde estés." },
            { "q": "¿Cómo se guardan mis opciones?", "a": "La configuración de tu ruleta, incluyendo tus opciones personalizadas, se <strong>guarda automáticamente en el almacenamiento local de tu navegador</strong> (`localStorage`). Esto significa que cuando regreses, encontrarás tu ruleta tal como la dejaste. ¡Es 100% privado y seguro en tu dispositivo!" },
            { "q": "¿Cómo comparto mi ruleta personalizada?", "a": "¡Es muy fácil! Utiliza el botón <strong>'Compartir'</strong> situado en el encabezado de la página. Esto generará un enlace URL único que contiene la configuración de tu ruleta. Puedes copiar este enlace y enviarlo a tus amigos, lo que es perfecto para juegos a distancia." },
            { "q": "¿Mis datos son realmente privados?", "a": "<strong>La privacidad es nuestra máxima prioridad.</strong> Todos los datos de tu ruleta (opciones e historial) se almacenan <strong>únicamente en tu dispositivo</strong>. No recopilamos, vemos ni almacenamos ninguna de esta información en nuestros servidores. Para más detalles, no dudes en consultar nuestra <a href='/es/politica-de-privacidad' class='text-primary hover:underline'>Política de Privacidad</a>." }
        ],
        ctaTitle: "Crea tu propia ruleta de viajes",
        ctaText: "¿Quieres hacer una ruleta con las capitales de Europa o las playas de Tailandia? Crea tu propia <strong>ruleta de la suerte</strong> personalizada ahora.",
        ctaLink: "➤ Crear una Ruleta Personalizada"
    },
    de: {
        metaTitle: "Länder-Glücksrad der 10 meistbesuchten Länder",
        metaDescription: "Brauchen Sie Reiseinspiration? Drehen Sie unser Reiseziel-Glücksrad und lassen Sie den Zufall ein Land für Sie aus den 10 meistbesuchten auswählen. Ein lustiges Drehrad für Ihre nächste Reise!",
        ogImage: 'https://avisclients.digitalextension.fr/wp-content/uploads/2025/07/roue-pays-les-plus-visites-monde.webp',
        pageTitle: "Länder-Glücksrad: Top 10",
        description: "Drehen Sie das Glücksrad für ein Traumziel. Ein Zufallsgenerator für Reisen zur Inspiration.",
        storageWarning: "Automatische Speicherung: Ihre Optionen und Ihr Verlauf werden in Ihrem Browser gespeichert.",
        spinButton: "DREHEN",
        customizeTooltip: "Anpassen",
        shuffleTooltip: "Mischen",
        resultsTooltip: "Verlauf",
        hideTooltip: "Ausblenden",
        showTooltip: "Anzeigen",
        defaultOptions: [
            { id: 'fr', name: 'Frankreich' },
            { id: 'es', name: 'Spanien' },
            { id: 'us', name: 'Vereinigte Staaten' },
            { id: 'cn', name: 'China' },
            { id: 'it', name: 'Italien' },
            { id: 'tr', name: 'Türkei' },
            { id: 'mx', name: 'Mexiko' },
            { id: 'de', name: 'Deutschland' },
            { id: 'th', name: 'Thailand' },
            { id: 'gb', name: 'Vereinigtes Königreich' },
        ],
        sectionTitle: "Planen Sie Ihre nächste Reise mit dem <strong>Reiseziel-Glücksrad</strong>",
        sectionDescription: "Sie wissen nicht, wohin Sie reisen sollen? Lassen Sie unseren <strong>Zufallsgenerator für Reiseziele</strong> für Sie aus den 10 meistbesuchten Ländern der Welt wählen. Das Abenteuer wartet!",
        whatIsTitle: "Was ist dieses thematische Glücksrad?",
        whatIsText: "Dies ist ein vorausgefülltes <strong>Online-Glücksrad</strong> mit der Liste der 10 Länder, die jedes Jahr die meisten Touristen anziehen. Es ist das perfekte <strong>Zufallsgenerator</strong>-Werkzeug, um Inspiration für Ihren nächsten Urlaub oder für Reisespiele zu finden.",
        whyUseTitle: "Warum diesen Zufallsgenerator verwenden?",
        whyUseText: "Für den Spaß an der Überraschung! Anstatt stundenlang nach einem Reiseziel zu suchen, lassen Sie sich vom <strong>Glücksrad</strong> eine aufregende Idee geben. Es ist auch eine großartige Möglichkeit, Länder zu entdecken, an die Sie vielleicht nicht gedacht hätten.",
        howToUseTitle: "Wie zieht man ein zufälliges Reiseziel?",
        howToUseSteps: [
            "<strong>Die Liste ist fertig:</strong> Die 10 meistbesuchten Länder sind bereits auf dem Rad.",
            "<strong>Fügen Sie Ihre eigenen Ideen hinzu:</strong> Sie können die Liste natürlich ändern, um Ihre eigenen Traumziele über das 'Anpassen'-Panel hinzuzufügen.",
            "<strong>Drehen Sie das Glücksrad und träumen Sie:</strong> Klicken Sie auf \"DREHEN\" und finden Sie heraus, wohin unser <strong>Zufallsgenerator</strong> Sie bei Ihrem nächsten Abenteuer führen könnte!",
        ],
        ideasTitle: "Anwendungsideen für dieses Glücksrad",
        ideasItems: [
            "<strong>Reiseinspiration:</strong> Der einfachste Weg, Ihr nächstes Reiseziel mit einem <strong>Zufallsgenerator</strong> zu wählen.",
            "<strong>Kulinarische Herausforderung:</strong> Kochen Sie ein typisches Gericht aus dem Land, das vom <strong>Glücksrad</strong> ausgewählt wurde.",
            "<strong>Filmabend:</strong> Sehen Sie sich einen Film an, der in dem durch die <strong>Zufallsziehung</strong> ausgewählten Land spielt.",
            "<strong>Lernspiel:</strong> Testen Sie Ihr Wissen über die Hauptstadt, die Sprache oder die Geschichte des Gewinnerlandes."
        ],
        faqTitle: "Häufig gestellte Fragen",
        faqItems: [
            { "q": "Ist das Glücksrad wirklich zufällig?", "a": "<strong>Absolut.</strong> Unser Glücksrad verwendet einen Zufallszahlengenerator (RNG), um sicherzustellen, dass jedes Ergebnis <strong>unvorhersehbar und unabhängig</strong> von früheren Drehungen ist. Jedes Segment hat die gleiche Wahrscheinlichkeit, was eine 100% faire Ziehung garantiert. Erfahren Sie mehr in unserer <a href='/de/anleitung-zufallsrad' class='text-primary hover:underline'>Anleitung</a>." },
            { "q": "Kann ich das Glücksrad auf meinem Handy benutzen?", "a": "<strong>Ja, natürlich!</strong> Unsere Seite ist vollständig so konzipiert, dass sie auf allen Geräten perfekt funktioniert: Desktops, Tablets und Smartphones. Das Erlebnis ist optimiert, damit Sie das Glücksrad drehen können, wo immer Sie sind." },
            { "q": "Wie werden meine Optionen gespeichert?", "a": "Ihre Glücksrad-Konfiguration wird <strong>automatisch in Ihrem Browser gespeichert</strong> (`localStorage`). Das bedeutet, wenn Sie zurückkehren, finden Sie Ihr Glücksrad so vor, wie Sie es verlassen haben. Es ist 100% privat und sicher auf Ihrem Gerät." },
            { "q": "Wie teile ich mein benutzerdefiniertes Glücksrad?", "a": "Ganz einfach! Verwenden Sie die Schaltfläche <strong>'Teilen'</strong> im Kopfbereich der Seite. Dadurch wird ein eindeutiger URL-Link generiert, der Ihre Glücksrad-Konfiguration enthält, perfekt für Fernspiele!" },
            { "q": "Sind meine Daten wirklich privat?", "a": "<strong>Datenschutz hat für uns oberste Priorität.</strong> Alle Ihre Glücksrad-Daten (Optionen und Verlauf) werden <strong>nur auf Ihrem Gerät</strong> gespeichert. Wir sammeln, sehen oder speichern keine dieser Informationen auf unseren Servern. Für weitere Details können Sie gerne unsere <a href='/de/datenschutzrichtlinie' class='text-primary hover:underline'>Datenschutzrichtlinie</a> konsultieren." }
        ],
        ctaTitle: "Erstellen Sie Ihr eigenes Reise-Glücksrad",
        ctaText: "Möchten Sie ein Rad mit den Hauptstädten Europas oder den Stränden Thailands? Erstellen Sie jetzt Ihr eigenes benutzerdefiniertes <strong>Glücksrad</strong>.",
        ctaLink: "➤ Erstellen Sie ein benutzerdefiniertes Glücksrad"
    },
    pt: {
        metaTitle: "Roda Online dos 10 Países Mais Visitados",
        metaDescription: "Precisa de inspiração para viajar? Gire a nossa roleta de destinos e deixe o sorteador escolher um país para si entre os 10 mais visitados. Uma roda da sorte divertida para a sua próxima viagem!",
        ogImage: 'https://avisclients.digitalextension.fr/wp-content/uploads/2025/07/roue-pays-les-plus-visites-monde.webp',
        pageTitle: "Roda dos 10 Países Mais Visitados",
        description: "Gire a roleta para um sorteio de destino. Um gerador de viagens aleatório para o inspirar.",
        storageWarning: "Gravação automática: As suas opções e histórico são guardados no seu navegador.",
        spinButton: "GIRAR",
        customizeTooltip: "Personalizar",
        shuffleTooltip: "Baralhar",
        resultsTooltip: "Histórico",
        hideTooltip: "Ocultar",
        showTooltip: "Mostrar",
        defaultOptions: [
            { id: 'fr', name: 'França' },
            { id: 'es', name: 'Espanha' },
            { id: 'us', name: 'Estados Unidos' },
            { id: 'cn', name: 'China' },
            { id: 'it', name: 'Itália' },
            { id: 'tr', name: 'Turquia' },
            { id: 'mx', name: 'México' },
            { id: 'de', name: 'Alemanha' },
            { id: 'th', name: 'Tailândia' },
            { id: 'gb', name: 'Reino Unido' },
        ],
        sectionTitle: "Planeie a sua próxima viagem com a <strong>Roda dos Destinos</strong>",
        sectionDescription: "Não sabe para onde ir? Deixe que o nosso <strong>gerador de destino aleatório</strong> escolha por si entre os 10 países mais visitados do planeta. A aventura espera por si!",
        whatIsTitle: "O que é esta roda da sorte temática?",
        whatIsText: "É uma <strong>roleta online</strong> pré-preenchida com a lista dos 10 países que recebem mais turistas todos os anos. É a ferramenta de <strong>sorteio</strong> perfeita para encontrar inspiração para as suas próximas férias ou para jogos com o tema de viagens.",
        whyUseTitle: "Porquê usar este gerador aleatório?",
        whyUseText: "Pela diversão da surpresa! Em vez de passar horas à procura de um destino, deixe que a <strong>roda da sorte</strong> lhe dê uma ideia emocionante. É também uma ótima maneira de descubrir países em que talvez não tivesse pensado.",
        howToUseTitle: "Como fazer um sorteio de destino?",
        howToUseSteps: [
            "<strong>A lista está pronta:</strong> Os 10 países mais visitados já estão na roda.",
            "<strong>Adicione as suas próprias ideias:</strong> Pode, claro, modificar a lista para incluir os seus próprios destinos de sonho através do painel 'Personalizar'.",
            "<strong>Gire a roleta e sonhe:</strong> Clique em \"GIRAR\" e descubra para onde o nosso <strong>gerador aleatório</strong> o poderá levar na sua próxima aventura!",
        ],
        ideasTitle: "Ideias de utilização para esta roda de viagens",
        ideasItems: [
            "<strong>Inspiração para viagens:</strong> A forma mais fácil de escolher o seu próximo destino com um <strong>gerador aleatório</strong>.",
            "<strong>Desafio culinário:</strong> Cozinhe um prato típico do país que foi selecionado pela <strong>roleta</strong>.",
            "<strong>Noite de cinema:</strong> Assista a um filme que se passa no país selecionado pelo <strong>sorteio</strong>.",
            "<strong>Jogo educativo:</strong> Teste os seus conhecimentos sobre a capital, a língua ou a história do país vencedor."
        ],
        faqTitle: "Perguntas Frequentes",
        faqItems: [
            { "q": "A roda é realmente aleatória ?", "a": "<strong>Absolutamente.</strong> A nossa roda utiliza um gerador de números aleatórios (RNG) para garantir que cada resultado é <strong>imprevisível e independente</strong> das rotações anteriores. Cada segmento tem a mesma probabilidade de ser selecionado, garantindo um sorteio 100% justo. Pode saber mais no nosso <a href='/pt/guia-roda-da-sorte' class='text-primary hover:underline'>guia de utilização</a>." },
            { "q": "Posso usar a roda no meu telemóvel ?", "a": "<strong>Sim, claro !</strong> O nosso site é totalmente responsivo, o que significa que foi concebido para funcionar perfeitamente em todos os dispositivos: computadores, tablets e smartphones. A experiência está otimizada para que possa girar a roda onde quer que esteja." },
            { "q": "Como são guardadas as minhas opções ?", "a": "A configuração da sua roda, incluindo as suas opções personalizadas, é <strong>automaticamente guardada no armazenamento local do seu navegador</strong> (`localStorage`). Isto significa que quando regressar, encontrará a sua roda tal como a deixou. É 100% privado e seguro no seu dispositivo." },
            { "q": "Como posso partilhar a minha roda personalizada ?", "a": "É muito fácil ! Utilize o botão <strong>'Partilhar'</strong> localizado no cabeçalho da página. Isto irá gerar um link URL único contendo a configuração da sua roda, perfeito para jogos à distância !" },
            { "q": "Os meus dados são realmente privados ?", "a": "<strong>A privacidade é a nossa prioridade absoluta.</strong> Todos os dados da sua roda (opções e histórico) são armazenados <strong>apenas no seu dispositivo</strong>. Não recolhemos, vemos ou armazenamos nenhuma destas informações nos nossos servidores. Para mais detalhes, não hesite em consultar a nossa <a href='/pt/politica-de-privacidade' class='text-primary hover:underline'>Política de Privacidade</a>." }
        ],
        ctaTitle: "Crie a sua própria roda de viagens",
        ctaText: "Quer fazer uma roda com as capitais da Europa ou as praias da Tailândia ? Crie a sua própria <strong>roda da sorte</strong> personalizada agora.",
        ctaLink: "➤ Criar uma Roda Personalizada"
    }
}
