
export const translations = {
    fr: {
        metaTitle: "Roue de la Chance Europe de l'Ouest | Roue aléatoire des Pays",
        metaDescription: "Tirez au sort un pays d'Europe avec notre roue des pays d'Europe de l'Ouest. Une roulette en ligne amusante pour les jeux, l'éducation ou pour trouver une destination.",
        ogImage: 'https://avisclients.digitalextension.fr/wp-content/uploads/2025/07/western-europe.webp',
        pageTitle: "Roue de la Chance des Pays d'Europe de l'Ouest",
        description: "Lancez cette roue aléatoire pour un tirage de pays et inspirez votre prochain voyage en Europe.",
        storageWarning: "Sauvegarde automatique : Vos options de roue et l'historique sont enregistrés dans votre navigateur.",
        spinButton: "LANCER",
        customizeTooltip: "Personnaliser",
        shuffleTooltip: "Mélanger",
        resultsTooltip: "Historique",
        hideTooltip: "Masquer le panneau",
        showTooltip: "Afficher le panneau",
        defaultOptions: [
            { id: 'fr', name: 'France' },
            { id: 'de', name: 'Allemagne' },
            { id: 'gb', name: 'Royaume-Uni' },
            { id: 'ie', name: 'Irlande' },
            { id: 'be', name: 'Belgique' },
            { id: 'nl', name: 'Pays-Bas' },
            { id: 'lu', name: 'Luxembourg' },
            { id: 'ch', name: 'Suisse' },
            { id: 'at', name: 'Autriche' },
            { id: 'li', name: 'Liechtenstein' },
            { id: 'mc', name: 'Monaco' },
        ],
        sectionTitle: "Explorez l'Europe avec notre <strong>Roue de la Chance des Pays</strong>",
        sectionDescription: "Un outil ludique et éducatif pour découvrir les pays d'Europe. Idéal pour les jeux, l'apprentissage ou pour choisir votre prochaine destination avec notre roulette aléatoire !",
        whatIsTitle: "Qu'est-ce que la Roue des Pays d'Europe de l'Ouest ?",
        whatIsText: "C'est une version thématique de notre <a href=\"/fr\" class=\"text-primary hover:underline\">roue aléatoire</a>, pré-remplie avec les pays d'Europe occidentale et leurs drapeaux. Chaque lancer de cette roue en ligne hasard vous permet de sélectionner un pays de manière 100% aléatoire.",
        whyUseTitle: "Pourquoi utiliser cette roue en ligne ?",
        whyUseText: "Que vous soyez un enseignant cherchant à dynamiser un cours de géographie, un groupe d'amis planifiant un voyage, ou simplement curieux, cette roue de la chance personnalisable ajoute une dimension amusante à la découverte. Utilisez-la pour rendre l'apprentissage interactif ou pour décider de manière ludique de votre prochaine aventure.",
        howToUseTitle: "Comment ça marche ?",
        howToUseSteps: [
            "<strong>Examinez la liste :</strong> La roue est pré-remplie avec les pays d'Europe de l'Ouest.",
            "<strong>Personnalisez si besoin :</strong> Utilisez le panneau de contrôle pour ajouter ou supprimer des pays de la liste de cette roue du hasard.",
            "<strong>Lancez la roue :</strong> Cliquez sur \"LANCER\" pour découvrir quel pays sera sélectionné par la roulette aléatoire!",
        ],
        ideasTitle: "Idées d'utilisation",
        ideasItems: [
            "<strong>Jeu de géographie :</strong> Tirez un pays au sort et demandez aux participants de nommer sa capitale.",
            "<strong>Planification de voyage :</strong> Indécis sur votre prochaine destination ? Laissez la roue de la chance en ligne choisir pour vous.",
            "<strong>Soirées à thème :</strong> Le pays sélectionné par la roue aléatoire inspire le thème de votre prochaine soirée (cuisine, musique, etc.).",
            "<strong>Apprentissage des langues :</strong> Tirez un pays et apprenez à dire \"Bonjour\" dans sa langue officielle."
        ],
        faqTitle: "Questions Fréquemment Posées",
        faqItems: [
            { "q": "La roue est-elle vraiment aléatoire ?", "a": "<strong>Absolument.</strong> Notre roue du hasard utilise un algorithme de Génération de Nombres Aléatoires de pointe pour garantir que chaque résultat est <strong>totalement imprévisible et indépendant</strong> des tours précédents. Chaque segment a une probabilité égale d'être sélectionné, assurant un tirage 100% juste et équitable. Pour en savoir plus sur le fonctionnement, vous pouvez consulter notre <a href='/fr/guide-roue-de-la-chance' class='text-primary hover:underline'>guide d'utilisation</a>." },
            { "q": "Puis-je utiliser la roue sur mon téléphone mobile ?", "a": "<strong>Oui, bien sûr !</strong> Notre site est entièrement \"responsive\", ce qui signifie que notre roue en ligne est conçue pour fonctionner parfaitement sur tous les appareils : ordinateurs de bureau, tablettes et smartphones. L'expérience est optimisée pour que vous puissiez faire tourner la roue où que vous soyez, quand vous le voulez." },
            { "q": "Comment sont sauvegardées mes options ?", "a": "La configuration de votre roue de la chance, y compris les options, est <strong>automatiquement sauvegardée dans le stockage local de votre navigateur</strong> (`localStorage`). Cela signifie que lorsque vous revenez sur notre site, vous retrouvez votre roue telle que vous l'avez laissée. C'est 100% privé et sécurisé sur votre appareil." },
            { "q": "Comment partager ma roue personnalisée ?", "a": "C'est très facile ! Utilisez le bouton <strong>'Partager'</strong> situé dans l'en-tête de la page. Cela générera un lien URL unique contenant la configuration de votre roue. Vous pourrez copier ce lien et l'envoyer à vos amis. Ils utiliseront alors exactement la même roue aléatoire que vous, ce qui est parfait pour les jeux à distance !" },
            { "q": "Mes données sont-elles vraiment privées ?", "a": "<strong>La confidentialité est notre priorité absolue.</strong> Toutes les données de votre roue (options et historique) sont stockées <strong>uniquement sur votre appareil</strong>. Nous ne collectons, ne voyons, ni ne stockons aucune de ces informations sur nos serveurs. C'est une des raisons pour lesquelles notre outil est si rapide et sécurisé. Pour plus de détails, n'hésitez pas à consulter notre <a href='/fr/politique-de-confidentialite' class='text-primary hover:underline'>Politique de Confidentialité</a>." }
        ],
        ctaTitle: "Prêt à créer la vôtre ?",
        ctaText: "Besoin d'une roue avec des options différentes ? Créez votre propre roue de la chance 100% personnalisée.",
        ctaLink: "➤ Créer une Roue Aléatoire"
    },
    en: {
        metaTitle: "Western Europe Spin Wheel | Random Country Picker",
        metaDescription: "Spin our online wheel to pick a random country from Western Europe. A fun random picker and custom spinner for geography games or travel inspiration.",
        ogImage: 'https://avisclients.digitalextension.fr/wp-content/uploads/2025/07/western-europe.webp',
        pageTitle: "Western Europe Spin Wheel",
        description: "Use our country spin wheel generator to inspire your next trip to Europe.",
        storageWarning: "Automatic saving: Your wheel options and history are saved in your browser.",
        spinButton: "SPIN",
        customizeTooltip: "Customize",
        shuffleTooltip: "Shuffle",
        resultsTooltip: "History",
        hideTooltip: "Hide panel",
        showTooltip: "Show panel",
        defaultOptions: [
            { id: 'fr', name: 'France' },
            { id: 'de', name: 'Germany' },
            { id: 'gb', name: 'United Kingdom' },
            { id: 'ie', name: 'Ireland' },
            { id: 'be', name: 'Belgium' },
            { id: 'nl', name: 'Netherlands' },
            { id: 'lu', name: 'Luxembourg' },
            { id: 'ch', name: 'Switzerland' },
            { id: 'at', name: 'Austria' },
            { id: 'li', name: 'Liechtenstein' },
            { id: 'mc', name: 'Monaco' },
        ],
        sectionTitle: "Explore Europe with our <strong>Country Spin Wheel</strong>",
        sectionDescription: "A fun and educational tool to discover European countries. Ideal for games, learning, or choosing your next travel destination with our random spinner!",
        whatIsTitle: "What is the Western Europe Countries Wheel?",
        whatIsText: "This is a themed version of our <a href=\"/en\" class=\"text-primary hover:underline\">random spin wheel</a>, pre-filled with Western European countries and their flags. Each spin allows you to select a country 100% randomly, perfect for educational activities or games.",
        whyUseTitle: "Why use this spin wheel?",
        whyUseText: "Whether you're a teacher looking to liven up a geography class, a group of friends planning a trip, or just curious, this custom spin wheel adds a fun dimension to discovery. Use it to make learning interactive or to playfully decide on your next European adventure.",
        howToUseTitle: "How does it work?",
        howToUseSteps: [
            "<strong>Examine the list:</strong> The spin wheel is pre-filled with Western European countries.",
            "<strong>Customize if needed:</strong> Use the control panel to add or remove countries from the list of this random picker.",
            "<strong>Spin the wheel:</strong> Click \"SPIN\" to find out which country will be randomly selected by the spinner!",
        ],
        ideasTitle: "Usage Ideas",
        ideasItems: [
            "<strong>Geography game:</strong> Randomly pick a country and have participants name its capital.",
            "<strong>Trip planning:</strong> Undecided on your next destination? Let the spin wheel online choose for you.",
            "<strong>Themed parties:</strong> The selected country inspires the theme of your next party (cuisine, music, etc.).",
            "<strong>Language learning:</strong> Pick a country and learn to say \"Hello\" in its official language."
        ],
        faqTitle: "Frequently Asked Questions",
        faqItems: [
            { "q": "Is the wheel truly random?", "a": "<strong>Absolutely.</strong> Our spin wheel uses a state-of-the-art Random Number Generator (RNG) algorithm to ensure that every result is <strong>completely unpredictable and independent</strong> of previous spins. Each segment has an equal probability of being selected, guaranteeing a 100% fair draw. You can learn more in our <a href='/en/guide-spin-wheel-of-chance' class='text-primary hover:underline'>user guide</a>." },
            { "q": "Can I use the spin wheel on my mobile phone?", "a": "<strong>Yes, of course!</strong> Our website is fully responsive, which means it is designed to work perfectly on all devices: desktops, tablets, and smartphones. The experience is optimized so you can spin the wheel wherever and whenever you want." },
            { "q": "How is my custom wheel configuration saved?", "a": "Your wheel configuration, including your custom options, is <strong>automatically saved in your browser's local storage</strong> (`localStorage`). This means when you return to our site, you'll find your wheel just as you left it. It's 100% private and secure on your device." },
            { "q": "How can I share my custom wheel?", "a": "It's very easy! Use the <strong>'Share' button</strong> in the page header. This will generate a unique URL containing your wheel's setup. You can copy this link and send it to your friends. They will then be able to use the exact same random wheel as you, which is perfect for remote games!" },
            { "q": "Is my data really private?", "a": "<strong>Privacy is our absolute priority.</strong> All your wheel data (options and history) is stored <strong>only on your device</strong>. We do not collect, see, or store any of this information on our servers. This is one of the reasons our tool is so fast and secure. For more details, feel free to consult our <a href='/en/privacy-policy' class='text-primary hover:underline'>Privacy Policy</a>." }
        ],
        ctaTitle: "Ready to create your own?",
        ctaText: "Need a wheel with different options? Create your own 100% customized wheel of chance.",
        ctaLink: "➤ Create a Random Wheel"
    },
    es: {
        metaTitle: "Ruleta en Línea de Europa Occidental | Sorteo de Países",
        metaDescription: "Gira la ruleta para elegir un país de Europa Occidental al azar. Una herramienta de sorteo divertida para aprender geografía o inspirar tu próximo viaje.",
        ogImage: 'https://avisclients.digitalextension.fr/wp-content/uploads/2025/07/western-europe.webp',
        pageTitle: "Ruleta de Europa Occidental",
        description: "Gira la ruleta para un sorteo de países e inspira tu próximo viaje por Europa.",
        storageWarning: "Guardado automático: Tus opciones de ruleta y el historial se guardan en tu navegador.",
        spinButton: "GIRAR",
        customizeTooltip: "Personalizar",
        shuffleTooltip: "Mezclar",
        resultsTooltip: "Historial",
        hideTooltip: "Ocultar panel",
        showTooltip: "Mostrar panel",
        defaultOptions: [
            { id: 'fr', name: 'Francia' },
            { id: 'de', name: 'Alemania' },
            { id: 'gb', name: 'Reino Unido' },
            { id: 'ie', name: 'Irlanda' },
            { id: 'be', name: 'Bélgica' },
            { id: 'nl', name: 'Países Bajos' },
            { id: 'lu', name: 'Luxemburgo' },
            { id: 'ch', name: 'Suiza' },
            { id: 'at', name: 'Austria' },
            { id: 'li', name: 'Liechtenstein' },
            { id: 'mc', name: 'Mónaco' },
        ],
        sectionTitle: "Explora Europa con nuestra <strong>Ruleta de Países</strong>",
        sectionDescription: "Una herramienta lúdica y educativa para descubrir países europeos. ¡Ideal para juegos, aprendizaje o para elegir tu próximo destino de viaje!",
        whatIsTitle: "¿Qué es la Ruleta de Países de Europa Occidental?",
        whatIsText: "Es una versión temática de nuestra <a href=\"/es\" class=\"text-primary hover:underline\">ruleta aleatoria</a>, precargada con los países de Europa Occidental y sus banderas. Cada giro te permite seleccionar un país de forma 100% aleatoria, perfecta para actividades educativas o juegos.",
        whyUseTitle: "¿Por qué usar esta ruleta?",
        whyUseText: "Tanto si eres un profesor que busca amenizar una clase de geografía, un grupo de amigos planeando un viaje, o simplemente un curioso, esta ruleta añade una dimensión divertida al descubrimiento. Úsala para hacer el aprendizaje interactivo o para decidir de forma lúdica tu próxima aventura europea.",
        howToUseTitle: "¿Cómo funciona?",
        howToUseSteps: [
            "<strong>Examina la lista:</strong> La ruleta está precargada con los países de Europa Occidental.",
            "<strong>Personaliza si es necesario:</strong> Usa el panel de control para añadir o eliminar países de la lista.",
            "<strong>Gira la ruleta:</strong> ¡Haz clic en \"GIRAR\" para descubrir qué país será seleccionado al azar!",
        ],
        ideasTitle: "Ideas de uso",
        ideasItems: [
            "<strong>Juego de geografía:</strong> Sortea un país y pide a los participantes que nombren su capital.",
            "<strong>Planificación de viajes:</strong> ¿Indeciso sobre tu próximo destino? Deja que la ruleta elija por ti.",
            "<strong>Fiestas temáticas:</strong> El país seleccionado inspira el tema de tu próxima fiesta (cocina, música, etc.).",
            "<strong>Aprendizaje de idiomas:</strong> Sortea un país y aprende a decir \"Hola\" en su idioma oficial."
        ],
        faqTitle: "Preguntas Frecuentes",
        faqItems: [
            { "q": "¿La ruleta es realmente aleatoria?", "a": "<strong>Absolutamente.</strong> Nuestra ruleta utiliza un algoritmo de Generador de Números Aleatorios (RNG) para garantizar que cada resultado sea <strong>impredecible e independiente</strong> de los giros anteriores. Cada segmento tiene la misma probabilidad de ser seleccionado, asegurando un sorteo 100% justo. Puedes aprender más en nuestra <a href='/es/guia-ruleta-de-la-suerte' class='text-primary hover:underline'>guía de uso</a>." },
            { "q": "¿Puedo usar la ruleta en mi teléfono móvil?", "a": "<strong>¡Sí, claro!</strong> Nuestro sitio está completamente diseñado para funcionar perfectamente en todos los dispositivos: ordenadores, tabletas y teléfonos inteligentes. La experiencia está optimizada para que puedas girar la ruleta estés donde estés." },
            { "q": "¿Cómo se guardan mis opciones?", "a": "La configuración de tu ruleta, incluyendo tus opciones personalizadas, se <strong>guarda automáticamente en el almacenamiento local de tu navegador</strong> (`localStorage`). Esto significa que cuando regreses, encontrarás tu ruleta tal como la dejaste. ¡Es 100% privado y seguro en tu dispositivo!" },
            { "q": "¿Cómo comparto mi ruleta personalizada?", "a": "¡Es muy fácil! Utiliza el botón <strong>'Compartir'</strong> situado en el encabezado de la página. Esto generará un enlace URL único que contiene la configuración de tu ruleta. Puedes copiar este enlace y enviarlo a tus amigos, lo que es perfecto para juegos a distancia." },
            { "q": "¿Mis datos son realmente privados?", "a": "<strong>La privacidad es nuestra máxima prioridad.</strong> Todos los datos de tu ruleta (opciones e historial) se almacenan <strong>únicamente en tu dispositivo</strong>. No recopilamos, vemos ni almacenamos ninguna de esta información en nuestros servidores. Para más detalles, no dudes en consultar nuestra <a href='/es/politica-de-privacidad' class='text-primary hover:underline'>Política de Privacidad</a>." }
        ],
        ctaTitle: "¿Listo para crear la tuya?",
        ctaText: "¿Necesitas una ruleta con opciones diferentes? Crea tu propia ruleta de la suerte 100% personalizada.",
        ctaLink: "➤ Crear una Ruleta Aleatoria"
    },
    de: {
        metaTitle: "Westeuropa-Glücksrad | Länder-Zufallsrad",
        metaDescription: "Drehen Sie das Glücksrad, um ein zufälliges westeuropäisches Land auszuwählen. Ein lustiges Drehrad zum Lernen von Geografie oder zur Inspiration für Ihre nächste Reise.",
        ogImage: 'https://avisclients.digitalextension.fr/wp-content/uploads/2025/07/western-europe.webp',
        pageTitle: "Westeuropa-Glücksrad",
        description: "Drehen Sie das Glücksrad für eine zufällige Länderauswahl und lassen Sie sich für Ihre nächste Europareise inspirieren.",
        storageWarning: "Automatische Speicherung: Ihre Radoptionen und der Verlauf werden in Ihrem Browser gespeichert.",
        spinButton: "DREHEN",
        customizeTooltip: "Anpassen",
        shuffleTooltip: "Mischen",
        resultsTooltip: "Verlauf",
        hideTooltip: "Panel ausblenden",
        showTooltip: "Panel anzeigen",
        defaultOptions: [
            { id: 'fr', name: 'Frankreich' },
            { id: 'de', name: 'Deutschland' },
            { id: 'gb', name: 'Vereinigtes Königreich' },
            { id: 'ie', name: 'Irland' },
            { id: 'be', name: 'Belgien' },
            { id: 'nl', name: 'Niederlande' },
            { id: 'lu', name: 'Luxemburg' },
            { id: 'ch', name: 'Schweiz' },
            { id: 'at', name: 'Österreich' },
            { id: 'li', name: 'Liechtenstein' },
            { id: 'mc', name: 'Monaco' },
        ],
        sectionTitle: "Entdecken Sie Europa mit unserem <strong>Länder-Glücksrad</strong>",
        sectionDescription: "Ein unterhaltsames und lehrreiches Werkzeug zur Entdeckung europäischer Länder. Ideal für Spiele, zum Lernen oder zur Auswahl Ihres nächsten Reiseziels mit unserem Glücksrad!",
        whatIsTitle: "Was ist das Westeuropa-Glücksrad?",
        whatIsText: "Dies ist eine thematische Version unseres <a href=\"/de\" class=\"text-primary hover:underline\">Zufallsrads</a>, das mit westeuropäischen Ländern und ihren Flaggen vorab ausgefüllt ist. Jeder Dreh ermöglicht es Ihnen, ein Land 100% zufällig auszuwählen, perfekt für Bildungsaktivitäten oder Spiele.",
        whyUseTitle: "Warum dieses Glücksrad verwenden?",
        whyUseText: "Egal, ob Sie ein Lehrer sind, der den Geografieunterricht beleben möchte, eine Gruppe von Freunden, die eine Reise planen, oder einfach nur neugierig sind, dieses Glücksrad fügt der Entdeckung eine unterhaltsame Dimension hinzu. Nutzen Sie es, um das Lernen interaktiv zu gestalten oder spielerisch über Ihr nächstes europäisches Abenteuer zu entscheiden.",
        howToUseTitle: "Wie funktioniert es?",
        howToUseSteps: [
            "<strong>Überprüfen Sie die Liste:</strong> Das Glücksrad ist mit westeuropäischen Ländern vorab ausgefüllt.",
            "<strong>Bei Bedarf anpassen:</strong> Verwenden Sie das Bedienfeld, um Länder zur Liste hinzuzufügen oder zu entfernen.",
            "<strong>Drehen Sie das Glücksrad:</strong> Klicken Sie auf \"DREHEN\", um herauszufinden, welches Land zufällig ausgewählt wird!",
        ],
        ideasTitle: "Anwendungsideen",
        ideasItems: [
            "<strong>Geografiespiel:</strong> Wählen Sie zufällig ein Land aus und lassen Sie die Teilnehmer die Hauptstadt nennen.",
            "<strong>Reiseplanung:</strong> Unentschlossen über Ihr nächstes Reiseziel? Lassen Sie das Glücksrad für sich entscheiden.",
            "<strong>Themenpartys:</strong> Das ausgewählte Land inspiriert das Thema Ihrer nächsten Party (Küche, Musik usw.).",
            "<strong>Sprachenlernen:</strong> Wählen Sie ein Land aus und lernen Sie, \"Hallo\" in der offiziellen Sprache zu sagen."
        ],
        faqTitle: "Häufig gestellte Fragen",
        faqItems: [
            { "q": "Ist das Glücksrad wirklich zufällig?", "a": "<strong>Absolut.</strong> Unser Glücksrad verwendet einen Zufallszahlengenerator (RNG), um sicherzustellen, dass jedes Ergebnis <strong>unvorhersehbar und unabhängig</strong> von früheren Drehungen ist. Jedes Segment hat die gleiche Wahrscheinlichkeit, was eine 100% faire Ziehung garantiert. Erfahren Sie mehr in unserer <a href='/de/anleitung-zufallsrad' class='text-primary hover:underline'>Anleitung</a>." },
            { "q": "Kann ich das Glücksrad auf meinem Handy benutzen?", "a": "<strong>Ja, natürlich!</strong> Unsere Seite ist vollständig so konzipiert, dass sie auf allen Geräten perfekt funktioniert: Desktops, Tablets und Smartphones. Das Erlebnis ist optimiert, damit Sie das Glücksrad drehen können, wo immer Sie sind." },
            { "q": "Wie werden meine Optionen gespeichert?", "a": "Ihre Glücksrad-Konfiguration wird <strong>automatisch in Ihrem Browser gespeichert</strong> (`localStorage`). Das bedeutet, wenn Sie zurückkehren, finden Sie Ihr Glücksrad so vor, wie Sie es verlassen haben. Es ist 100% privat und sicher auf Ihrem Gerät." },
            { "q": "Wie teile ich mein benutzerdefiniertes Glücksrad?", "a": "Ganz einfach! Verwenden Sie die Schaltfläche <strong>'Teilen'</strong> im Kopfbereich der Seite. Dadurch wird ein eindeutiger URL-Link generiert, der Ihre Glücksrad-Konfiguration enthält, perfekt für Fernspiele!" },
            { "q": "Sind meine Daten wirklich privat?", "a": "<strong>Datenschutz hat für uns oberste Priorität.</strong> Alle Ihre Glücksrad-Daten (Optionen und Verlauf) werden <strong>nur auf Ihrem Gerät</strong> gespeichert. Wir sammeln, sehen oder speichern keine dieser Informationen auf unseren Servern. Für weitere Details können Sie gerne unsere <a href='/de/datenschutzrichtlinie' class='text-primary hover:underline'>Datenschutzrichtlinie</a> konsultieren." }
        ],
        ctaTitle: "Bereit, Ihr eigenes zu erstellen?",
        ctaText: "Benötigen Sie ein Rad mit anderen Optionen? Erstellen Sie Ihr eigenes 100% individuelles Glücksrad.",
        ctaLink: "➤ Erstellen Sie ein Zufallsrad"
    },
    pt: {
        metaTitle: "Roda Online da Europa Ocidental | Sorteador de Países",
        metaDescription: "Gire a nossa roleta online para escolher um país da Europa Ocidental aleatoriamente. Uma ferramenta de sorteio divertida para aprender geografia ou inspirar a sua próxima viagem.",
        ogImage: 'https://avisclients.digitalextension.fr/wp-content/uploads/2025/07/western-europe.webp',
        pageTitle: "Roda da Europa Ocidental",
        description: "Gire a roleta para um sorteio de países e inspire a sua próxima viagem pela Europa.",
        storageWarning: "Gravação automática: As suas opções de roda e o histórico são guardados no seu navegador.",
        spinButton: "GIRAR",
        customizeTooltip: "Personalizar",
        shuffleTooltip: "Baralhar",
        resultsTooltip: "Histórico",
        hideTooltip: "Ocultar painel",
        showTooltip: "Mostrar painel",
        defaultOptions: [
            { id: 'fr', name: 'França' },
            { id: 'de', name: 'Alemanha' },
            { id: 'gb', name: 'Reino Unido' },
            { id: 'ie', name: 'Irlanda' },
            { id: 'be', name: 'Bélgica' },
            { id: 'nl', name: 'Países Baixos' },
            { id: 'lu', name: 'Luxemburgo' },
            { id: 'ch', name: 'Suíça' },
            { id: 'at', name: 'Áustria' },
            { id: 'li', name: 'Liechtenstein' },
            { id: 'mc', name: 'Mónaco' },
        ],
        sectionTitle: "Explore a Europa com a nossa <strong>Roda dos Países</strong>",
        sectionDescription: "Uma ferramenta divertida e educativa para descubrir os países europeus. Ideal para jogos, aprendizagem ou para escolher o seu próximo destino de viagem!",
        whatIsTitle: "O que é a Roda dos Países da Europa Ocidental?",
        whatIsText: "Esta é uma versão temática da nossa <a href=\"/pt\" class=\"text-primary hover:underline\">roda aleatória</a>, pré-preenchida com os países da Europa Ocidental e as suas bandeiras. Cada volta permite-lhe selecionar um país de forma 100% aleatória, perfeita para atividades educativas ou jogos.",
        whyUseTitle: "Por que usar esta roda?",
        whyUseText: "Quer seja um professor a tentar dinamizar uma aula de geografia, um grupo de amigos a planear uma viagem, ou simplesmente curioso, esta roda adiciona uma dimensão divertida à descoberta. Use-a para tornar a aprendizagem interativa ou para decidir de forma lúdica a sua próxima aventura europeia.",
        howToUseTitle: "Como funciona?",
        howToUseSteps: [
            "<strong>Examine a lista:</strong> A roda está pré-preenchida com os países da Europa Ocidental.",
            "<strong>Personalize se necessário:</strong> Use o painel de controlo para adicionar ou remover países da lista.",
            "<strong>Gire a roda:</strong> Clique em \"GIRAR\" para descubrir que país será selecionado ao acaso!",
        ],
        ideasTitle: "Ideias de utilização",
        ideasItems: [
            "<strong>Jogo de geografia:</strong> Sorteie um país e peça aos participantes para nomearem a sua capital.",
            "<strong>Planeamento de viagens:</strong> Indeciso sobre o seu próximo destino? Deixe a roda escolher por si.",
            "<strong>Festas temáticas:</strong> O país selecionado inspira o tema da sua próxima festa (culinária, música, etc.).",
            "<strong>Aprendizagem de línguas:</strong> Sorteie um país e aprenda a dizer \"Olá\" na sua língua oficial."
        ],
        faqTitle: "Perguntas Frequentes",
        faqItems: [
            { "q": "A roda é realmente aleatória?", "a": "<strong>Absolutamente.</strong> A nossa roda utiliza um gerador de números aleatórios (RNG) para garantir que cada resultado é <strong>imprevisível e independente</strong> das rotações anteriores. Cada segmento tem a mesma probabilidade de ser selecionado, garantindo um sorteio 100% justo. Pode saber mais no nosso <a href='/pt/guia-roda-da-sorte' class='text-primary hover:underline'>guia de utilização</a>." },
            { "q": "Posso usar a roda no meu telemóvel?", "a": "<strong>Sim, claro!</strong> O nosso site é totalmente responsivo, o que significa que foi concebido para funcionar perfeitamente em todos os dispositivos: computadores, tablets e smartphones. A experiência está otimizada para que possa girar a roda onde quer que esteja." },
            { "q": "Como são guardadas as minhas opções?", "a": "A configuração da sua roda, incluindo as suas opções personalizadas, é <strong>automaticamente guardada no armazenamento local do seu navegador</strong> (`localStorage`). Isto significa que quando regressar, encontrará a sua roda tal como a deixou. É 100% privado e seguro no seu dispositivo." },
            { "q": "Como posso partilhar a minha roda personalizada?", "a": "É muito fácil! Utilize o botão <strong>'Partilhar'</strong> localizado no cabeçalho da página. Isto irá gerar um link URL único contendo a configuração da sua roda, perfeito para jogos à distância!" },
            { "q": "Os meus dados são realmente privados?", "a": "<strong>A privacidade é a nossa prioridade absoluta.</strong> Todos os dados da sua roda (opções e histórico) são armazenados <strong>apenas no seu dispositivo</strong>. Não recolhemos, vemos ou armazenamos nenhuma destas informações nos nossos servidores. Para mais detalhes, não hesite em consultar a nossa <a href='/pt/politica-de-privacidade' class='text-primary hover:underline'>Política de Privacidade</a>." }
        ],
        ctaTitle: "Pronto para criar a sua própria?",
        ctaText: "Precisa de uma roda com opções diferentes? Crie a sua própria roda da sorte 100% personalizada.",
        ctaLink: "➤ Criar uma Roda Aleatória"
    }
}
