
export const translations = {
    fr: {
        metaTitle: "Nouveautés | Les Derniers Outils de la Roue de la Chance",
        metaDescription: "Découvrez les dernières nouveautés et les nouveaux outils de notre application de roue de la chance. Restez à jour avec nos fonctionnalités de roulette aléatoire et de tirage au sort.",
        title: "Nouveautés de la Roue de la Chance",
        description: "Découvrez les derniers outils et fonctionnalités ajoutés à notre application de roue en ligne. La liste est classée du plus récent au plus ancien.",
        launchTool: "Lancer l'outil",
        ctaTitle: "Prêt à faire tourner la roue ?",
        ctaText: "Maintenant que vous avez vu les nouveautés, retournez sur la page d'accueil pour créer votre propre roue personnalisée !",
        ctaLink: "Créer une Roue Aléatoire",
        tools: [
            { 
                title: "Pile ou Face Euro", 
                date: "Août 2024",
                description: "Une variante de notre populaire jeu de pile ou face, utilisant une pièce d'euro pour une touche européenne. Ce tirage au sort 50/50 est une alternative simple à la roue de la chance.", 
                slugKey: "coin-flip-dollar",
                url: "https://pileouface.net/pile-ou-face/euro",
            },
            { 
                title: "Jeu 2048", 
                date: "Août 2024",
                description: "Le jeu de puzzle classique où vous combinez des tuiles pour atteindre le score de 2048. Un excellent complément à notre roue de la chance pour un défi de logique et de stratégie.", 
                slugKey: "game-2048",
                url: "https://jeu-2048.com/",
            },
            { 
                title: "Dé en Ligne", 
                date: "Août 2024",
                description: "Notre dé en ligne 3D est un lanceur de dé virtuel parfait pour tous vos jeux de société. Une alternative moderne à la roue aléatoire pour un tirage au sort de 1 à 6.", 
                slugKey: "dice-roller",
            },
            { 
                title: "Pile ou Face", 
                date: "Août 2024",
                description: "Pour une décision rapide 50/50, notre simulateur de pile ou face est idéal. C'est l'alternative la plus simple à la roue de la chance pour un tirage au sort à deux options.", 
                slugKey: "coin-flip",
            },
            {
                title: "Roue des 10 Pays les Plus Visités",
                date: "Juillet 2024",
                description: "Utilisez notre générateur de destination aléatoire pour votre prochain voyage. Cette roue de la chance thématique est parfaite pour trouver l'inspiration.",
                slugKey: "top-10-countries",
            },
            {
                title: "Roue des Films d'Action",
                date: "Juillet 2024",
                description: "Fini les débats pour la soirée cinéma ! Laissez notre roulette en ligne de films d'action faire un tirage au sort parmi les meilleurs classiques.",
                slugKey: "top-10-action-movies",
            },
            { 
                title: "Roue de l'Alphabet (A-Z)", 
                date: "Juillet 2024",
                description: "L'outil indispensable pour le jeu du Petit Bac. Notre roue de l'alphabet effectue un tirage au sort de lettre rapide pour tous vos jeux de mots.", 
                slugKey: "alphabet",
            },
            {
                title: "Roue de l'Europe de l'Ouest",
                date: "Juillet 2024",
                description: "Une roue en ligne éducative pour les cours de géographie ou pour choisir une destination de voyage en Europe de manière ludique.",
                slugKey: "western-europe",
            },
            { 
                title: "Roue des Couleurs", 
                date: "Juillet 2024",
                description: "Le générateur de couleurs aléatoires pour les artistes. Cette roue de la chance est un excellent outil pour trouver l'inspiration pour une palette.", 
                slugKey: 'color-wheel',
            },
            { 
                title: "Roue Oui, Non, Peut-être", 
                date: "Juillet 2024",
                description: "Pour les décisions qui méritent de la nuance. Une roue de décision à trois options quand un simple oui ou non ne suffit pas.", 
                slugKey: "yes-no-maybe",
            },
            { 
                title: "Roue Oui ou Non", 
                date: "Juillet 2024",
                description: "La roue de décision ultime pour une réponse rapide. Ce tirage au sort 50/50 est l'outil le plus simple pour toute question binaire.", 
                slugKey: "yes-no",
            },
        ]
    },
    en: {
        metaTitle: "What's New | Latest Tools from Wheel of Chance",
        metaDescription: "Discover the latest updates and new tools from our spin wheel application. Stay up-to-date with our random picker and spinner features.",
        title: "What's New on Wheel of Chance?",
        description: "Discover the latest tools and features added to our online wheel application. The list is sorted from newest to oldest.",
        launchTool: "Launch Tool",
        ctaTitle: "Ready to spin the wheel?",
        ctaText: "Now that you've seen what's new, head back to the homepage to create your own custom wheel!",
        ctaLink: "Create a Random Wheel",
        tools: [
            { 
                title: "Coin Flip Euro", 
                date: "August 2024",
                description: "A variation of our popular coin flip game, using a Euro coin for a European touch. Perfect for a quick and familiar draw.", 
                slugKey: "coin-flip-dollar",
                url: "https://pileouface.net/pile-ou-face/euro",
            },
             { 
                title: "2048 Game", 
                date: "August 2024",
                description: "The classic puzzle game where you combine tiles to reach 2048. A great addition to our spin wheel for a challenge of logic and strategy.", 
                slugKey: "game-2048",
                url: "https://jeu-2048.com/",
            },
            { 
                title: "Online Dice Roller", 
                date: "August 2024",
                description: "Our 3D online dice roller is a virtual die perfect for all your board games. A modern alternative to the random picker for a 1-6 draw.", 
                slugKey: "dice-roller",
            },
            { 
                title: "Coin Flip", 
                date: "August 2024",
                description: "For a quick 50/50 decision, our coin flip simulator is ideal. It's the simplest alternative to the spin wheel for a two-option draw.", 
                slugKey: "coin-flip",
            },
            {
                title: "Top 10 Visited Countries Wheel",
                date: "July 2024",
                description: "Use our random destination generator for your next trip. This themed spin wheel is perfect for finding travel inspiration.",
                slugKey: "top-10-countries",
            },
            {
                title: "Action Movies Spin Wheel",
                date: "July 2024",
                description: "Movie night? Let our action movies online spinner make a random pick from the best classics for you. No more endless debates!",
                slugKey: "top-10-action-movies",
            },
            { 
                title: "Alphabet Spin Wheel (A-Z)", 
                date: "July 2024",
                description: "The essential tool for Scattergories. Our alphabet wheel performs a quick letter draw for all your word games.", 
                slugKey: "alphabet",
            },
            {
                title: "Western Europe Wheel",
                date: "July 2024",
                description: "A fun online wheel for geography classes or for choosing a travel destination in Europe in a playful way.",
                slugKey: "western-europe",
            },
            { 
                title: "Color Spin Wheel", 
                date: "July 2024",
                description: "The random color generator for artists. This spin wheel is an excellent tool for finding palette inspiration.", 
                slugKey: 'color-wheel',
            },
            { 
                title: "Yes, No, Maybe Spin Wheel", 
                date: "July 2024",
                description: "For decisions that require more nuance. A three-option decision wheel when a simple yes or no is not enough.", 
                slugKey: "yes-no-maybe",
            },
            { 
                title: "Yes or No Spin Wheel", 
                date: "July 2024",
                description: "The ultimate decision-making tool for a quick answer. This 50/50 random picker is the simplest tool for any binary question.", 
                slugKey: "yes-no",
            },
        ]
    },
    es: {
        metaTitle: "Novedades | Últimas Herramientas de la Ruleta de la Suerte",
        metaDescription: "Descubre las últimas actualizaciones y nuevas herramientas de nuestra aplicación de ruleta giratoria. Mantente al día con nuestras funcionalidades de ruleta aleatoria.",
        title: "¿Qué hay de nuevo en la Ruleta de la Suerte?",
        description: "Descubre las últimas herramientas y funcionalidades añadidas a nuestra aplicación de ruleta online. La lista está ordenada de la más reciente a la más antigua.",
        launchTool: "Lanzar Herramienta",
        ctaTitle: "¿Listo para girar la ruleta?",
        ctaText: "Ahora que has visto las novedades, ¡vuelve a la página de inicio para crear tu propia ruleta personalizada!",
        ctaLink: "Crear una Ruleta Aleatoria",
        tools: [
            { 
                title: "Cara o Cruz Euro", 
                date: "Agosto 2024",
                description: "Una variante de nuestro popular juego de cara o cruz, usando una moneda de euro para un toque europeo. Perfecto para un sorteo rápido y familiar.", 
                slugKey: "coin-flip-dollar",
                url: "https://pileouface.net/pile-ou-face/euro",
            },
            { 
                title: "Juego 2048", 
                date: "Agosto 2024",
                description: "El clásico juego de rompecabezas donde combinas fichas para alcanzar 2048. Un gran complemento a nuestra ruleta de la suerte para un desafío de lógica.", 
                slugKey: "game-2048",
                url: "https://jeu-2048.com/",
            },
            { 
                title: "Dado en Línea", 
                date: "Agosto 2024",
                description: "Nuestro dado en línea 3D es un lanzador de dados virtual perfecto para tus juegos. Una alternativa moderna a la ruleta aleatoria para un sorteo del 1 al 6.", 
                slugKey: "dice-roller",
            },
            { 
                title: "Cara o Cruz", 
                date: "Agosto 2024",
                description: "Para una decisión rápida 50/50, nuestro simulador de cara o cruz es ideal. La alternativa más simple a la ruleta giratoria para un sorteo de dos opciones.", 
                slugKey: "coin-flip",
            },
            {
                title: "Ruleta de los 10 Países Más Visitados",
                date: "Julio 2024",
                description: "Utiliza nuestro generador de destinos aleatorio para tu próximo viaje. Esta rueda de la fortuna temática es perfecta para encontrar inspiración.",
                slugKey: "top-10-countries",
            },
            {
                title: "Ruleta de Películas de Acción",
                date: "Julio 2024",
                description: "¡Noche de cine? Deja que nuestra ruleta online de películas de acción haga un sorteo entre los mejores clásicos para ti.",
                slugKey: "top-10-action-movies",
            },
            { 
                title: "Ruleta del Alfabeto (A-Z)", 
                date: "Julio 2024",
                description: "La herramienta indispensable para el juego de Tutti Frutti. Nuestra ruleta del alfabeto realiza un sorteo rápido de letras para tus juegos de palabras.", 
                slugKey: "alphabet",
            },
            {
                title: "Ruleta de Europa Occidental",
                date: "Julio 2024",
                description: "Una ruleta en línea educativa para las clases de geografía o para elegir un destino de viaje en Europa de forma lúdica.",
                slugKey: "western-europe",
            },
            { 
                title: "Ruleta de Colores", 
                date: "Julio 2024",
                description: "El generador de colores aleatorios para artistas. Esta rueda de la fortuna es una excelente herramienta para encontrar inspiración para una paleta.", 
                slugKey: 'color-wheel',
            },
            { 
                title: "Ruleta Sí, No, Quizás", 
                date: "Julio 2024",
                description: "Para decisiones que requieren más matices. Una ruleta de decisión de tres opciones cuando un simple sí o no no es suficiente.", 
                slugKey: "yes-no-maybe",
            },
            { 
                title: "Ruleta Sí o No", 
                date: "Julio 2024",
                description: "La herramienta de decisión definitiva para una respuesta rápida. Este sorteo 50/50 es la herramienta más simple para cualquier pregunta binaria.", 
                slugKey: "yes-no",
            },
        ]
    },
    de: {
        metaTitle: "Neuigkeiten | Neueste Tools vom Glücksrad",
        metaDescription: "Entdecken Sie die neuesten Updates und neuen Tools unserer Glücksrad-Anwendung. Bleiben Sie mit unseren Zufallsrad-Funktionen auf dem Laufenden.",
        title: "Was ist neu am Glücksrad?",
        description: "Entdecken Sie die neuesten Tools und Funktionen, die unserer Online-Rad-Anwendung hinzugefügt wurden. Die Liste ist von der neuesten zur ältesten sortiert.",
        launchTool: "Tool starten",
        ctaTitle: "Bereit, das Rad zu drehen?",
        ctaText: "Nachdem Sie die Neuigkeiten gesehen haben, kehren Sie zur Startseite zurück, um Ihr eigenes Rad zu erstellen!",
        ctaLink: "Ein Zufallsrad erstellen",
        tools: [
            { 
                title: "Kopf oder Zahl Euro", 
                date: "August 2024",
                description: "Eine Variante unseres beliebten Kopf-oder-Zahl-Spiels mit einer Euro-Münze für einen europäischen Touch. Perfekt für eine schnelle und vertraute Ziehung.", 
                slugKey: "coin-flip-dollar",
                url: "https://pileouface.net/pile-ou-face/euro",
            },
            { 
                title: "Spiel 2048", 
                date: "August 2024",
                description: "Das klassische Puzzlespiel, bei dem Sie Kacheln kombinieren, um 2048 zu erreichen. Eine tolle Ergänzung zu unserem Glücksrad für eine logische Herausforderung.", 
                slugKey: "game-2048",
                url: "https://jeu-2048.com/",
            },
            { 
                title: "Online Würfel", 
                date: "August 2024",
                description: "Unser 3D-Online-Würfel ist ein virtueller Würfel, perfekt für all Ihre Brettspiele. Eine moderne Alternative zum Zufallsrad für eine 1-6-Ziehung.", 
                slugKey: "dice-roller",
            },
            { 
                title: "Kopf oder Zahl", 
                date: "August 2024",
                description: "Für eine schnelle 50/50-Entscheidung ist unser Kopf-oder-Zahl-Simulator ideal. Die einfachste Alternative zum Drehrad für eine Zwei-Optionen-Ziehung.", 
                slugKey: "coin-flip",
            },
            {
                title: "Top 10 Besuchte Länder Rad",
                date: "Juli 2024",
                description: "Nutzen Sie unseren Zufallsgenerator für Ihr nächstes Reiseziel. Dieses thematische Glücksrad ist perfekt, um Reiseinspiration zu finden.",
                slugKey: "top-10-countries",
            },
            {
                title: "Actionfilme-Glücksrad",
                date: "Juli 2024",
                description: "Filmabend? Lassen Sie unser Actionfilme-Online-Drehrad einen zufälligen Klassiker für Sie auswählen. Keine endlosen Debatten mehr!",
                slugKey: "top-10-action-movies",
            },
            { 
                title: "Alphabet-Glücksrad (A-Z)", 
                date: "Juli 2024",
                description: "Das unverzichtbare Werkzeug für Stadt, Land, Fluss. Unser Alphabet-Rad führt eine schnelle Buchstabenziehung für all Ihre Wortspiele durch.", 
                slugKey: "alphabet",
            },
            {
                title: "Westeuropa-Rad",
                date: "Juli 2024",
                description: "Ein unterhaltsames Online-Rad für den Geografieunterricht oder zur spielerischen Auswahl eines Reiseziels in Europa.",
                slugKey: "western-europe",
            },
            { 
                title: "Farben-Glücksrad", 
                date: "Juli 2024",
                description: "Der Zufallsfarbengenerator für Künstler. Dieses Glücksrad ist ein ausgezeichnetes Werkzeug, um Paletteninspiration zu finden.", 
                slugKey: 'color-wheel',
            },
            { 
                title: "Ja, Nein, Vielleicht Glücksrad", 
                date: "Juli 2024",
                description: "Für Entscheidungen, die mehr Nuancen erfordern. Ein Entscheidungsrad mit drei Optionen, wenn ein einfaches Ja oder Nein nicht ausreicht.", 
                slugKey: "yes-no-maybe",
            },
            { 
                title: "Ja oder Nein Glücksrad", 
                date: "Juli 2024",
                description: "Das ultimative Entscheidungswerkzeug für eine schnelle Antwort. Diese 50/50-Zufallsziehung ist das einfachste Werkzeug für jede binäre Frage.", 
                slugKey: "yes-no",
            },
        ]
    },
    pt: {
        metaTitle: "Novidades | Últimas Ferramentas da Roda da Sorte",
        metaDescription: "Descubra as últimas atualizações e novas ferramentas da nossa aplicação de roleta giratória. Mantenha-se atualizado com as nossas funcionalidades de roda da sorte.",
        title: "Novidades na Roda da Sorte",
        description: "Descubra as últimas ferramentas e funcionalidades adicionadas à nossa aplicação de roda online. A lista está ordenada da mais recente para a mais antiga.",
        launchTool: "Lançar Ferramenta",
        ctaTitle: "Pronto para girar a roda?",
        ctaText: "Agora que já viu as novidades, volte à página inicial para criar a sua própria roda personalizada!",
        ctaLink: "Criar uma Roda Aleatória",
        tools: [
            { 
                title: "Cara ou Coroa Euro", 
                date: "Agosto 2024",
                description: "Uma variação do nosso popular jogo de cara ou coroa, usando uma moeda de euro para um toque europeu. Perfeito para um sorteio rápido e familiar.", 
                slugKey: "coin-flip-dollar",
                url: "https://pileouface.net/pile-ou-face/euro",
            },
            { 
                title: "Jogo 2048", 
                date: "Agosto 2024",
                description: "O clássico jogo de quebra-cabeça onde combina peças para chegar a 2048. Um ótimo complemento à nossa roda da sorte para um desafio de lógica.", 
                slugKey: "game-2048",
                url: "https://jeu-2048.com/",
            },
            { 
                title: "Dado Online", 
                date: "Agosto 2024",
                description: "O nosso dado online 3D é um dado virtual perfeito para todos os seus jogos de tabuleiro. Uma alternativa moderna à roleta aleatória para um sorteio de 1 a 6.", 
                slugKey: "dice-roller",
            },
            { 
                title: "Cara ou Coroa", 
                date: "Agosto 2024",
                description: "Para uma decisão rápida 50/50, o nosso simulador de cara ou coroa é ideal. A alternativa mais simples à roda giratória para um sorteio de duas opções.", 
                slugKey: "coin-flip",
            },
            {
                title: "Roda dos 10 Países Mais Visitados",
                date: "Julho 2024",
                description: "Use o nosso gerador de destinos aleatório para a sua próxima viagem. Esta roda da sorte temática é perfeita para encontrar inspiração.",
                slugKey: "top-10-countries",
            },
            {
                title: "Roda de Filmes de Ação",
                date: "Julho 2024",
                description: "Noite de cinema? Deixe a nossa roleta online de filmes de ação fazer um sorteio entre os melhores clássicos para si.",
                slugKey: "top-10-action-movies",
            },
            { 
                title: "Roda do Alfabeto (A-Z)", 
                date: "Julho 2024",
                description: "A ferramenta essencial para o jogo do Stop. A nossa roda do alfabeto realiza um sorteio rápido de letras para todos os seus jogos de palavras.", 
                slugKey: "alphabet",
            },
            {
                title: "Roda da Europa Ocidental",
                date: "Julho 2024",
                description: "Uma roleta online educativa para as aulas de geografia ou para escolher um destino de viagem na Europa de forma lúdica.",
                slugKey: "western-europe",
            },
            { 
                title: "Roda das Cores", 
                date: "Julho 2024",
                description: "O gerador de cores aleatórias para artistas. Esta roda da sorte é uma excelente ferramenta para encontrar inspiração para uma paleta.", 
                slugKey: 'color-wheel',
            },
            { 
                title: "Roda Sim, Não, Talvez", 
                date: "Julho 2024",
                description: "Para decisões que requerem mais nuances. Uma roleta de decisão com três opções quando um simples sim ou não não é suficiente.", 
                slugKey: "yes-no-maybe",
            },
            { 
                title: "Roda Sim ou Não", 
                date: "Julho 2024",
                description: "A ferramenta de decisão definitiva para uma resposta rápida. Este sorteio 50/50 é a ferramenta mais simples para qualquer questão binária.", 
                slugKey: "yes-no",
            },
        ]
    }
};
