
export const translations = {
    fr: {
        metaTitle: "Roue de la Chance Oui ou Non | Roue de Décision Aléatoire",
        metaDescription: "Besoin de prendre une décision ? Notre roue Oui ou Non est une roulette aléatoire gratuite pour un tirage au sort 50/50. Lancez la roue de la chance pour un résultat instantané !",
        ogImage: 'https://avisclients.digitalextension.fr/wp-content/uploads/2025/07/oui-non-roue-de-la-chance.webp',
        pageTitle: "Roue de la Chance : Oui ou Non ?",
        description: "Lancez cette Roue aléatoire pour une décision rapide ou un tirage Oui ou Non.",
        storageWarning: "Sauvegarde automatique : L'historique des résultats est enregistré dans votre navigateur.",
        spinButton: "LANCER",
        customizeTooltip: "Personnaliser",
        shuffleTooltip: "Mélanger",
        resultsTooltip: "Historique",
        hideTooltip: "Masquer le panneau",
        showTooltip: "Afficher le panneau",
        clear: "Vider",
        draw: "Tirage",
        noResults: "Aucun résultat. Lancez la roue !",
        customizationDisabledTitle: "Roue non personnalisable",
        customizationDisabledDescription: "Cette roue thématique ne peut pas être modifiée. Pour créer votre propre roue, allez sur la page d'accueil.",
        sectionTitle: "La <strong>Roue Oui/Non</strong> : Votre Aide à la Décision Instantanée",
        sectionDescription: "Simple, rapide et efficace. Cette roue de la chance est conçue pour vous donner une réponse claire et immédiate à n'importe quelle question binaire.",
        whatIsTitle: "Qu'est-ce que la Roue Oui/Non ?",
        whatIsText: "C'est une roue de décision en ligne avec seulement deux options : 'Oui' et 'Non'. Chaque option a une probabilité égale de 50% d'être choisie, ce qui en fait un outil de tirage au sort perfectly équilibré pour toutes vos interrogations.",
        whyUseTitle: "Pourquoi utiliser cette roue du hasard ?",
        whyUseText: "Pour éliminer l'indécision ! Face à un choix difficile ou pour pimenter une situation, cette roue aléatoire apporte une réponse ludique et impartiale. Elle est parfaite pour sortir de l'impasse et avancer.",
        howToUseTitle: "Comment l'utiliser ?",
        howToUseSteps: [
            "<strong>Posez votre question :</strong> Pensez à la question à laquelle vous voulez une réponse par oui ou par non.",
            "<strong>Lancez la roue :</strong> Cliquez sur le bouton central \"LANCER\".",
            "<strong>Acceptez le destin :</strong> La roue s'arrêtera sur 'Oui' ou 'Non', vous donnant une direction claire."
        ],
        ideasTitle: "Quand utiliser la roue Oui/Non ?",
        ideasItems: [
            "<strong>Décisions quotidiennes :</strong> \"Dois-je commander une pizza ce soir ?\"",
            "<strong>Défis entre amis :</strong> \"Devrais-je envoyer ce message audacieux ?\"",
            "<strong>Motivation :</strong> \"Est-ce que je fais ma séance de sport maintenant ?\"",
            "<strong>Jeux de société :</strong> Utilisez la roue pour déterminer les actions dans un jeu."
        ],
        reliabilityTitle: "Cette roue est-elle fiable pour de vraies décisions ?",
        reliabilityText: "Bien que notre roue soit <strong>100% aléatoire</strong>, elle est avant tout un outil de divertissement. Pour les décisions importantes de la vie (carrière, relations, finances), nous vous recommandons de vous fier à votre propre jugement. Utilisez la roue pour vous amuser et vous aider à voir vos propres désirs cachés (si vous êtes déçu du résultat, c'est que vous vouliez l'autre option !).",
        faqTitle: "Questions Fréquemment Posées",
        faqItems: [
            { "q": "La probabilité est-elle vraiment de 50/50 ?", "a": "<strong>Oui, absolument.</strong> L'algorithme derrière la roue garantit une répartition parfaitement équitable entre le 'Oui' et le 'Non'. Chaque lancer est un événement indépendant, comme lancer une pièce de monnaie." },
            { "q": "Puis-je ajouter d'autres options ?", "a": "Cette roue est spécifiquement conçue pour le Oui/Non. Si vous voulez plus d'options, comme 'Peut-être', essayez notre <a href='/fr/roue-de-la-chance-oui-non-peut-etre' class='text-primary hover:underline'>roue Oui/Non/Peut-être</a> ou créez la vôtre sur la <a href='/fr' class='text-primary hover:underline'>page d'accueil</a>!" },
            { "q": "Comment puis-je partager mon résultat ?", "a": "Après que la roue s'est arrêtée sur un résultat, une fenêtre contextuelle apparaît. Dans cette fenêtre, vous trouverez un bouton 'Partager'. Cela vous permet de partager facilement votre résultat 'Oui' ou 'Non' avec des amis sur les réseaux sociaux ou par messagerie." },
            { "q": "Y a-t-il un moyen de voir les résultats passés ?", "a": "<strong>Oui !</strong> Le panneau de contrôle à côté de la roue dispose d'un onglet 'Historique'. Il sauvegarde automatiquement vos résultats les plus récents, afin que vous puissiez suivre votre parcours de prise de décision. Cet historique est stocké de manière privée sur votre appareil." },
            { "q": "Dois-je créer un compte pour utiliser la roue ?", "a": "<strong>Aucun compte n'est nécessaire.</strong> Notre roue Oui/Non est entièrement gratuite et ne nécessite aucune inscription. Vous pouvez visiter la page et commencer à prendre des décisions instantanément." }
        ],
        probabilityTitle: "Probabilité et Hasard",
        probabilityText: "Chaque tour de roue est un événement indépendant avec une probabilité de 50% pour chaque issue. Obtenir 'Oui' cinq fois de suite ne rend pas le 'Non' plus probable au sixième tour. C'est la beauté du hasard!",
        disclaimer: "*À utiliser pour le divertissement. Ne basez pas les décisions qui changent une vie sur le résultat d'une roue.",
        ctaTitle: "Besoin de plus de nuances ?",
        ctaText: "Parfois, la vie n'est pas juste noire ou blanche. Pour ces moments-là, personnalisez votre propre roue!",
        ctaLink: "➤ Créer une Roue Personnalisée"
    },
    en: {
        metaTitle: "Yes or No Spin Wheel | Random Decision Maker",
        metaDescription: "Need to make a decision? Our Yes or No spin wheel is a free random picker for a 50/50 draw. Spin the wheel online for an instant answer!",
        ogImage: 'https://avisclients.digitalextension.fr/wp-content/uploads/2025/07/oui-non-roue-de-la-chance.webp',
        pageTitle: "Yes or No Spin Wheel",
        description: "Use our Yes or No spin wheel generator for a quick 50/50 decision.",
        storageWarning: "Automatic saving: The results history is saved in your browser.",
        spinButton: "SPIN",
        resultsTitle: "History",
        customizeTooltip: "Customize",
        shuffleTooltip: "Shuffle",
        resultsTooltip: "History",
        hideTooltip: "Hide panel",
        showTooltip: "Show panel",
        clear: "Clear",
        draw: "Draw",
        noResults: "No results. Spin the wheel!",
        customizationDisabledTitle: "Wheel Not Customizable",
        customizationDisabledDescription: "This themed wheel cannot be modified. To create your own wheel, go to the homepage.",
        sectionTitle: "The <strong>Yes/No Wheel</strong>: Your Instant Decision Helper",
        sectionDescription: "Simple, fast, and effective. This wheel is designed to give you a clear and immediate answer to any binary question.",
        whatIsTitle: "What is the Yes/No Wheel?",
        whatIsText: "It's an online decision wheel with only two options: 'Yes' and 'No'. Each option has an equal 50% probability of being chosen, making it a perfectly balanced drawing tool for all your questions.",
        whyUseTitle: "Why use this wheel?",
        whyUseText: "To eliminate indecision! When faced with a difficult choice or to spice up a situation, this random wheel provides a fun and impartial answer. It's perfect for breaking deadlocks and moving forward.",
        howToUseTitle: "How to use it?",
        howToUseSteps: [
            "<strong>Ask your question:</strong> Think of the question you want a yes or no answer to.",
            "<strong>Spin the wheel:</strong> Click the central \"SPIN\" button.",
            "<strong>Accept your fate:</strong> The wheel will stop on 'Yes' or 'No', giving you a clear direction."
        ],
        ideasTitle: "When to use the Yes/No wheel?",
        ideasItems: [
            "<strong>Daily decisions:</strong> \"Should I order a pizza tonight?\"",
            "<strong>Challenges with friends:</strong> \"Should I send that bold text?\"",
            "<strong>Motivation:</strong> \"Should I do my workout now?\"",
            "<strong>Board games:</strong> Use the wheel to determine actions in a game."
        ],
        reliabilityTitle: "Is this wheel reliable for real decisions?",
        reliabilityText: "While our wheel is <strong>100% random</strong>, it is primarily an entertainment tool. For important life decisions (career, relationships, finances), we recommend relying on your own judgment. Use the wheel for fun and to help you see your own hidden desires (if you're disappointed with the result, you probably wanted the other option!).",
        faqTitle: "Frequently Asked Questions",
        faqItems: [
            { "q": "Is the probability really 50/50?", "a": "<strong>Yes, absolutely.</strong> The algorithm behind the wheel ensures a perfectly fair distribution between 'Yes' and 'No'. Each spin is an independent event, just like flipping a coin." },
            { "q": "Can I add other options?", "a": "This wheel is specifically designed for Yes/No. If you want more options, like 'Maybe', try our <a href='/en/yes-no-maybe-spin-wheel' class='text-primary hover:underline'>Yes/No/Maybe wheel</a> or create your own on the <a href='/en' class='text-primary hover:underline'>homepage</a>!" },
            { "q": "How can I share my result?", "a": "After the wheel lands on a result, a pop-up will appear. In that pop-up, you'll find a 'Share' button. This lets you easily share your 'Yes' or 'No' outcome with friends on social media or messaging apps." },
            { "q": "Is there a way to see past results?", "a": "<strong>Yes!</strong> The control panel next to the wheel has a 'History' tab. It automatically saves your most recent results, so you can track your decision-making journey. This history is stored privately on your device." },
            { "q": "Do I need an account to use the wheel?", "a": "<strong>No account is needed.</strong> Our Yes/No wheel is completely free to use without any registration. You can visit the page and start making decisions instantly." }
        ],
        probabilityTitle: "Probability and Chance",
        probabilityText: "Each spin of the wheel is an independent event with a 50% probability for each outcome. Getting 'Yes' five times in a row does not make 'No' more likely on the sixth spin. That's the beauty of chance!",
        disclaimer: "*For entertainment purposes only. Do not base life-changing decisions on the outcome of a wheel.",
        ctaTitle: "Need more nuance?",
        ctaText: "Sometimes, life isn't just black or white. For those moments, customize your own wheel!",
        ctaLink: "➤ Create a Custom Wheel"
    },
    es: {
        metaTitle: "Ruleta Sí o No | Rueda Giratoria de Decisiones Aleatorias",
        metaDescription: "¿Necesitas tomar una decisión? Nuestra ruleta Sí o No es una rueda de la fortuna online gratis para un sorteo 50/50. ¡Gira la ruleta giratoria para obtener una respuesta al instante!",
        ogImage: 'https://avisclients.digitalextension.fr/wp-content/uploads/2025/07/oui-non-roue-de-la-chance.webp',
        pageTitle: "Ruleta Giratoria: ¿Sí o No?",
        description: "Gira la ruleta para una decisión rápida. Una rueda de la fortuna para un sorteo de Sí o No.",
        storageWarning: "Guardado automático: El historial de resultados se guarda en tu navegador.",
        spinButton: "GIRAR",
        resultsTitle: "Historial",
        hideTooltip: "Ocultar panel",
        showTooltip: "Mostrar panel",
        clear: "Limpiar",
        draw: "Sorteo",
        noResults: "Sin resultados. ¡Gira la ruleta!",
        customizationDisabledTitle: "Ruleta no personalizable",
        customizationDisabledDescription: "Esta ruleta temática no se puede modificar. Para crear tu propia ruleta, ve a la página de inicio.",
        sectionTitle: "La <strong>Rueda Giratoria Sí/No</strong>: Tu Ayuda para Decisiones Instantáneas",
        sectionDescription: "Simple, rápida y eficaz. Esta rueda de la fortuna está diseñada para darte una respuesta clara e inmediata a cualquier pregunta binaria.",
        whatIsTitle: "¿Qué es la Ruleta Sí/No?",
        whatIsText: "Es una ruleta de decisión online con solo dos opciones: 'Sí' y 'No'. Cada opción tiene una probabilidad igual del 50% de ser elegida, lo que la convierte en una herramienta perfectamente equilibrada para todas tus preguntas.",
        whyUseTitle: "Por qué usar esta ruleta giratoria online gratis?",
        whyUseText: "¡Para eliminar la indecisión! Ante una elección difícil, esta ruleta aleatoria aporta una respuesta lúdica e imparcial. Es perfecta para salir del estancamiento y seguir adelante.",
        howToUseTitle: "¿Cómo funciona?",
        howToUseSteps: [
            "<strong>Haz tu pregunta:</strong> Piensa en la pregunta a la que quieres una respuesta de sí o no.",
            "<strong>Gira la ruleta:</strong> Haz clic en el botón central \"GIRAR\".",
            "<strong>Acepta el destino:</strong> La ruleta se detendrá en 'Sí' o 'No', dándote una dirección clara."
        ],
        ideasTitle: "¿Cuándo usar la ruleta Sí/No?",
        ideasItems: [
            "<strong>Decisiones diarias:</strong> \"¿Debería pedir pizza esta noche?\"",
            "<strong>Retos entre amigos:</strong> \"¿Debería enviar ese mensaje atrevido?\"",
            "<strong>Motivación:</strong> \"¿Hago mi sesión de ejercicio ahora?\"",
            "<strong>Juegos de mesa:</strong> Usa la rueda para determinar acciones en un juego."
        ],
        reliabilityTitle: "¿Es fiable esta rueda para decisiones reales?",
        reliabilityText: "Aunque nuestra ruleta es <strong>100% aleatoria</strong>, es ante todo una herramienta de entretenimiento. Para decisiones importantes de la vida (carrera, relaciones, finanzas), te recomendamos que te fíes de tu propio juicio. Usa la rueda para divertirte y ayudarte a ver tus propios deseos ocultos (si te decepciona el resultado, ¡es que querías la otra opción!).",
        faqTitle: "Preguntas Frecuentes",
        faqItems: [
            { "q": "¿La probabilidad es realmente 50/50?", "a": "<strong>Sí, absolutamente.</strong> El algoritmo detrás de la ruleta garantiza una distribución perfectamente equitativa entre 'Sí' y 'No'. Cada giro es un evento independiente, como lanzar una moneda." },
            { "q": "¿Puedo añadir otras opciones?", "a": "Esta ruleta está diseñada específicamente para Sí/No. Si quieres más opciones, como 'Quizás', prueba nuestra <a href='/es/ruleta-giratoria-si-no-quizas' class='text-primary hover:underline'>ruleta Sí/No/Quizás</a> o crea la tuya en la <a href='/es' class='text-primary hover:underline'>página de inicio</a>!" },
            { "q": "¿Cómo puedo compartir mi resultado?", "a": "Después de que la ruleta se detenga, aparecerá una ventana emergente. En esa ventana, encontrarás un botón 'Compartir'. Esto te permite compartir fácilmente tu resultado de 'Sí' o 'No' con amigos en redes sociales o aplicaciones de mensajería." },
            { "q": "¿Hay alguna forma de ver los resultados anteriores?", "a": "<strong>¡Sí!</strong> El panel de control junto a la ruleta tiene una pestaña de 'Historial'. Guarda automáticamente tus resultados más recientes, para que puedas seguir tu viaje de toma de decisiones. Este historial se almacena de forma privada en tu dispositivo." },
            { "q": "¿Necesito una cuenta para usar la ruleta?", "a": "<strong>No se necesita cuenta.</strong> Nuestra ruleta Sí/No es completamente gratuita y no requiere registro. Puedes visitar la página y empezar a tomar decisiones al instante." }
        ],
        probabilityTitle: "Probabilidad y Azar",
        probabilityText: "Cada giro de la ruleta es un evento independiente con una probabilidad del 50% para cada resultado. Obtener 'Sí' cinco veces seguidas no hace que 'No' sea más probable en el sexto giro. ¡Esa es la belleza del azar!",
        disclaimer: "*Para fines de entretenimiento. No bases decisiones que cambian la vida en el resultado de una ruleta.",
        ctaTitle: "¿Necesitas más matices?",
        ctaText: "A veces, la vida no es solo blanco o negro. ¡Para esos momentos, personaliza tu propia ruleta!",
        ctaLink: "➤ Crear una Rueda de Premios Personalizada"
    },
    de: {
        metaTitle: "Ja oder Nein Glücksrad | Zufälliger Entscheider & Drehrad",
        metaDescription: "Treffen Sie eine schnelle Entscheidung mit unserem Ja/Nein-Glücksrad. Dieses kostenlose Drehrad ist das perfekte Werkzeug für eine 50/50-Zufallsziehung. Drehen Sie das Glücksrad für eine sofortige Antwort!",
        ogImage: 'https://avisclients.digitalextension.fr/wp-content/uploads/2025/07/oui-non-roue-de-la-chance.webp',
        pageTitle: "Ja oder Nein Glücksrad?",
        description: "Drehen Sie dieses Glücksrad für eine schnelle Ja- oder Nein-Entscheidung.",
        storageWarning: "Automatische Speicherung: Der Ergebnisverlauf wird in Ihrem Browser gespeichert.",
        spinButton: "DREHEN",
        resultsTitle: "Verlauf",
        customizeTooltip: "Anpassen",
        shuffleTooltip: "Mischen",
        resultsTooltip: "Verlauf",
        hideTooltip: "Panel ausblenden",
        showTooltip: "Panel anzeigen",
        clear: "Leeren",
        draw: "Ziehung",
        noResults: "Keine Ergebnisse. Drehen Sie das Glücksrad!",
        customizationDisabledTitle: "Rad nicht anpassbar",
        customizationDisabledDescription: "Dieses thematische Rad kann nicht geändert werden. Um Ihr eigenes Rad zu erstellen, gehen Sie zur Startseite.",
        sectionTitle: "Das <strong>Ja/Nein-Glücksrad</strong>: Ihre sofortige Entscheidungshilfe",
        sectionDescription: "Einfach, schnell und effektiv. Dieses Glücksrad wurde entwickelt, um Ihnen eine klare und sofortige Antwort auf jede binäre Frage zu geben.",
        whatIsTitle: "Was ist das Ja/Nein-Glücksrad?",
        whatIsText: "Es ist ein Online-Entscheidungsrad mit nur zwei Optionen: 'Ja' und 'Nein'. Jede Option hat eine gleiche Wahrscheinlichkeit von 50%, ausgewählt zu werden, was es zu einem perfekt ausgewogenen Ziehungswerkzeug für all Ihre Fragen macht.",
        whyUseTitle: "Warum dieses Drehrad verwenden?",
        whyUseText: "Um Unentschlossenheit zu beseitigen! Bei einer schwierigen Wahl oder um eine Situation aufzupeppen, bietet dieses Glücksrad eine unterhaltsame und unparteiische Antwort. Es ist perfekt, um aus Sackgassen herauszukommen und vorwärts zu kommen.",
        howToUseTitle: "Wie wird es benutzt?",
        howToUseSteps: [
            "<strong>Stellen Sie Ihre Frage:</strong> Denken Sie an die Frage, auf die Sie eine Ja- oder Nein-Antwort haben möchten.",
            "<strong>Drehen Sie das Glücksrad:</strong> Klicken Sie auf den zentralen \"DREHEN\"-Button.",
            "<strong>Akzeptieren Sie Ihr Schicksal:</strong> Das Rad hält bei 'Ja' oder 'Nein' an und gibt Ihnen eine klare Richtung."
        ],
        ideasTitle: "Wann das Ja/Nein-Rad verwenden?",
        ideasItems: [
            "<strong>Tägliche Entscheidungen:</strong> \"Soll ich heute Abend Pizza bestellen?\"",
            "<strong>Herausforderungen mit Freunden:</strong> \"Soll ich diese mutige Nachricht senden?\"",
            "<strong>Motivation:</strong> \"Soll ich jetzt mein Training machen?\"",
            "<strong>Brettspiele:</strong> Verwenden Sie das Glücksrad, um Aktionen in einem Spiel zu bestimmen."
        ],
        reliabilityTitle: "Ist dieses Rad für echte Entscheidungen zuverlässig?",
        reliabilityText: "Obwohl unser Rad <strong>100% zufällig</strong> ist, ist es in erster Linie ein Unterhaltungswerkzeug. Für wichtige Lebensentscheidungen (Karriere, Beziehungen, Finanzen) empfehlen wir Ihnen, sich auf Ihr eigenes Urteilsvermögen zu verlassen. Verwenden Sie das Glücksrad zum Spaß und um Ihre eigenen verborgenen Wünsche zu erkennen (wenn Sie vom Ergebnis enttäuscht sind, wollten Sie wahrscheinlich die andere Option!).",
        faqTitle: "Häufig gestellte Fragen",
        faqItems: [
            { "q": "Ist die Wahrscheinlichkeit wirklich 50/50?", "a": "<strong>Ja, absolut.</strong> Der Algorithmus hinter dem Rad garantiert eine perfekt faire Verteilung zwischen 'Ja' und 'Nein'. Jeder Dreh ist ein unabhängiges Ereignis, genau wie beim Münzwurf." },
            { "q": "Kann ich andere Optionen hinzufügen?", "a": "Dieses Rad ist speziell für Ja/Nein konzipiert. Wenn Sie mehr Optionen wie 'Vielleicht' möchten, probieren Sie unser <a href='/de/ja-nein-vielleicht-rad' class='text-primary hover:underline'>Ja/Nein/Vielleicht-Rad</a> oder erstellen Sie Ihr eigenes auf der <a href='/de' class='text-primary hover:underline'>Startseite</a>!" },
            { "q": "Wie kann ich mein Ergebnis teilen?", "a": "Nachdem das Rad ein Ergebnis anzeigt, erscheint ein Pop-up. Dort finden Sie einen 'Teilen'-Button, mit dem Sie Ihr 'Ja'- oder 'Nein'-Ergebnis ganz einfach in sozialen Medien oder über Messaging-Apps teilen können." },
            { "q": "Gibt es eine Möglichkeit, frühere Ergebnisse zu sehen?", "a": "<strong>Ja!</strong> Das Bedienfeld neben dem Rad hat einen 'Verlauf'-Tab. Es speichert automatisch Ihre letzten Ergebnisse, sodass Sie Ihre Entscheidungsfindung nachverfolgen können. Dieser Verlauf wird privat auf Ihrem Gerät gespeichert." },
            { "q": "Benötige ich ein Konto, um das Glücksrad zu benutzen?", "a": "<strong>Kein Konto erforderlich.</strong> Unser Ja/Nein-Rad ist komplett kostenlos und ohne Registrierung nutzbar. Sie können die Seite besuchen und sofort mit dem Entscheiden beginnen." }
        ],
        probabilityTitle: "Wahrscheinlichkeit und Zufall",
        probabilityText: "Jeder Dreh des Rades ist ein unabhängiges Ereignis mit einer Wahrscheinlichkeit von 50% für jedes Ergebnis. Fünfmal hintereinander 'Ja' zu bekommen, macht 'Nein' beim sechsten Dreh nicht wahrscheinlicher. Das ist das Schöne am Zufall!",
        disclaimer: "*Nur zu Unterhaltungszwecken. Basieren Sie keine lebensverändernden Entscheidungen auf dem Ergebnis eines Rades.",
        ctaTitle: "Brauchen Sie mehr Nuancen?",
        ctaText: "Manchmal ist das Leben nicht nur schwarz oder weiß. Für diese Momente passen Sie Ihr eigenes Glücksrad an!",
        ctaLink: "➤ Erstellen Sie ein benutzerdefiniertes Glücksrad"
    },
    pt: {
        metaTitle: "Roda da Sorte Sim ou Não | Roleta de Decisão Aleatória",
        metaDescription: "Precisa de tomar uma decisão? A nossa roda da sorte Sim ou Não é uma roleta giratória grátis para um sorteio 50/50. Gire a roda para uma resposta instantânea!",
        ogImage: 'https://avisclients.digitalextension.fr/wp-content/uploads/2025/07/oui-non-roue-de-la-chance.webp',
        pageTitle: "Roda da Sorte: Sim ou Não?",
        description: "Gire esta roleta giratória para uma decisão rápida ou um sorteio Sim ou Não.",
        storageWarning: "Gravação automática: O histórico de resultados é guardado no seu navegador.",
        spinButton: "GIRAR",
        resultsTitle: "Histórico",
        hideTooltip: "Ocultar painel",
        showTooltip: "Mostrar painel",
        clear: "Limpar",
        draw: "Sorteio",
        noResults: "Sem resultados. Gire a roda!",
        customizationDisabledTitle: "Roda não personalizável",
        customizationDisabledDescription: "Esta roda temática não pode ser modificada. Para criar a sua própria roda, vá para a página inicial.",
        sectionTitle: "A <strong>Roda da Sorte Sim/Não</strong>: O Seu Ajudante de Decisão Instantânea",
        sectionDescription: "Simples, rápida e eficaz. Esta roda da sorte foi concebida para lhe dar uma resposta clara e imediata a qualquer questão binária.",
        whatIsTitle: "O que é a Roda Sim/Não?",
        whatIsText: "É uma roleta online com apenas duas opções: 'Sim' e 'Não'. Cada opção tem uma probabilidade igual de 50% de ser escolhida, o que a torna uma ferramenta de sorteio perfeitamente equilibrada para todas as suas interrogações.",
        whyUseTitle: "Porquê usar esta roda da sorte?",
        whyUseText: "Para eliminar a indecisão! Perante uma escolha difícil ou para apimentar uma situação, esta roda da sorte proporciona uma resposta divertida e imparcial. É perfeita para sair de impasses e seguir em frente.",
        howToUseTitle: "Como usar a roda giratória?",
        howToUseSteps: [
            "<strong>Faça a sua pergunta:</strong> Pense na pergunta para a qual quer uma resposta de sim ou não.",
            "<strong>Gire a roda da sorte:</strong> Clique no botão central \"GIRAR\".",
            "<strong>Aceite o seu destino:</strong> A roda irá parar em 'Sim' ou 'Não', dando-lhe uma direção clara."
        ],
        ideasTitle: "Quando usar a roda da sorte Sim/Não?",
        ideasItems: [
            "<strong>Decisões diárias:</strong> \"Devo encomendar uma pizza esta noite?\"",
            "<strong>Desafios com amigos:</strong> \"Devo enviar aquela mensagem ousada?\"",
            "<strong>Motivação:</strong> \"Faço o meu treino agora?\"",
            "<strong>Jogos de tabuleiro:</strong> Use a roda da sorte para determinar ações num jogo."
        ],
        reliabilityTitle: "Esta roleta é fiável para decisões reais?",
        reliabilityText: "Embora a nossa roda da sorte seja <strong>100% aleatória</strong>, é principalmente uma ferramenta de entretenimento. Para decisões importantes da vida (carreira, relações, finanças), recomendamos que confie no seu próprio julgamento. Use a roda para se divertir e para o ajudar a ver os seus próprios desejos ocultos (se ficar desapontado com o resultado, é porque provavelmente queria a outra opção!).",
        faqTitle: "Perguntas Frequentes",
        faqItems: [
            { "q": "A probabilidade é realmente 50/50?", "a": "<strong>Sim, absolutamente.</strong> O algoritmo por trás da roda da sorte garante uma distribuição perfeitamente equitativa entre 'Sim' e 'Não'. Cada volta é um evento independente, tal como atirar uma moeda ao ar." },
            { "q": "Posso adicionar outras opções?", "a": "Esta roda foi concebida especificamente para Sim/Não. Se quiser mais opções, como 'Talvez', experimente a nossa <a href='/pt/roda-sim-nao-talvez' class='text-primary hover:underline'>roda Sim/Não/Talvez</a> ou crie a sua própria na <a href='/pt' class='text-primary hover:underline'>página inicial</a>!" },
            { "q": "Como posso partilhar o meu resultado?", "a": "Depois de a roda parar num resultado, aparecerá um pop-up. Nesse pop-up, encontrará um botão 'Partilhar'. Isto permite-lhe partilhar facilmente o seu resultado de 'Sim' ou 'Não' com amigos nas redes sociais ou aplicações de mensagens." },
            { "q": "Existe alguma forma de ver os resultados anteriores?", "a": "<strong>Sim!</strong> O painel de controlo ao lado da roda tem um separador 'Histórico'. Guarda automaticamente os seus resultados mais recentes, para que possa acompanhar o seu percurso de tomada de decisões. Este histórico é armazenado de forma privada no seu dispositivo." },
            { "q": "Preciso de uma conta para usar a roda da sorte?", "a": "<strong>Não é necessária nenhuma conta.</strong> A nossa roda Sim/Não é completamente gratuita e não requer registo. Pode visitar la página e começar a tomar decisões instantaneamente." }
        ],
        probabilityTitle: "Probabilidade e Acaso",
        probabilityText: "Cada volta da roda é um evento independente com uma probabilidade de 50% para cada resultado. Obter 'Sim' cinco vezes seguidas não torna o 'Não' mais provável na sexta volta. Essa é a beleza do acaso!",
        disclaimer: "*Apenas para fins de entretenimento. Não baseie decisões que mudam a vida no resultado de uma roda.",
        ctaTitle: "Precisa de mais nuances?",
        ctaText: "Às vezes, a vida não é apenas a preto e branco. Para esses momentos, personalize a sua própria roda da sorte!",
        ctaLink: "➤ Criar uma Roda da Sorte Personalizada"
    }
}

    
